yun_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/0/09/%28yunt%29.gif",
        "damage": "5",
        "startup": "28",
        "hit": "26",
        "recovery": "28",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/2/2c/%28yunlp%29.gif",
        "damage": "15",
        "startup": "4",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/1/12/%28yunmp%29.gif",
        "damage": "50",
        "startup": "5",
        "hit": "4",
        "recovery": "12",
        "block_adv": "-3",
        "hit_adv": "-2"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/9/9f/%28yunhp%29.gif",
        "damage": "130",
        "startup": "9",
        "hit": "2",
        "recovery": "23",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "http://wiki.shoryuken.com/images/0/0a/%28yuncloselp%29.gif",
        "damage": "15",
        "startup": "3",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "http://wiki.shoryuken.com/images/b/be/%28yunclosemp%29.gif",
        "damage": "60",
        "startup": "4",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+6",
        "hit_adv": "+7"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "http://wiki.shoryuken.com/images/8/84/%28yunclosehp%29.gif",
        "damage": "110",
        "startup": "6",
        "hit": "3",
        "recovery": "13",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/8/8e/%28yunlk%29.gif",
        "damage": "35",
        "startup": "3",
        "hit": "3",
        "recovery": "6",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "http://wiki.shoryuken.com/images/d/d0/%28yunmk%29.gif",
        "damage": "80",
        "startup": "9",
        "hit": "3",
        "recovery": "15",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28yunhk%29.gif",
        "damage": "100",
        "startup": "14",
        "hit": "4",
        "recovery": "22",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "http://wiki.shoryuken.com/images/2/25/%28yunclosemk%29.gif",
        "damage": "30",
        "startup": "5",
        "hit": "9",
        "recovery": "1",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28yunjlp%29.gif",
        "damage": "40(60 neutral jump)",
        "startup": "2",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-4~+7",
        "hit_adv": "-4~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/8/88/%28yunjmp%29.gif",
        "damage": "80",
        "startup": "3",
        "hit": "6(7 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/1/14/%28yunjhp%29.gif",
        "damage": "100(120 neutral jump)",
        "startup": "5(8 neutral jump)",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-4~+10",
        "hit_adv": "-4~+10"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/b/b1/%28yunjlk%29.gif",
        "damage": "40",
        "startup": "3(4 neutral jump)",
        "hit": "12",
        "recovery": "N/A",
        "block_adv": "+1~+7",
        "hit_adv": "+1~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/5/5f/%28yunjmk%29.gif",
        "damage": "70",
        "startup": "6",
        "hit": "7",
        "recovery": "N/A",
        "block_adv": "-3~+10",
        "hit_adv": "-3~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28yunjhk%29.gif",
        "damage": "110",
        "startup": "5",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "-1~+10",
        "hit_adv": "-1~+10"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/4/44/%28yunoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "9",
        "recovery": "6",
        "block_adv": "-5~+2",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hiza Geri",
        "pic": "http://wiki.shoryuken.com/images/3/3d/%28yunhg%29.gif",
        "damage": "160",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Monkey Flip",
        "pic": "http://wiki.shoryuken.com/images/7/75/%28yunmfth%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/0/07/%28yunclp%29.gif",
        "damage": "20",
        "startup": "2",
        "hit": "2",
        "recovery": "1",
        "block_adv": "+13",
        "hit_adv": "+14"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/1/1c/%28yuncmp%29.gif",
        "damage": "40",
        "startup": "3",
        "hit": "2",
        "recovery": "1",
        "block_adv": "+12",
        "hit_adv": "+13"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/9/9e/%28yunchp%29.gif",
        "damage": "90",
        "startup": "3-10",
        "hit": "1-2",
        "recovery": "1",
        "block_adv": "+12",
        "hit_adv": "+13"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/7/7b/%28yunclk%29.gif",
        "damage": "20",
        "startup": "2",
        "hit": "2",
        "recovery": "1",
        "block_adv": "+13",
        "hit_adv": "+13"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/a/ac/%28yuncmk%29.gif",
        "damage": "30",
        "startup": "3",
        "hit": "2",
        "recovery": "4",
        "block_adv": "+7",
        "hit_adv": "+8"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/b/b5/%28yunchk%29.gif",
        "damage": "50",
        "startup": "8",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+5",
        "hit_adv": "knd"
    },
    {
        "name": "f.mk",
        "desc": "Senpuu Kyaku",
        "pic": "http://wiki.shoryuken.com/images/f/f3/%28yunfmk%29.gif",
        "damage": "80",
        "startup": "19",
        "hit": "6",
        "recovery": "18",
        "block_adv": "-1",
        "hit_adv": "0"
    },
    {
        "name": "f.hp",
        "desc": "Dakai",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28yunfhp%29.gif",
        "damage": "140",
        "startup": "17",
        "hit": "5",
        "recovery": "19",
        "block_adv": "-7",
        "hit_adv": "knd"
    },
    {
        "name": "air.d.mk",
        "desc": "Raigeki Shuu",
        "pic": "http://wiki.shoryuken.com/images/c/c6/%28yunjdk%29.gif",
        "damage": "70",
        "startup": "6/6/8",
        "hit": "land",
        "recovery": "N/A",
        "block_adv": "-3~+10",
        "hit_adv": "-3~+10"
    },
    {
        "name": "qcf.lp",
        "desc": "Zesshou Hohou (Jab)",
        "pic": "http://wiki.shoryuken.com/images/d/d9/%28yunlunge%29.gif",
        "damage": "100",
        "startup": "7",
        "hit": "5",
        "recovery": "22",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.mp",
        "desc": "Zesshou Hohou (Strong)",
        "pic": "http://wiki.shoryuken.com/images/d/d9/%28yunlunge%29.gif",
        "damage": "110",
        "startup": "10",
        "hit": "11",
        "recovery": "16",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.hp",
        "desc": "Zesshou Hohou (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/d/d9/%28yunlunge%29.gif",
        "damage": "120",
        "startup": "13",
        "hit": "15",
        "recovery": "12",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.2p",
        "desc": "Zesshou Hohou (EX)",
        "pic": "http://wiki.shoryuken.com/images/2/22/%28yunlungeex%29.gif",
        "damage": "160",
        "startup": "13-22",
        "hit": "19-6",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lp",
        "desc": "Tetsu Zankou (Jab)",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28yunshoulder%29.gif",
        "damage": "100",
        "startup": "7",
        "hit": "6",
        "recovery": "13",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "dp.mp",
        "desc": "Tetsu Zankou (Strong)",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28yunshoulder%29.gif",
        "damage": "125",
        "startup": "8",
        "hit": "6",
        "recovery": "15",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Tetsu Zankou (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28yunshoulder%29.gif",
        "damage": "140",
        "startup": "10",
        "hit": "6",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2p",
        "desc": "Tetsu Zankou (EX)",
        "pic": "http://wiki.shoryuken.com/images/5/51/%28yunshoulderex%29.gif",
        "damage": "160",
        "startup": "10-17",
        "hit": "7-6",
        "recovery": "19",
        "block_adv": "-7",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lk",
        "desc": "Nishou Kyaku (Short)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28yunkicks%29.gif",
        "damage": "130",
        "startup": "4-13",
        "hit": "2-4",
        "recovery": "25",
        "block_adv": "-25",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mk",
        "desc": "Nishou Kyaku (Forward)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28yunkicks%29.gif",
        "damage": "140",
        "startup": "6-15",
        "hit": "2-4",
        "recovery": "26",
        "block_adv": "-26",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hk",
        "desc": "Nishou Kyaku (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28yunkicks%29.gif",
        "damage": "150",
        "startup": "8-17",
        "hit": "2-4",
        "recovery": "28",
        "block_adv": "-28",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2k",
        "desc": "Nishou Kyaku (EX)",
        "pic": "http://wiki.shoryuken.com/images/2/23/%28yunkicksex%29.gif",
        "damage": "170",
        "startup": "4-12",
        "hit": "2-4",
        "recovery": "29",
        "block_adv": "-28",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lp",
        "desc": "Kobukushi",
        "pic": "http://wiki.shoryuken.com/images/4/44/%28yunpalm%29.gif",
        "damage": "180",
        "startup": "24",
        "hit": "10",
        "recovery": "4",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.lk",
        "desc": "Zenpou-Tenshin",
        "pic": "http://wiki.shoryuken.com/images/6/61/%28yuncg%29.gif",
        "damage": "N/A",
        "startup": "5",
        "hit": "2",
        "recovery": "26",
        "block_adv": "N/A",
        "hit_adv": "+16"
    },
    {
        "name": "sa1",
        "desc": "You Hou",
        "pic": "http://wiki.shoryuken.com/images/7/78/%28yunsa1%29.gif",
        "damage": "410",
        "startup": "1+10+45",
        "hit": "9+2+2",
        "recovery": "36",
        "block_adv": "-27",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Sourai Rengeki",
        "pic": "http://wiki.shoryuken.com/images/0/08/%28yunsa2%29.gif",
        "damage": "320",
        "startup": "4+20+34+47+66+78",
        "hit": "3+2+3+3+4+2",
        "recovery": "33",
        "block_adv": "-27",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Genei Jin",
        "pic": "http://wiki.shoryuken.com/images/f/f3/%28yunsa3%29.gif",
        "damage": "N/A",
        "startup": "10",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    }
]

chun_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/b/bc/%28chunlit1%29.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "59",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/a/a9/%28chunlilp%29.gif",
        "damage": "15",
        "startup": "3",
        "hit": "5",
        "recovery": "4",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/3/3d/%28chunlimp%29.gif",
        "damage": "100",
        "startup": "6",
        "hit": "8",
        "recovery": "9",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/8/8b/%28chunlihp%29.gif",
        "damage": "110",
        "startup": "8",
        "hit": "6",
        "recovery": "17",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "http://wiki.shoryuken.com/images/c/cc/%28chunlicloselp%29.gif",
        "damage": "30",
        "startup": "2",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/6/61/%28chunlilk%29.gif",
        "damage": "40",
        "startup": "3",
        "hit": "5",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "http://wiki.shoryuken.com/images/8/8a/%28chunlimk%29.gif",
        "damage": "90",
        "startup": "7",
        "hit": "6",
        "recovery": "19",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/c/cd/%28chunlihk%29.gif",
        "damage": "120",
        "startup": "12",
        "hit": "1",
        "recovery": "15",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "http://wiki.shoryuken.com/images/d/d2/%28chunliclosemk%29.gif",
        "damage": "80",
        "startup": "6",
        "hit": "2",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "close.hk",
        "desc": "Close Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28chunliclosehk%29.gif",
        "damage": "120",
        "startup": "4",
        "hit": "9",
        "recovery": "12",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/a/a3/%28chunlijlp%29.gif",
        "damage": "40",
        "startup": "2(4 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/c/c1/%28chunlijmp%29.gif",
        "damage": "60(80 neutral jump)",
        "startup": "4(6 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-6~+10",
        "hit_adv": "-6~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/4/40/%28chunlijhp%29.gif",
        "damage": "80(130 neutral jump)",
        "startup": "9(10 neutral jump)",
        "hit": "6(3 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-1~+13(+4~+13 neutral jump)",
        "hit_adv": "-1~+13(+4~+13 neutral jump)"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/1/1f/%28chunlijlk%29.gif",
        "damage": "50(40 neutral jump)",
        "startup": "5",
        "hit": "until land(22 neutral jump)",
        "recovery": "N/A",
        "block_adv": "0~+7",
        "hit_adv": "0~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/a/a2/%28chunlijmk%29.gif",
        "damage": "90(80 neutral jump)",
        "startup": "6",
        "hit": "13(2 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+2~+10(-1~+10 neutral jump)",
        "hit_adv": "+2~+10(-1~+10 neutral jump)"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/6/64/%28chunlijhk%29.gif",
        "damage": "110(130 neutral jump)",
        "startup": "10(8 neutral jump)",
        "hit": "3(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+1~+13",
        "hit_adv": "+1~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/4/47/%28chunlioh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hiza Geri",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28chunlitr%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.lp+lk",
        "desc": "Seoi Nage",
        "pic": "http://wiki.shoryuken.com/images/a/ac/%28chunliatr%29.gif",
        "damage": "80",
        "startup": "5",
        "hit": "1",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/5/5f/%28chunliclp%29.gif",
        "damage": "15",
        "startup": "2",
        "hit": "4",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/f/ff/%28chunlicmp%29.gif",
        "damage": "90",
        "startup": "8",
        "hit": "2",
        "recovery": "18",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/3/3f/%28chunlichp%29.gif",
        "damage": "130",
        "startup": "8",
        "hit": "2",
        "recovery": "22",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/c/c7/%28chunliclk%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/f/f8/%28chunlicmk%29.gif",
        "damage": "90",
        "startup": "6",
        "hit": "2",
        "recovery": "14",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/c/cb/%28chunlichk%29.gif",
        "damage": "110",
        "startup": "7",
        "hit": "3",
        "recovery": "21",
        "block_adv": "-7",
        "hit_adv": "knd"
    },
    {
        "name": "b.mp",
        "desc": "Souren Shou",
        "pic": "http://wiki.shoryuken.com/images/8/81/%28chunlibmp%29.gif",
        "damage": "110",
        "startup": "5",
        "hit": "2,1",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "b.hp",
        "desc": "Hakkei",
        "pic": "http://wiki.shoryuken.com/images/1/10/%28chunlibhp%29.gif",
        "damage": "130",
        "startup": "7",
        "hit": "9",
        "recovery": "10",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "f.mk",
        "desc": "Senjou Shuu",
        "pic": "http://wiki.shoryuken.com/images/7/7a/%28chunlifmk%29.gif",
        "damage": "80",
        "startup": "11",
        "hit": "7",
        "recovery": "11",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "hold.mk",
        "desc": "Kakushu Raku Kyaku",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28chunlimkmk%29.gif",
        "damage": "120",
        "startup": "6",
        "hit": "6",
        "recovery": "2",
        "block_adv": "-1",
        "hit_adv": "+3"
    },
    {
        "name": "f.hk",
        "desc": "Yoku Sen Kyaku",
        "pic": "http://wiki.shoryuken.com/images/0/0e/%28chunlifhk%29.gif",
        "damage": "120",
        "startup": "12",
        "hit": "1",
        "recovery": "15",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "df.hk",
        "desc": "Tenshin Shuu Kyaku",
        "pic": "http://wiki.shoryuken.com/images/9/9e/%28chunlidfhk%29.gif",
        "damage": "110",
        "startup": "37",
        "hit": "5",
        "recovery": "2",
        "block_adv": "+9",
        "hit_adv": "+11"
    },
    {
        "name": "air.d.mk",
        "desc": "Yosou Kyaku",
        "pic": "http://wiki.shoryuken.com/images/3/36/%28chunlijdmk%29.gif",
        "damage": "50",
        "startup": "9",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "hcf.lp",
        "desc": "Kikkoken (Jab)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28chunlikikoken%29.gif",
        "damage": "45",
        "startup": "13",
        "hit": "1",
        "recovery": "45",
        "block_adv": "-17",
        "hit_adv": "-16"
    },
    {
        "name": "hcf.mp",
        "desc": "Kikkoken (Strong)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28chunlikikoken%29.gif",
        "damage": "50",
        "startup": "12",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-10",
        "hit_adv": "-0"
    },
    {
        "name": "hcf.mp",
        "desc": "Kikkoken (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28chunlikikoken%29.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "32",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "hcf.2p",
        "desc": "Kikkoken (EX)",
        "pic": "http://wiki.shoryuken.com/images/0/03/%28chunlikikokenex%29.gif",
        "damage": "80",
        "startup": "14",
        "hit": "1",
        "recovery": "41",
        "block_adv": "-7",
        "hit_adv": "-6"
    },
    {
        "name": "rapid.lk",
        "desc": "Hyakuretsu Kyaku (Short)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28chunlihkk%29.gif",
        "damage": "150",
        "startup": "6+10+13+17",
        "hit": "2+1+2+2",
        "recovery": "12",
        "block_adv": "+3",
        "hit_adv": "+5"
    },
    {
        "name": "rapid.mk",
        "desc": "Hyakuretsu Kyaku (Forward)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28chunlihkk%29.gif",
        "damage": "160",
        "startup": "6+9+12+15",
        "hit": "1+1+1+1",
        "recovery": "13",
        "block_adv": "+1",
        "hit_adv": "+3"
    },
    {
        "name": "rapid.mk",
        "desc": "Hyakuretsu Kyaku (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28chunlihkk%29.gif",
        "damage": "165",
        "startup": "5+7+9+11+13+15+17+19",
        "hit": "1+1+1+1+1+1+1+1",
        "recovery": "15",
        "block_adv": "+1",
        "hit_adv": "-1"
    },
    {
        "name": "rapid.2k",
        "desc": "Hyakuretsu Kyaku (EX)",
        "pic": "http://wiki.shoryuken.com/images/0/0e/%28chunlihrkex%29.gif",
        "damage": "210",
        "startup": "3+5+7+9",
        "hit": "1+1+1+1",
        "recovery": "17",
        "block_adv": "-36",
        "hit_adv": "knd"
    },
    {
        "name": "charge.lk",
        "desc": "Spinning Bird Kick (Short)",
        "pic": "http://wiki.shoryuken.com/images/6/6c/%28chunlisbk%29.gif",
        "damage": "140",
        "startup": "12+13+18+23",
        "hit": "1x4",
        "recovery": "21",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "charge.mk",
        "desc": "Spinning Bird Kick (Forward)",
        "pic": "http://wiki.shoryuken.com/images/6/6c/%28chunlisbk%29.gif",
        "damage": "175",
        "startup": "14+15+20+25+30+35",
        "hit": "1x6",
        "recovery": "22",
        "block_adv": "-4",
        "hit_adv": "-4"
    },
    {
        "name": "charge.hk",
        "desc": "Spinning Bird Kick (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/6/6c/%28chunlisbk%29.gif",
        "damage": "195",
        "startup": "17+18+23+28+33+38+43+48",
        "hit": "1x6",
        "recovery": "22",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "charge.2k",
        "desc": "Spinning Bird Kick (EX)",
        "pic": "http://wiki.shoryuken.com/images/6/6d/%28chunlisbkex%29.gif",
        "damage": "175",
        "startup": "12+17+22+27+32",
        "hit": "2x5",
        "recovery": "22",
        "block_adv": "-8",
        "hit_adv": "knd "
    },
    {
        "name": "hcb.lk",
        "desc": "Hazan Shu (Short)",
        "pic": "http://wiki.shoryuken.com/images/e/e4/%28chunlihzs%29.gif",
        "damage": "100",
        "startup": "22",
        "hit": "3",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "hcb.mk",
        "desc": "Hazan Shu (Forward)",
        "pic": "http://wiki.shoryuken.com/images/e/e4/%28chunlihzs%29.gif",
        "damage": "110",
        "startup": "24",
        "hit": "3",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "hcb.hk",
        "desc": "Hazan Shu (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/e/e4/%28chunlihzs%29.gif",
        "damage": "120",
        "startup": "29",
        "hit": "3",
        "recovery": "17",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "hcb.2k",
        "desc": "Hazan Shu (EX)",
        "pic": "http://wiki.shoryuken.com/images/7/75/%28chunlihzsex%29.gif",
        "damage": "160",
        "startup": "6",
        "hit": "1",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Kikoshou",
        "pic": "http://wiki.shoryuken.com/images/8/86/%28chunlisa1%29.gif",
        "damage": "360",
        "startup": "1-30",
        "hit": "1x20",
        "recovery": "48",
        "block_adv": "-38",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Houyoku Sen",
        "pic": "http://wiki.shoryuken.com/images/9/99/%28chunlisa2%29.gif",
        "damage": "390",
        "startup": "3-71",
        "hit": "1x16 + 3",
        "recovery": "35",
        "block_adv": "-25",
        "hit_adv": "launch"
    },
    {
        "name": "sa3",
        "desc": "Tensei Ranka",
        "pic": "http://wiki.shoryuken.com/images/e/ef/%28chunlisa3%29.gif",
        "damage": "280",
        "startup": "3-30",
        "hit": "3+1x5+3+4+1",
        "recovery": "46",
        "block_adv": "-30",
        "hit_adv": "knd"
    }
]

ken_frames=[{
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/8/8d/%28kent%29.gif",
        "damage": "5/5",
        "startup": "15/9",
        "hit": "1/1",
        "recovery": "27",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/5/5a/%28kenlp%29.gif",
        "damage": "20",
        "startup": "5",
        "hit": "3",
        "recovery": "4",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/f/f4/%28kenmp%29.gif",
        "damage": "90",
        "startup": "6",
        "hit": "3",
        "recovery": "10",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/e/e1/%28kenhp%29.gif",
        "damage": "130",
        "startup": "9",
        "hit": "3",
        "recovery": "15",
        "block_adv": "+2",
        "hit_adv": "+4"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "http://wiki.shoryuken.com/images/6/6c/%28kencloselp%29.gif",
        "damage": "20",
        "startup": "3",
        "hit": "3",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "http://wiki.shoryuken.com/images/3/3a/%28kenclosemp%29.gif",
        "damage": "100",
        "startup": "4",
        "hit": "4",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "http://wiki.shoryuken.com/images/b/b3/%28kenclosehp%29.gif",
        "damage": "130",
        "startup": "6",
        "hit": "3",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/2/22/%28kenlk%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "4",
        "recovery": "7",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "http://wiki.shoryuken.com/images/d/d1/%28kenmk%29.gif",
        "damage": "110",
        "startup": "8",
        "hit": "7",
        "recovery": "16",
        "block_adv": "-6",
        "hit_adv": "-2"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/1/15/%28kenhk%29.gif",
        "damage": "150",
        "startup": "11",
        "hit": "6",
        "recovery": "19",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/5/54/%28kenjlp%29.gif",
        "damage": "50",
        "startup": "4(5 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/6/6c/%28kenjmp%29.gif",
        "damage": "100",
        "startup": "5(6 neutral jump)",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/6/6c/%28kenjmp%29.gif",
        "damage": "130",
        "startup": "6(7 neutral jump)",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "+3~+13",
        "hit_adv": "+3~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/1/19/%28kenjlk%29.gif",
        "damage": "50",
        "startup": "4(5 neutral jump)",
        "hit": "10(19 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-8~+7",
        "hit_adv": "-8~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/f/ff/%28kenjmk%29.gif",
        "damage": "90",
        "startup": "5",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "-6~10",
        "hit_adv": "-6~10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/8/86/%28kenjhk%29.gif",
        "damage": "125(130 neutral jump)",
        "startup": "6(7 neutral jump)",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/e/ec/%28kenoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "8",
        "recovery": "7",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hiza Geri",
        "pic": "http://wiki.shoryuken.com/images/8/85/%28kenhg%29.gif",
        "damage": "160",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Seoi Nage",
        "pic": "http://wiki.shoryuken.com/images/0/0b/%28kensn%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Jigoku Guruma",
        "pic": "http://wiki.shoryuken.com/images/7/70/%28kenjg%29.gif",
        "damage": "110",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/3/39/%28kenclp%29.gif",
        "damage": "20",
        "startup": "4",
        "hit": "3",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/a/ae/%28kencmp%29.gif",
        "damage": "90",
        "startup": "5",
        "hit": "4",
        "recovery": "7",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/4/40/%28kenchp%29.gif",
        "damage": "130",
        "startup": "7",
        "hit": "5",
        "recovery": "17",
        "block_adv": "-8",
        "hit_adv": "-6"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/3/32/%28kenclk%29.gif",
        "damage": "20",
        "startup": "5",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/8/80/%28kencmk%29.gif",
        "damage": "85",
        "startup": "6",
        "hit": "5",
        "recovery": "17",
        "block_adv": "-3",
        "hit_adv": "-3"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/5/53/%28kenchk%29.gif",
        "damage": "130",
        "startup": "5",
        "hit": "5",
        "recovery": "26",
        "block_adv": "-13",
        "hit_adv": "knd"
    },
    {
        "name": "f.mk",
        "desc": "Fumikomi Mae Geri",
        "pic": "http://wiki.shoryuken.com/images/2/24/%28kenfmk%29.gif",
        "damage": "80",
        "startup": "16",
        "hit": "4",
        "recovery": "15",
        "block_adv": "-4",
        "hit_adv": "-1"
    },
    {
        "name": "b.mk",
        "desc": "Inazuma Kakato Wari",
        "pic": "http://wiki.shoryuken.com/images/b/b3/%28kenbmk%29.gif",
        "damage": "130",
        "startup": "8",
        "hit": "2/2",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "f.hk",
        "desc": "Shiden Kakato Otoshi",
        "pic": "http://wiki.shoryuken.com/images/8/8f/%28kenfhk%29.gif",
        "damage": "120",
        "startup": "30",
        "hit": "5",
        "recovery": "14(18 on fake)",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "hold.mk",
        "desc": "Inazuma Kakato Wari",
        "pic": "http://wiki.shoryuken.com/images/2/25/%28kenhmk%29.gif",
        "damage": "110/130",
        "startup": "8/25",
        "hit": "7/2/2",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "qcf.lp",
        "desc": "Hadouken",
        "pic": "http://wiki.shoryuken.com/images/2/2a/%28kenhdk%29.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-11",
        "hit_adv": "-10"
    },
    {
        "name": "qcf.mp",
        "desc": "Hadouken",
        "pic": "http://wiki.shoryuken.com/images/2/2a/%28kenhdk%29.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-11",
        "hit_adv": "-10"
    },
    {
        "name": "qcf.hp",
        "desc": "Hadouken",
        "pic": "http://wiki.shoryuken.com/images/2/2a/%28kenhdk%29.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-11",
        "hit_adv": "-10"
    },
    {
        "name": "qcf.2p",
        "desc": "Hadouken (EX)",
        "pic": "http://wiki.shoryuken.com/images/a/ad/%28kenhdkex%29.gif",
        "damage": "60+60",
        "startup": "10",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-6",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lp",
        "desc": "Shoryuken (Jab)",
        "pic": "http://wiki.shoryuken.com/images/6/6a/%28kensrk%29.gif",
        "damage": "150",
        "startup": "2",
        "hit": "8",
        "recovery": "26",
        "block_adv": "-17",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mp",
        "desc": "Shoryuken (Strong)",
        "pic": "http://wiki.shoryuken.com/images/6/6a/%28kensrk%29.gif",
        "damage": "165",
        "startup": "3",
        "hit": "2/12",
        "recovery": "28",
        "block_adv": "-24",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Shoryuken (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/6/6a/%28kensrk%29.gif",
        "damage": "185",
        "startup": "1",
        "hit": "2/2/7",
        "recovery": "32",
        "block_adv": "-31",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2p",
        "desc": "Shoryuken (EX)",
        "pic": "http://wiki.shoryuken.com/images/1/1c/%28kensrkex%29.gif",
        "damage": "80+50+40+40",
        "startup": "1",
        "hit": "2/2/2/14",
        "recovery": "38",
        "block_adv": "-36",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lk",
        "desc": "Tatsumaki Senpuu Kyaku (Short)",
        "pic": "http://wiki.shoryuken.com/images/f/fb/%28kentsk%29.gif",
        "damage": "80+30",
        "startup": "6+16+22",
        "hit": "2+3+2",
        "recovery": "14",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "qcb.mk",
        "desc": "Tatsumaki Senpuu Kyaku (Forward)",
        "pic": "http://wiki.shoryuken.com/images/f/fb/%28kentsk%29.gif",
        "damage": "60+30(x3)",
        "startup": "6-37",
        "hit": "2x7",
        "recovery": "15",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "qcb.hk",
        "desc": "Tatsumaki Senpuu Kyaku (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/f/fb/%28kentsk%29.gif",
        "damage": "60+30(x4)",
        "startup": "6-48",
        "hit": "2x9",
        "recovery": "15",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "qcb.2k",
        "desc": "Tatsumaki Senpuu Kyaku (EX)",
        "pic": "http://wiki.shoryuken.com/images/7/72/%28kentskex%29.gif",
        "damage": "200",
        "startup": "4-48",
        "hit": "2x11",
        "recovery": "13",
        "block_adv": "-3",
        "hit_adv": "-1 "
    },
   {
        "name": "air.qcb.lk",
        "desc": "Air Tatsumaki Senpuu Kyaku (Short)",
        "pic": "http://wiki.shoryuken.com/images/5/54/%28kenatsk%29.gif",
        "damage": "160",
        "startup": "7-18",
        "hit": "1x4",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.mk",
        "desc": "Air Tatsumaki Senpuu Kyaku (Forward)",
        "pic": "http://wiki.shoryuken.com/images/5/54/%28kenatsk%29.gif",
        "damage": "160",
        "startup": "7-26",
        "hit": "1x6",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.hk",
        "desc": "Air Tatsumaki Senpuu Kyaku (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/5/54/%28kenatsk%29.gif",
        "damage": "160",
        "startup": "7-34",
        "hit": "1x8",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.2k",
        "desc": "Air Tatsumaki Senpuu Kyaku (EX)",
        "pic": "http://wiki.shoryuken.com/images/a/a2/%28kenatskex%29.gif",
        "damage": "240",
        "startup": "6-42",
        "hit": "1x13",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Shoryureppa",
        "pic": "http://wiki.shoryuken.com/images/9/96/%28kensa1%29.gif",
        "damage": "400",
        "startup": "1",
        "hit": "1",
        "recovery": "11",
        "block_adv": "-38",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Shinryuken",
        "pic": "http://wiki.shoryuken.com/images/5/54/%28kensa2%29.gif",
        "damage": "495",
        "startup": "2",
        "hit": "2",
        "recovery": "61",
        "block_adv": "-80",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Shippu Jinrai Kyaku",
        "pic": "http://wiki.shoryuken.com/images/d/d5/%28kensa3%29.gif",
        "damage": "290",
        "startup": "2",
        "hit": "2",
        "recovery": "27",
        "block_adv": "-11",
        "hit_adv": "knd"
    }]

makoto_frames=[{
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/1/13/%28makotot%29.gif",
        "damage": "10",
        "startup": "79",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/3/3a/%28makotolp%29.gif",
        "damage": "30",
        "startup": "4",
        "hit": "6",
        "recovery": "6",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/7/7a/%28makotomp%29.gif",
        "damage": "80",
        "startup": "8",
        "hit": "11",
        "recovery": "4",
        "block_adv": "+6",
        "hit_adv": "+7"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/6/6a/%28makotohp%29.gif",
        "damage": "120",
        "startup": "8",
        "hit": "2",
        "recovery": "22",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/8/8b/%28makotolk%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "5",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "-2"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "http://wiki.shoryuken.com/images/6/6c/%28makotomk%29.gif",
        "damage": "90",
        "startup": "7",
        "hit": "5",
        "recovery": "13",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/8/86/%28makotohk%29.gif",
        "damage": "130",
        "startup": "11",
        "hit": "9",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/8/8d/%28makotojlp%29.gif",
        "damage": "50",
        "startup": "4(9 neutral jump)",
        "hit": "21(17 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-9~+7(-2~+7 neutral jump)",
        "hit_adv": "-9~+7(-2~+7 neutral jump)"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/e/e8/%28makotojmp%29.gif",
        "damage": "80",
        "startup": "11",
        "hit": "24(6 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-3~+10(+2~+10 neutral jump)",
        "hit_adv": "-3~+10(+2~+10 neutral jump)"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/6/63/%28makotojhp%29.gif",
        "damage": "130",
        "startup": "10(13 neutral jump)",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "+1~+13(+7~+13 neutral jump)",
        "hit_adv": "+1~+13(+7~+13 neutral jump)"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/f/f7/%28makotojlk%29.gif",
        "damage": "60",
        "startup": "2",
        "hit": "14",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/6/66/%28makotojmk%29.gif",
        "damage": "90",
        "startup": "7",
        "hit": "13",
        "recovery": "N/A",
        "block_adv": "-5~+10",
        "hit_adv": "-5~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/5/5b/%28makotojhk%29.gif",
        "damage": "130",
        "startup": "6",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "+4~+13",
        "hit_adv": "+4~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/c/c2/%28makotooh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hikiyose Zutsuki (Tacchuu)",
        "pic": "http://wiki.shoryuken.com/images/3/35/%28makotothr%29.gif",
        "damage": "90",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Hiji Otoshi Sanren Tsuki (Araiso)",
        "pic": "http://wiki.shoryuken.com/images/7/78/%28makotobftr%29.gif",
        "damage": "150",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Hiji Otoshi Sanren Tsuki (Araiso)",
        "pic": "http://wiki.shoryuken.com/images/7/78/%28makotobftr%29.gif",
        "damage": "150",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/f/fe/%28makotoclp%29.gif",
        "damage": "20",
        "startup": "5",
        "hit": "4",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/d/de/%28makotocmp%29.gif",
        "damage": "70",
        "startup": "7",
        "hit": "7",
        "recovery": "11",
        "block_adv": "-1",
        "hit_adv": "0"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/7/74/%28makotochp%29.gif",
        "damage": "130",
        "startup": "10",
        "hit": "2",
        "recovery": "21",
        "block_adv": "-8",
        "hit_adv": "knd"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/6/61/%28makotoclk%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "6",
        "recovery": "10",
        "block_adv": "-3",
        "hit_adv": "-3"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/9/9a/%28makotocmk%29.gif",
        "damage": "90",
        "startup": "7",
        "hit": "8",
        "recovery": "7",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/a/a1/%28makotochk%29.gif",
        "damage": "130",
        "startup": "10",
        "hit": "4",
        "recovery": "12",
        "block_adv": "+2",
        "hit_adv": "+4"
    },
    {
        "name": "f.lp",
        "desc": "Kazami",
        "pic": "http://wiki.shoryuken.com/images/4/49/%28makotoflp%29.gif",
        "damage": "25",
        "startup": "4",
        "hit": "4",
        "recovery": "8",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "f.mp",
        "desc": "Kaoruna",
        "pic": "http://wiki.shoryuken.com/images/5/51/%28makotofmp%29.gif",
        "damage": "85",
        "startup": "9",
        "hit": "6",
        "recovery": "9",
        "block_adv": "+2",
        "hit_adv": "+3"
    },
    {
        "name": "f.hp",
        "desc": "Shikami",
        "pic": "http://wiki.shoryuken.com/images/7/7c/%28makotofhp%29.gif",
        "damage": "150",
        "startup": "16",
        "hit": "4,15",
        "recovery": "13",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "f.lk",
        "desc": "Shinbuki",
        "pic": "http://wiki.shoryuken.com/images/0/07/%28makotoflk%29.gif",
        "damage": "350",
        "startup": "6",
        "hit": "6",
        "recovery": "13",
        "block_adv": "-5",
        "hit_adv": "-5"
    },
    {
        "name": "f.mk",
        "desc": "Naruto",
        "pic": "http://wiki.shoryuken.com/images/b/b8/%28makotofmk%29.gif",
        "damage": "100",
        "startup": "17",
        "hit": "5",
        "recovery": "18",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "f.hk",
        "desc": "Kurushio",
        "pic": "http://wiki.shoryuken.com/images/d/d0/%28makotofhk%29.gif",
        "damage": "120",
        "startup": "22",
        "hit": "3",
        "recovery": "25",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.lp",
        "desc": "Hayate (Jab)",
        "pic": "http://wiki.shoryuken.com/images/1/10/%28makotohayate%29.gif",
        "damage": "100",
        "startup": "6",
        "hit": "6",
        "recovery": "12",
        "block_adv": "-12",
        "hit_adv": "+2"
    },
    {
        "name": "qcf.mp",
        "desc": "Hayate (Strong)",
        "pic": "http://wiki.shoryuken.com/images/1/10/%28makotohayate%29.gif",
        "damage": "100",
        "startup": "9",
        "hit": "6",
        "recovery": "12",
        "block_adv": "-12",
        "hit_adv": "+2"
    },
    {
        "name": "qcf.hp",
        "desc": "Hayate (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/1/10/%28makotohayate%29.gif",
        "damage": "100",
        "startup": "11",
        "hit": "6",
        "recovery": "12",
        "block_adv": "-12",
        "hit_adv": "+2"
    },
    {
        "name": "hold.qcf.lp",
        "desc": "Hayate (Levels 1-4)",
        "pic": "http://wiki.shoryuken.com/images/1/10/%28makotohayate%29.gif",
        "damage": "110,120,130,140",
        "startup": "7-26, 27-46,47-66,67-126",
        "hit": "6",
        "recovery": "11,10,10,8",
        "block_adv": "-9, -6, -2, +2",
        "hit_adv": "+2, +2, knd, knd"
    },
    {
        "name": "qcf.2p",
        "desc": "Hayate (EX)",
        "pic": "http://wiki.shoryuken.com/images/f/f2/%28makotohdkex%29.gif",
        "damage": "160",
        "startup": "17",
        "hit": "1",
        "recovery": "8/12",
        "block_adv": "+2",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lp",
        "desc": "Fukiage (Jab)",
        "pic": "http://wiki.shoryuken.com/images/2/2a/%28makotofkage%29.gif",
        "damage": "120",
        "startup": "7",
        "hit": "8",
        "recovery": "26",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mp",
        "desc": "Fukiage (Strong)",
        "pic": "http://wiki.shoryuken.com/images/2/2a/%28makotofkage%29.gif",
        "damage": "140",
        "startup": "10",
        "hit": "8",
        "recovery": "26",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Fukiage (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/2/2a/%28makotofkage%29.gif",
        "damage": "140",
        "startup": "10",
        "hit": "7",
        "recovery": "26",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2p",
        "desc": "Fukiage (EX)",
        "pic": "http://wiki.shoryuken.com/images/5/53/%28makotosrkex%29.gif",
        "damage": "140",
        "startup": "11",
        "hit": "8",
        "recovery": "17/26",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lp",
        "desc": "Oroshi (Jab)",
        "pic": "http://wiki.shoryuken.com/images/6/6e/%28makotooroshi%29.gif",
        "damage": "100",
        "startup": "19",
        "hit": "7",
        "recovery": "17",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "qcb.mp",
        "desc": "Oroshi (Strong)",
        "pic": "http://wiki.shoryuken.com/images/6/6e/%28makotooroshi%29.gif",
        "damage": "110",
        "startup": "23",
        "hit": "7",
        "recovery": "17",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "qcb.hp",
        "desc": "Oroshi (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/6/6e/%28makotooroshi%29.gif",
        "damage": "100",
        "startup": "28",
        "hit": "7",
        "recovery": "17",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2p",
        "desc": "Oroshi (EX)",
        "pic": "http://wiki.shoryuken.com/images/f/fa/%28makototskex%29.gif",
        "damage": "160",
        "startup": "13",
        "hit": "7",
        "recovery": "17",
        "block_adv": "+3~+9",
        "hit_adv": "knd"
    },
   {
        "name": "hcb.lk",
        "desc": "Karakusa (Short)",
        "pic": "http://wiki.shoryuken.com/images/c/c0/%28makotokarakusa%29.gif",
        "damage": "30",
        "startup": "7",
        "hit": "3",
        "recovery": "28",
        "block_adv": "N/A",
        "hit_adv": "+14"
    },
    {
        "name": "hcb.mk",
        "desc": "Karakusa (Forward)",
        "pic": "http://wiki.shoryuken.com/images/c/c0/%28makotokarakusa%29.gif",
        "damage": "30",
        "startup": "8",
        "hit": "4",
        "recovery": "29",
        "block_adv": "N/A",
        "hit_adv": "+14"
    },
    {
        "name": "hcb.hk",
        "desc": "Karakusa (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/c/c0/%28makotokarakusa%29.gif",
        "damage": "30",
        "startup": "9",
        "hit": "4",
        "recovery": "30",
        "block_adv": "N/A",
        "hit_adv": "+14"
    },
    {
        "name": "air.qcb.lk",
        "desc": "Tsurugi (Short)",
        "pic": "http://wiki.shoryuken.com/images/9/96/%28makotoatsur%29.gif",
        "damage": "140",
        "startup": "7",
        "hit": "1",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.mk",
        "desc": "Tsurugi (Forward)",
        "pic": "http://wiki.shoryuken.com/images/9/96/%28makotoatsur%29.gif",
        "damage": "150",
        "startup": "7",
        "hit": "1",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.hk",
        "desc": "Tsurugi (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/9/96/%28makotoatsur%29.gif",
        "damage": "160",
        "startup": "7",
        "hit": "1",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.2k",
        "desc": "Tsurugi (EX)",
        "pic": "http://wiki.shoryuken.com/images/6/64/%28makotoatskex%29.gif",
        "damage": "80+100",
        "startup": "15+17",
        "hit": "2+2",
        "recovery": "8",
        "block_adv": "+2~+9",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Seichu Sen Godanzuki",
        "pic": "http://wiki.shoryuken.com/images/5/50/%28makotosa1%29.gif",
        "damage": "500",
        "startup": "1",
        "hit": "3",
        "recovery": "133/65 far/71 parry",
        "block_adv": "-17",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Abare To Sadami Kudaki",
        "pic": "http://wiki.shoryuken.com/images/3/3c/%28makotosa2%29.gif",
        "damage": "360",
        "startup": "14~18",
        "hit": "5/6/9",
        "recovery": "6/25 far/32 parry",
        "block_adv": "-20",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Tanden Renki-Seme no Kata",
        "pic": "http://wiki.shoryuken.com/images/7/7e/%28makotosa3%29.gif",
        "damage": "N/A",
        "startup": "2",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    }]

dudley_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/5/57/%28dudleyt%29.gif",
        "damage": "5",
        "startup": "19",
        "hit": "1",
        "recovery": "33",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/3/36/%28dudleylp%29.gif",
        "damage": "15",
        "startup": "3",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/7/7a/%28dudleymp%29.gif",
        "damage": "60",
        "startup": "3",
        "hit": "2",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/c/c7/%28dudleyhp%29.gif",
        "damage": "140",
        "startup": "7",
        "hit": "3",
        "recovery": "17",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/9/92/%28dudleylk%29.gif",
        "damage": "35",
        "startup": "5",
        "hit": "2",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "http://wiki.shoryuken.com/images/5/50/%28dudleymk%29.gif",
        "damage": "80",
        "startup": "5",
        "hit": "3",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/9/94/%28dudleyhk%29.gif",
        "damage": "120",
        "startup": "5",
        "hit": "3",
        "recovery": "12",
        "block_adv": "+4",
        "hit_adv": "+6"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/1/18/%28dudleyjlp%29.gif",
        "damage": "40",
        "startup": "3",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "+1~+7",
        "hit_adv": "+1~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/2/2d/%28dudleyjmp%29.gif",
        "damage": "70",
        "startup": "4",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+3~+10",
        "hit_adv": "+3~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/d/d7/%28dudleyjhp%29.gif",
        "damage": "120",
        "startup": "7",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "0~+13",
        "hit_adv": "0~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/1/1a/%28dudleyjlk%29.gif",
        "damage": "40",
        "startup": "3",
        "hit": "17",
        "recovery": "N/A",
        "block_adv": "-2~+7",
        "hit_adv": "-2~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/0/02/%28dudleyjmk%29.gif",
        "damage": "60",
        "startup": "4",
        "hit": "13",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "0~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/f/fb/%28dudleyjhk%29.gif",
        "damage": "90",
        "startup": "11",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/b/b4/%28dudleyoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Liver Crusher",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28dudleylct%29.gif",
        "damage": "160",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Dynamite Throw",
        "pic": "http://wiki.shoryuken.com/images/3/30/%28dudleydttr%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Dynamite Throw",
        "pic": "http://wiki.shoryuken.com/images/3/30/%28dudleydttr%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/3/3a/%28dudleyclp%29.gif",
        "damage": "15",
        "startup": "3",
        "hit": "1",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/c/c2/%28dudleycmp%29.gif",
        "damage": "70",
        "startup": "4",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+2",
        "hit_adv": "+3"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/0/09/%28dudleychp%29.gif",
        "damage": "130",
        "startup": "7",
        "hit": "4",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/f/fd/%28dudleyclk%29.gif",
        "damage": "30",
        "startup": "4",
        "hit": "1",
        "recovery": "10",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/c/c4/%28dudleycmk%29.gif",
        "damage": "60",
        "startup": "9",
        "hit": "3",
        "recovery": "22",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/1/1f/%28dudleychk%29.gif",
        "damage": "130",
        "startup": "15",
        "hit": "3",
        "recovery": "21",
        "block_adv": "+1",
        "hit_adv": "knd"
    },
    {
        "name": "f.lp",
        "desc": "Slipping Jab",
        "pic": "http://wiki.shoryuken.com/images/6/6a/%28dudleyflp%29.gif",
        "damage": "25",
        "startup": "4",
        "hit": "2",
        "recovery": "8",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "f.mp",
        "desc": "Stomach Blow",
        "pic": "http://wiki.shoryuken.com/images/4/4b/%28dudleyfmp%29.gif",
        "damage": "80",
        "startup": "8",
        "hit": "5",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "0"
    },
    {
        "name": "f.hp",
        "desc": "Step Straight",
        "pic": "http://wiki.shoryuken.com/images/4/40/%28dudleyfhp%29.gif",
        "damage": "140",
        "startup": "15",
        "hit": "5",
        "recovery": "16",
        "block_adv": "+2",
        "hit_adv": "0"
    },
    {
        "name": "f.mk",
        "desc": "Lever Blow",
        "pic": "http://wiki.shoryuken.com/images/e/eb/%28dudleyfmk%29.gif",
        "damage": "100",
        "startup": "5",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+2",
        "hit_adv": "+3"
    },
    {
        "name": "f.hk",
        "desc": "Dart Shot",
        "pic": "http://wiki.shoryuken.com/images/7/70/%28dudleyfhk%29.gif",
        "damage": "110",
        "startup": "12",
        "hit": "4",
        "recovery": "16",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "dp.lp",
        "desc": "Jet Upper (Jab)",
        "pic": "http://wiki.shoryuken.com/images/1/10/%28makotohayate%29.gif",
        "damage": "140",
        "startup": "4",
        "hit": "8",
        "recovery": "29",
        "block_adv": "-23",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mp",
        "desc": "Jet Upper (Strong)",
        "pic": "http://wiki.shoryuken.com/images/1/10/%28makotohayate%29.gif",
        "damage": "160",
        "startup": "4",
        "hit": "16",
        "recovery": "28",
        "block_adv": "-30",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Jet Upper (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/1/10/%28makotohayate%29.gif",
        "damage": "180",
        "startup": "3/4",
        "hit": "1/20",
        "recovery": "32",
        "block_adv": "-38",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2p",
        "desc": "Jet Upper (EX)",
        "pic": "http://wiki.shoryuken.com/images/f/f3/%28dudleyjupex%29.gif",
        "damage": "220",
        "startup": "3/4",
        "hit": "1/20",
        "recovery": "34",
        "block_adv": "-37",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.lp",
        "desc": "Machine Gun Blow (Jab)",
        "pic": "http://wiki.shoryuken.com/images/6/69/%28dudleymgb%29.gif",
        "damage": "150",
        "startup": "8/10/18",
        "hit": "2/2/4",
        "recovery": "18",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "hcf.mp",
        "desc": "Machine Gun Blow (Strong)",
        "pic": "http://wiki.shoryuken.com/images/6/69/%28dudleymgb%29.gif",
        "damage": "165",
        "startup": "15/17/19/27",
        "hit": "2/2/1/4",
        "recovery": "24",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "hcf.hp",
        "desc": "Machine Gun Blow (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/6/69/%28dudleymgb%29.gif",
        "damage": "185",
        "startup": "15/17/19/27",
        "hit": "2/2/1/4",
        "recovery": "2/2/1/1/4/4",
        "block_adv": "-12",
        "hit_adv": "N/A"
    },
    {
        "name": "hcf.2p",
        "desc": "Machine Gun Blow (EX)",
        "pic": "http://wiki.shoryuken.com/images/8/87/%28dudleymgbex%29.gif",
        "damage": "190",
        "startup": "16-46",
        "hit": "2/2/2/2/1/4/4",
        "recovery": "24",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.lp",
        "desc": "Cross Counter (Jab)",
        "pic": "http://wiki.shoryuken.com/images/9/91/%28dudleycrco%29.gif",
        "damage": "80+move damage",
        "startup": "2",
        "hit": "68",
        "recovery": "19",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mp",
        "desc": "Cross Counter (Strong)",
        "pic": "http://wiki.shoryuken.com/images/9/91/%28dudleycrco%29.gif",
        "damage": "100+move damage",
        "startup": "2",
        "hit": "49",
        "recovery": "19",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.hp",
        "desc": "Cross Counter (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/9/91/%28dudleycrco%29.gif",
        "damage": "130+move damage",
        "startup": "4",
        "hit": "28",
        "recovery": "19",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.2p",
        "desc": "Cross Counter (EX)",
        "pic": "http://wiki.shoryuken.com/images/a/ab/%28dudleyccex%29.gif",
        "damage": "160+move damage",
        "startup": "4",
        "hit": "29",
        "recovery": "19",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
   {
        "name": "hcb.lk",
        "desc": "Short Swing Blow (Short)",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28dudleyssbex%29.gif",
        "damage": "200",
        "startup": "17",
        "hit": "3",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mk",
        "desc": "Short Swing Blow (Forward)",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28dudleyssbex%29.gif",
        "damage": "200",
        "startup": "20",
        "hit": "3",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mk",
        "desc": "Short Swing Blow (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28dudleyssbex%29.gif",
        "damage": "200",
        "startup": "23",
        "hit": "3",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.2k",
        "desc": "Short Swing Blow (EX)",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28dudleyssbex%29.gif",
        "damage": "200",
        "startup": "17/27/41",
        "hit": "2/4/4",
        "recovery": "15",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.k,lp",
        "desc": "Ducking Straight (Jab)",
        "pic": "http://wiki.shoryuken.com/images/e/ec/%28dudleyduckst%29.gif",
        "damage": "160",
        "startup": "20",
        "hit": "4",
        "recovery": "19",
        "block_adv": "-7",
        "hit_adv": "-1"
    },
    {
        "name": "hcf.k,mp",
        "desc": "Ducking Straight (Strong)",
        "pic": "http://wiki.shoryuken.com/images/e/ec/%28dudleyduckst%29.gif",
        "damage": "160",
        "startup": "20",
        "hit": "4",
        "recovery": "19",
        "block_adv": "-7",
        "hit_adv": "-1"
    },
    {
        "name": "hcf.k,hp",
        "desc": "Ducking Straight (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/e/ec/%28dudleyduckst%29.gif",
        "damage": "160",
        "startup": "20",
        "hit": "4",
        "recovery": "19",
        "block_adv": "-7",
        "hit_adv": "-1"
    },
    {
        "name": "hcf.k,lk",
        "desc": "Ducking Uppercut (Short)",
        "pic": "http://wiki.shoryuken.com/images/e/ee/%28dudleyduckup%29.gif",
        "damage": "180",
        "startup": "19/20",
        "hit": "1/3",
        "recovery": "25",
        "block_adv": "-12",
        "hit_adv": "-5"
    },
    {
        "name": "hcf.k,mk",
        "desc": "Ducking Uppercut (Forward)",
        "pic": "http://wiki.shoryuken.com/images/e/ee/%28dudleyduckup%29.gif",
        "damage": "180",
        "startup": "19/20",
        "hit": "1/3",
        "recovery": "25",
        "block_adv": "-12",
        "hit_adv": "-5"
    },
    {
        "name": "hcf.k,hk",
        "desc": "Ducking Uppercut (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/e/ee/%28dudleyduckup%29.gif",
        "damage": "180",
        "startup": "19/20",
        "hit": "1/3",
        "recovery": "25",
        "block_adv": "-12",
        "hit_adv": "-5"
    },
    {
        "name": "sa1",
        "desc": "Rocket Upper",
        "pic": "http://wiki.shoryuken.com/images/4/45/%28dudleysa1%29.gif",
        "damage": "375",
        "startup": "1-70",
        "hit": "3/5/3/8/3/2/3/3/3/3/1",
        "recovery": "31",
        "block_adv": "-31",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Rolling Thunder",
        "pic": "http://wiki.shoryuken.com/images/e/e0/%28dudleysa2%29.gif",
        "damage": "415",
        "startup": "2",
        "hit": "2",
        "recovery": "61",
        "block_adv": "-9",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Corkscrew Blow",
        "pic": "http://wiki.shoryuken.com/images/5/5c/%28dudleysa3%29.gif",
        "damage": "275",
        "startup": "1/3/5/7/9",
        "hit": "2x5",
        "recovery": "24",
        "block_adv": "-10",
        "hit_adv": "knd"
    }
]

yang_frames=[]

gouki_frames=[]

urien_frames=[]

ryu_frames=[]

oro_frames=[]

ibuki_frames=[]

elena_frames=[]

necro_frames=[]

alex_frames=[]

remy_frames=[]

q_frames=[]

hugo_frames=[]

twelve_frames=[]

sean_frames=[]