yun_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/0/09/%28yunt%29.gif",
        "damage": "5",
        "startup": "28",
        "hit": "26",
        "recovery": "28",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/2/2c/%28yunlp%29.gif",
        "damage": "15",
        "startup": "4",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/1/12/%28yunmp%29.gif",
        "damage": "50",
        "startup": "5",
        "hit": "4",
        "recovery": "12",
        "block_adv": "-3",
        "hit_adv": "-2"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/9/9f/%28yunhp%29.gif",
        "damage": "130",
        "startup": "9",
        "hit": "2",
        "recovery": "23",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/0/0a/%28yuncloselp%29.gif",
        "damage": "15",
        "startup": "3",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/b/be/%28yunclosemp%29.gif",
        "damage": "60",
        "startup": "4",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+6",
        "hit_adv": "+7"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/8/84/%28yunclosehp%29.gif",
        "damage": "110",
        "startup": "6",
        "hit": "3",
        "recovery": "13",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "lk",
        "desc": "Short",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/8/8e/%28yunlk%29.gif",
        "damage": "35",
        "startup": "3",
        "hit": "3",
        "recovery": "6",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/d/d0/%28yunmk%29.gif",
        "damage": "80",
        "startup": "9",
        "hit": "3",
        "recovery": "15",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28yunhk%29.gif",
        "damage": "100",
        "startup": "14",
        "hit": "4",
        "recovery": "22",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/2/25/%28yunclosemk%29.gif",
        "damage": "30",
        "startup": "5",
        "hit": "9",
        "recovery": "1",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28yunjlp%29.gif",
        "damage": "40(60 neutral jump)",
        "startup": "2",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-4~+7",
        "hit_adv": "-4~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/8/88/%28yunjmp%29.gif",
        "damage": "80",
        "startup": "3",
        "hit": "6(7 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/1/14/%28yunjhp%29.gif",
        "damage": "100(120 neutral jump)",
        "startup": "5(8 neutral jump)",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-4~+10",
        "hit_adv": "-4~+10"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/b/b1/%28yunjlk%29.gif",
        "damage": "40",
        "startup": "3(4 neutral jump)",
        "hit": "12",
        "recovery": "N/A",
        "block_adv": "+1~+7",
        "hit_adv": "+1~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/5/5f/%28yunjmk%29.gif",
        "damage": "70",
        "startup": "6",
        "hit": "7",
        "recovery": "N/A",
        "block_adv": "-3~+10",
        "hit_adv": "-3~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28yunjhk%29.gif",
        "damage": "110",
        "startup": "5",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "-1~+10",
        "hit_adv": "-1~+10"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/4/44/%28yunoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "9",
        "recovery": "6",
        "block_adv": "-5~+2",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hiza Geri",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/3/3d/%28yunhg%29.gif",
        "damage": "160",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Monkey Flip",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/7/75/%28yunmfth%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/0/07/%28yunclp%29.gif",
        "damage": "20",
        "startup": "2",
        "hit": "2",
        "recovery": "1",
        "block_adv": "+13",
        "hit_adv": "+14"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/1/1c/%28yuncmp%29.gif",
        "damage": "40",
        "startup": "3",
        "hit": "2",
        "recovery": "1",
        "block_adv": "+12",
        "hit_adv": "+13"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/9/9e/%28yunchp%29.gif",
        "damage": "90",
        "startup": "3-10",
        "hit": "1-2",
        "recovery": "1",
        "block_adv": "+12",
        "hit_adv": "+13"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/7/7b/%28yunclk%29.gif",
        "damage": "20",
        "startup": "2",
        "hit": "2",
        "recovery": "1",
        "block_adv": "+13",
        "hit_adv": "+13"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/a/ac/%28yuncmk%29.gif",
        "damage": "30",
        "startup": "3",
        "hit": "2",
        "recovery": "4",
        "block_adv": "+7",
        "hit_adv": "+8"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/b/b5/%28yunchk%29.gif",
        "damage": "50",
        "startup": "8",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+5",
        "hit_adv": "knd"
    },
    {
        "name": "f.mk",
        "desc": "Senpuu Kyaku",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/f/f3/%28yunfmk%29.gif",
        "damage": "80",
        "startup": "19",
        "hit": "6",
        "recovery": "18",
        "block_adv": "-1",
        "hit_adv": "0"
    },
    {
        "name": "f.hp",
        "desc": "Dakai",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28yunfhp%29.gif",
        "damage": "140",
        "startup": "17",
        "hit": "5",
        "recovery": "19",
        "block_adv": "-7",
        "hit_adv": "knd"
    },
    {
        "name": "air.d.mk",
        "desc": "Raigeki Shuu",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/c/c6/%28yunjdk%29.gif",
        "damage": "70",
        "startup": "6/6/8",
        "hit": "land",
        "recovery": "N/A",
        "block_adv": "-3~+10",
        "hit_adv": "-3~+10"
    },
    {
        "name": "qcf.lp",
        "desc": "Zesshou Hohou (Jab)",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/d/d9/%28yunlunge%29.gif",
        "damage": "100",
        "startup": "7",
        "hit": "5",
        "recovery": "22",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.mp",
        "desc": "Zesshou Hohou (Strong)",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/d/d9/%28yunlunge%29.gif",
        "damage": "110",
        "startup": "10",
        "hit": "11",
        "recovery": "16",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.hp",
        "desc": "Zesshou Hohou (Fierce)",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/d/d9/%28yunlunge%29.gif",
        "damage": "120",
        "startup": "13",
        "hit": "15",
        "recovery": "12",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.2p",
        "desc": "Zesshou Hohou (EX)",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/2/22/%28yunlungeex%29.gif",
        "damage": "160",
        "startup": "13-22",
        "hit": "19-6",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lp",
        "desc": "Tetsu Zankou (Jab)",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28yunshoulder%29.gif",
        "damage": "100",
        "startup": "7",
        "hit": "6",
        "recovery": "13",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "dp.mp",
        "desc": "Tetsu Zankou (Strong)",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28yunshoulder%29.gif",
        "damage": "125",
        "startup": "8",
        "hit": "6",
        "recovery": "15",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Tetsu Zankou (Fierce)",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28yunshoulder%29.gif",
        "damage": "140",
        "startup": "10",
        "hit": "6",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2p",
        "desc": "Tetsu Zankou (EX)",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/5/51/%28yunshoulderex%29.gif",
        "damage": "160",
        "startup": "10-17",
        "hit": "7-6",
        "recovery": "19",
        "block_adv": "-7",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lk",
        "desc": "Nishou Kyaku (Short)",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28yunkicks%29.gif",
        "damage": "130",
        "startup": "4-13",
        "hit": "2-4",
        "recovery": "25",
        "block_adv": "-25",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mk",
        "desc": "Nishou Kyaku (Forward)",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28yunkicks%29.gif",
        "damage": "140",
        "startup": "6-15",
        "hit": "2-4",
        "recovery": "26",
        "block_adv": "-26",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hk",
        "desc": "Nishou Kyaku (Roundhouse)",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28yunkicks%29.gif",
        "damage": "150",
        "startup": "8-17",
        "hit": "2-4",
        "recovery": "28",
        "block_adv": "-28",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2k",
        "desc": "Nishou Kyaku (EX)",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/2/23/%28yunkicksex%29.gif",
        "damage": "170",
        "startup": "4-12",
        "hit": "2-4",
        "recovery": "29",
        "block_adv": "-28",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lp",
        "desc": "Kobukushi",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/4/44/%28yunpalm%29.gif",
        "damage": "180",
        "startup": "24",
        "hit": "10",
        "recovery": "4",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.lk",
        "desc": "Zenpou-Tenshin",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/6/61/%28yuncg%29.gif",
        "damage": "N/A",
        "startup": "5",
        "hit": "2",
        "recovery": "26",
        "block_adv": "N/A",
        "hit_adv": "+16"
    },
    {
        "name": "sa1",
        "desc": "You Hou",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/7/78/%28yunsa1%29.gif",
        "damage": "410",
        "startup": "1+10+45",
        "hit": "9+2+2",
        "recovery": "36",
        "block_adv": "-27",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Sourai Rengeki",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/0/08/%28yunsa2%29.gif",
        "damage": "320",
        "startup": "4+20+34+47+66+78",
        "hit": "3+2+3+3+4+2",
        "recovery": "33",
        "block_adv": "-27",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Genei Jin",
        "color": "0x0029f5",
        "pic": "http://wiki.shoryuken.com/images/f/f3/%28yunsa3%29.gif",
        "damage": "N/A",
        "startup": "10",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    }
]

chun_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlit1).gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "59",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlilp).gif",
        "damage": "15",
        "startup": "3",
        "hit": "5",
        "recovery": "4",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlimp).gif",
        "damage": "100",
        "startup": "6",
        "hit": "8",
        "recovery": "9",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlihp).gif",
        "damage": "110",
        "startup": "8",
        "hit": "6",
        "recovery": "17",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlicloselp).gif",
        "damage": "30",
        "startup": "2",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunliclosemp).gif",
        "damage": "60",
        "startup": "4",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+6",
        "hit_adv": "+7"
    },
    {
        "name": "lk",
        "desc": "Short",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlilk).gif",
        "damage": "40",
        "startup": "3",
        "hit": "5",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlimk).gif",
        "damage": "90",
        "startup": "7",
        "hit": "6",
        "recovery": "19",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlihk).gif",
        "damage": "120",
        "startup": "12",
        "hit": "1",
        "recovery": "15",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunliclosemk).gif",
        "damage": "80",
        "startup": "6",
        "hit": "2",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "close.hk",
        "desc": "Close Roundhouse",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlichlosehk).gif",
        "damage": "120",
        "startup": "4",
        "hit": "9",
        "recovery": "12",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlijlp).gif",
        "damage": "40",
        "startup": "2(4 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlijmp).gif",
        "damage": "60(80 neutral jump)",
        "startup": "4(6 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-6~+10",
        "hit_adv": "-6~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlijhp).gif",
        "damage": "80(130 neutral jump)",
        "startup": "9(10 neutral jump)",
        "hit": "6(3 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-1~+13(+4~+13 neutral jump)",
        "hit_adv": "-1~+13(+4~+13 neutral jump)"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlijlk).gif",
        "damage": "50(40 neutral jump)",
        "startup": "5",
        "hit": "until land(22 neutral jump)",
        "recovery": "N/A",
        "block_adv": "0~+7",
        "hit_adv": "0~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlijmk).gif",
        "damage": "90(80 neutral jump)",
        "startup": "6",
        "hit": "13(2 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+2~+10(-1~+10 neutral jump)",
        "hit_adv": "+2~+10(-1~+10 neutral jump)"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlijhk).gif",
        "damage": "110(130 neutral jump)",
        "startup": "10(8 neutral jump)",
        "hit": "3(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+1~+13",
        "hit_adv": "+1~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlioh).gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hiza Geri",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlitr).gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.lp+lk",
        "desc": "Seoi Nage",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunliatr).gif",
        "damage": "80",
        "startup": "5",
        "hit": "1",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunliclp).gif",
        "damage": "15",
        "startup": "2",
        "hit": "4",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlicmp).gif",
        "damage": "90",
        "startup": "8",
        "hit": "2",
        "recovery": "18",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlichp).gif",
        "damage": "130",
        "startup": "8",
        "hit": "2",
        "recovery": "22",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunliclk).gif",
        "damage": "40",
        "startup": "4",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlicmk).gif",
        "damage": "90",
        "startup": "6",
        "hit": "2",
        "recovery": "14",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlichk).gif",
        "damage": "110",
        "startup": "7",
        "hit": "3",
        "recovery": "21",
        "block_adv": "-7",
        "hit_adv": "knd"
    },
    {
        "name": "b.mp",
        "desc": "Souren Shou",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlibmp).gif",
        "damage": "110",
        "startup": "5",
        "hit": "2,1",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "b.hp",
        "desc": "Hakkei",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlibhp).gif",
        "damage": "130",
        "startup": "7",
        "hit": "9",
        "recovery": "10",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "f.mk",
        "desc": "Senjou Shuu",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlifmk).gif",
        "damage": "80",
        "startup": "11",
        "hit": "7",
        "recovery": "11",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "hold.mk",
        "desc": "Kakushu Raku Kyaku",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlimkmk).gif",
        "damage": "120",
        "startup": "6",
        "hit": "6",
        "recovery": "2",
        "block_adv": "-1",
        "hit_adv": "+3"
    },
    {
        "name": "f.hk",
        "desc": "Yoku Sen Kyaku",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlifhk).gif",
        "damage": "120",
        "startup": "12",
        "hit": "1",
        "recovery": "15",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "df.hk",
        "desc": "Tenshin Shuu Kyaku",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlidfhk).gif",
        "damage": "110",
        "startup": "37",
        "hit": "5",
        "recovery": "2",
        "block_adv": "+9",
        "hit_adv": "+11"
    },
    {
        "name": "air.d.mk",
        "desc": "Yosou Kyaku",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlijdmk).gif",
        "damage": "50",
        "startup": "9",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "hcf.lp",
        "desc": "Kikkoken (Jab)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlikikoken).gif",
        "damage": "45",
        "startup": "13",
        "hit": "1",
        "recovery": "45",
        "block_adv": "-17",
        "hit_adv": "-16"
    },
    {
        "name": "hcf.mp",
        "desc": "Kikkoken (Strong)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlikikoken).gif",
        "damage": "50",
        "startup": "12",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-10",
        "hit_adv": "-0"
    },
    {
        "name": "hcf.mp",
        "desc": "Kikkoken (Fierce)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlikikoken).gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "32",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "hcf.2p",
        "desc": "Kikkoken (EX)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlikikokenex).gif",
        "damage": "80",
        "startup": "14",
        "hit": "1",
        "recovery": "41",
        "block_adv": "-7",
        "hit_adv": "-6"
    },
    {
        "name": "rapid.lk",
        "desc": "Hyakuretsu Kyaku (Short)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlihkk).gif",
        "damage": "150",
        "startup": "6+10+13+17",
        "hit": "2+1+2+2",
        "recovery": "12",
        "block_adv": "+3",
        "hit_adv": "+5"
    },
    {
        "name": "rapid.mk",
        "desc": "Hyakuretsu Kyaku (Forward)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlihkk).gif",
        "damage": "160",
        "startup": "6+9+12+15",
        "hit": "1+1+1+1",
        "recovery": "13",
        "block_adv": "+1",
        "hit_adv": "+3"
    },
    {
        "name": "rapid.mk",
        "desc": "Hyakuretsu Kyaku (Roundhouse)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlihkk).gif",
        "damage": "165",
        "startup": "5+7+9+11+13+15+17+19",
        "hit": "1+1+1+1+1+1+1+1",
        "recovery": "15",
        "block_adv": "+1",
        "hit_adv": "-1"
    },
    {
        "name": "rapid.2k",
        "desc": "Hyakuretsu Kyaku (EX)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlihkkex).gif",
        "damage": "210",
        "startup": "3+5+7+9",
        "hit": "1+1+1+1",
        "recovery": "17",
        "block_adv": "-36",
        "hit_adv": "knd"
    },
    {
        "name": "charge.lk",
        "desc": "Spinning Bird Kick (Short)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlisbk).gif",
        "damage": "140",
        "startup": "12+13+18+23",
        "hit": "1x4",
        "recovery": "21",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "charge.mk",
        "desc": "Spinning Bird Kick (Forward)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlisbk).gif",
        "damage": "175",
        "startup": "14+15+20+25+30+35",
        "hit": "1x6",
        "recovery": "22",
        "block_adv": "-4",
        "hit_adv": "-4"
    },
    {
        "name": "charge.hk",
        "desc": "Spinning Bird Kick (Roundhouse)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlisbk).gif",
        "damage": "195",
        "startup": "17+18+23+28+33+38+43+48",
        "hit": "1x6",
        "recovery": "22",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "charge.2k",
        "desc": "Spinning Bird Kick (EX)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlisbkex).gif",
        "damage": "175",
        "startup": "12+17+22+27+32",
        "hit": "2x5",
        "recovery": "22",
        "block_adv": "-8",
        "hit_adv": "knd "
    },
    {
        "name": "hcb.lk",
        "desc": "Hazan Shu (Short)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlihzs).gif",
        "damage": "100",
        "startup": "22",
        "hit": "3",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "hcb.mk",
        "desc": "Hazan Shu (Forward)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlihzs).gif",
        "damage": "110",
        "startup": "24",
        "hit": "3",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "hcb.hk",
        "desc": "Hazan Shu (Roundhouse)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlihzs).gif",
        "damage": "120",
        "startup": "29",
        "hit": "3",
        "recovery": "17",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "hcb.2k",
        "desc": "Hazan Shu (EX)",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlihzsex).gif",
        "damage": "160",
        "startup": "6",
        "hit": "1",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Kikoshou",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlisa1).gif",
        "damage": "360",
        "startup": "1-30",
        "hit": "1x20",
        "recovery": "48",
        "block_adv": "-38",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Houyoku Sen",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlisa2).gif",
        "damage": "390",
        "startup": "3-71",
        "hit": "1x16 + 3",
        "recovery": "35",
        "block_adv": "-25",
        "hit_adv": "launch"
    },
    {
        "name": "sa3",
        "desc": "Tensei Ranka",
        "color": "0x0029f5",
        "pic": "./img/chun/(chunlisa3).gif",
        "damage": "280",
        "startup": "3-30",
        "hit": "3+1x5+3+4+1",
        "recovery": "46",
        "block_adv": "-30",
        "hit_adv": "knd"
    }
]

ken_frames=[]

makoto_frames=[]

dudley_frames=[]

yang_frames=[]

gouki_frames=[]

urien_frames=[]

ryu_frames=[]

oro_frames=[]

ibuki_frames=[]

elena_frames=[]

necro_frames=[]

alex_frames=[]

remy_frames=[]

q_frames=[]

hugo_frames=[]

twelve_frames=[]

sean_frames=[]