alex_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "5/5",
        "startup": "N/A",
        "hit": "64",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "framedata/img/al-lp.gif",
        "damage": "30",
        "startup": "4",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "framedata/img/al-mp.gif",
        "damage": "100",
        "startup": "4",
        "hit": "3",
        "recovery": "12",
        "block_adv": "-1",
        "hit_adv": "0"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "framedata/img/al-hp.gif",
        "damage": "145",
        "startup": "14",
        "hit": "4",
        "recovery": "16",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "framedata/img/al-closelp.gif",
        "damage": "30",
        "startup": "4",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "framedata/img/al-lk.gif",
        "damage": "40",
        "startup": "5",
        "hit": "3",
        "recovery": "10",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "framedata/img/al-mk.gif",
        "damage": "100",
        "startup": "11",
        "hit": "3",
        "recovery": "14",
        "block_adv": "-1",
        "hit_adv": "0"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "framedata/img/al-hk.gif",
        "damage": "150",
        "startup": "16",
        "hit": "5",
        "recovery": "29",
        "block_adv": "-13",
        "hit_adv": "0"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "framedata/img/al-closemk.gif",
        "damage": "105",
        "startup": "5",
        "hit": "3",
        "recovery": "12",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "framedata/img/al-alp.gif",
        "damage": "40",
        "startup": "4",
        "hit": "12",
        "recovery": "N/A",
        "block_adv": "-8~+7",
        "hit_adv": "-8~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "framedata/img/al-amp.gif",
        "damage": "80",
        "startup": "5",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "+2~+10",
        "hit_adv": "+2~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "framedata/img/al-ahp.gif",
        "damage": "140",
        "startup": "8",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "framedata/img/al-alk.gif",
        "damage": "60",
        "startup": "4",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-8~+7",
        "hit_adv": "-8~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "framedata/img/al-amk.gif",
        "damage": "90",
        "startup": "9",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "-3~+10",
        "hit_adv": "0~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "framedata/img/al-ahk.gif",
        "damage": "120",
        "startup": "8",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "framedata/img/al-overhead.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Body Slam",
        "pic": "framedata/img/al-throw.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Body Slam",
        "pic": "framedata/img/al-throw.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Body Slam",
        "pic": "framedata/img/al-throw.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "30",
        "startup": "4",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "90",
        "startup": "7",
        "hit": "2",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "80+60",
        "startup": "13",
        "hit": "2,3",
        "recovery": "7",
        "block_adv": "-9",
        "hit_adv": "knd"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "30",
        "startup": "5",
        "hit": "2",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "70",
        "startup": "8",
        "hit": "3",
        "recovery": "12",
        "block_adv": "-1",
        "hit_adv": "0"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "130",
        "startup": "11",
        "hit": "2",
        "recovery": "29",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "f.mp",
        "desc": "Chop",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "110",
        "startup": "7",
        "hit": "5",
        "recovery": "10",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "f.hp",
        "desc": "Lariat",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "135",
        "startup": "9",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "b.hp",
        "desc": "Headbutt/ Sleeper Hold (back turned)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "180/240",
        "startup": "8",
        "hit": "4",
        "recovery": "23",
        "block_adv": "-11",
        "hit_adv": "+1/+4"
    },
    {
        "name": "air.d.hp",
        "desc": "Flying Cross Chop",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "120",
        "startup": "10",
        "hit": "11",
        "recovery": "24",
        "block_adv": "-10",
        "hit_adv": "-1"
    },
    {
        "name": "qcf.lp",
        "desc": "Flash Chop (Jab)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "120",
        "startup": "11",
        "hit": "2",
        "recovery": "17",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "qcf.mp",
        "desc": "Flash Chop (Strong)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "130",
        "startup": "15",
        "hit": "3",
        "recovery": "19",
        "block_adv": "-1",
        "hit_adv": "+14"
    },
    {
        "name": "qcf.hp",
        "desc": "Flash Chop (Fierce)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "140",
        "startup": "19",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-1",
        "hit_adv": "+15"
    },
    {
        "name": "dp.lk",
        "desc": "Air Knee Smash (Short)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "120",
        "startup": "6",
        "hit": "6",
        "recovery": "35",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mk",
        "desc": "Air Knee Smash (Forward)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "135",
        "startup": "7",
        "hit": "10",
        "recovery": "34",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hk",
        "desc": "Air Knee Smash (Roundhouse)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "150",
        "startup": "8",
        "hit": "12",
        "recovery": "33",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.lp",
        "desc": "Powerbomb (Jab)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "160",
        "startup": "6",
        "hit": "1",
        "recovery": "35",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mp",
        "desc": "Powerbomb (Strong)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "180",
        "startup": "7",
        "hit": "1",
        "recovery": "41",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.hp",
        "desc": "Powerbomb (Fierce)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "200",
        "startup": "8",
        "hit": "1",
        "recovery": "44",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "chargef.lk",
        "desc": "Slash Elbow (Short)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "100",
        "startup": "15",
        "hit": "1",
        "recovery": "17",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "chargef.mk",
        "desc": "Slash Elbow (Forward)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "120",
        "startup": "18",
        "hit": "1",
        "recovery": "23",
        "block_adv": "-8",
        "hit_adv": "0"
    },
    {
        "name": "chargef.hk",
        "desc": "Slash Elbow (Roundhouse)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "140",
        "startup": "20",
        "hit": "1",
        "recovery": "23",
        "block_adv": "-8",
        "hit_adv": "-1"
    },
    {
        "name": "chargeu.lk",
        "desc": "Stomp (Short)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "120",
        "startup": "23",
        "hit": "2",
        "recovery": "19",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.mk",
        "desc": "Stomp (Forward)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "140",
        "startup": "25",
        "hit": "2",
        "recovery": "19",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.hk",
        "desc": "Stomp (Roundhouse)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "160",
        "startup": "26",
        "hit": "2",
        "recovery": "19",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.lk",
        "desc": "Spiral DDT (Short)",
        "pic": "img/al-hcbk.gif",
        "damage": "160",
        "startup": "20",
        "hit": "3",
        "recovery": "8",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mk",
        "desc": "Spiral DDT (Forward)",
        "pic": "img/al-hcbk.gif",
        "damage": "160",
        "startup": "22",
        "hit": "3",
        "recovery": "8",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.hk",
        "desc": "Spiral DDT (Roundhouse)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "160",
        "startup": "24",
        "hit": "3",
        "recovery": "8",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.2p",
        "desc": "Flash Chop (EX)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "100+100",
        "startup": "9/11",
        "hit": "2/2",
        "recovery": "15",
        "block_adv": "-1",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2k",
        "desc": "Air Knee Smash (EX)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "190",
        "startup": "3",
        "hit": "17",
        "recovery": "34",
        "block_adv": "-31",
        "hit_adv": "knd"
    },
    {
        "name": "chargef.2k",
        "desc": "Slash Elbow (EX)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "80+80",
        "startup": "9,20",
        "hit": "6,1",
        "recovery": "23",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "chargeu.2k",
        "desc": "Stomp (EX)",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "180",
        "startup": "26",
        "hit": "2",
        "recovery": "19",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Hyper Bomb",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "530(590 reverse)",
        "startup": "2",
        "hit": "2",
        "recovery": "33",
        "block_adv": "-38",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Boomerang Raid",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "350",
        "startup": "1-57",
        "hit": "3/3/3/3/2",
        "recovery": "41",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Stun Gun Headbutt",
        "pic": "framedata/img/al-taunt.gif",
        "damage": "180(max stun)",
        "startup": "25",
        "hit": "3",
        "recovery": "17",
        "block_adv": "N/A",
        "hit_adv": "knd"
    }
]