chun_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "framedata/img/ch-taunt.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "59",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "framedata/img/ch-lp.gif",
        "damage": "15",
        "startup": "3",
        "hit": "5",
        "recovery": "4",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "framedata/img/ch-mp.gif",
        "damage": "100",
        "startup": "6",
        "hit": "8",
        "recovery": "9",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "framedata/img/ch-hp.gif",
        "damage": "110",
        "startup": "8",
        "hit": "6",
        "recovery": "17",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "framedata/img/ch-closelp.gif",
        "damage": "30",
        "startup": "2",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "framedata/img/ch-lk.gif",
        "damage": "40",
        "startup": "3",
        "hit": "5",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "framedata/img/ch-mk.gif",
        "damage": "90",
        "startup": "7",
        "hit": "6",
        "recovery": "19",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "framedata/img/ch-hk.gif",
        "damage": "120",
        "startup": "12",
        "hit": "1",
        "recovery": "15",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "framedata/img/ch-closemk.gif",
        "damage": "80",
        "startup": "6",
        "hit": "2",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "close.hk",
        "desc": "Close Roundhouse",
        "pic": "framedata/img/ch-closehk.gif",
        "damage": "120",
        "startup": "4",
        "hit": "9",
        "recovery": "12",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "framedata/img/ch-alp.gif",
        "damage": "40",
        "startup": "2(4 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "framedata/img/ch-amp.gif",
        "damage": "60(80 neutral jump)",
        "startup": "4(6 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-6~+10",
        "hit_adv": "-6~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "framedata/img/ch-ahp.gif",
        "damage": "80(130 neutral jump)",
        "startup": "9(10 neutral jump)",
        "hit": "6(3 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-1~+13(+4~+13 neutral jump)",
        "hit_adv": "-1~+13(+4~+13 neutral jump)"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "framedata/img/ch-alk.gif",
        "damage": "50(40 neutral jump)",
        "startup": "5",
        "hit": "until land(22 neutral jump)",
        "recovery": "N/A",
        "block_adv": "0~+7",
        "hit_adv": "0~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "framedata/img/ch-amk.gif",
        "damage": "90(80 neutral jump)",
        "startup": "6",
        "hit": "13(2 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+2~+10(-1~+10 neutral jump)",
        "hit_adv": "+2~+10(-1~+10 neutral jump)"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "framedata/img/ch-ahk.gif",
        "damage": "110(130 neutral jump)",
        "startup": "10(8 neutral jump)",
        "hit": "3(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+1~+13",
        "hit_adv": "+1~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "framedata/img/ch-overhead.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hiza Geri",
        "pic": "framedata/img/ch-throw.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.lp+lk",
        "desc": "Seoi Nage",
        "pic": "framedata/img/ch-airthrow.gif",
        "damage": "80",
        "startup": "5",
        "hit": "1",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "framedata/img/ch-clp.gif",
        "damage": "15",
        "startup": "2",
        "hit": "4",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "framedata/img/ch-cmp.gif",
        "damage": "90",
        "startup": "8",
        "hit": "2",
        "recovery": "18",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "framedata/img/ch-chp.gif",
        "damage": "130",
        "startup": "8",
        "hit": "2",
        "recovery": "22",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "framedata/img/ch-clk.gif",
        "damage": "40",
        "startup": "4",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "framedata/img/ch-cmk.gif",
        "damage": "90",
        "startup": "6",
        "hit": "2",
        "recovery": "14",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "framedata/img/ch-chk.gif",
        "damage": "110",
        "startup": "7",
        "hit": "3",
        "recovery": "21",
        "block_adv": "-7",
        "hit_adv": "knd"
    },
    {
        "name": "b.mp",
        "desc": "Souren Shou",
        "pic": "framedata/img/ch-bmp.gif",
        "damage": "110",
        "startup": "5",
        "hit": "2,1",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "b.hp",
        "desc": "Hakkei",
        "pic": "framedata/img/ch-bhp.gif",
        "damage": "130",
        "startup": "7",
        "hit": "9",
        "recovery": "10",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "f.mk",
        "desc": "Senjou Shuu",
        "pic": "framedata/img/ch-fmk.gif",
        "damage": "80",
        "startup": "11",
        "hit": "7",
        "recovery": "11",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "hold.mk",
        "desc": "Kakushu Raku Kyaku",
        "pic": "framedata/img/ch-mkmk.gif",
        "damage": "120",
        "startup": "6",
        "hit": "6",
        "recovery": "2",
        "block_adv": "-1",
        "hit_adv": "+3"
    },
    {
        "name": "f.hk",
        "desc": "Yoku Sen Kyaku",
        "pic": "framedata/img/ch-fhk.gif",
        "damage": "120",
        "startup": "12",
        "hit": "1",
        "recovery": "15",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "df.hk",
        "desc": "Tenshin Shuu Kyaku",
        "pic": "framedata/img/ch-dfhk.gif",
        "damage": "110",
        "startup": "37",
        "hit": "5",
        "recovery": "2",
        "block_adv": "+9",
        "hit_adv": "+11"
    },
    {
        "name": "air.d.mk",
        "desc": "Yosou Kyaku",
        "pic": "framedata/img/ch-admk.gif",
        "damage": "50",
        "startup": "9",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "hcf.lp",
        "desc": "Kikkoken (Jab)",
        "pic": "framedata/img/ch-hcfp.gif",
        "damage": "45",
        "startup": "13",
        "hit": "1",
        "recovery": "45",
        "block_adv": "-17",
        "hit_adv": "-16"
    },
    {
        "name": "hcf.mp",
        "desc": "Kikkoken (Strong)",
        "pic": "framedata/img/ch-hcfp.gif",
        "damage": "50",
        "startup": "12",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-10",
        "hit_adv": "-0"
    },
    {
        "name": "hcf.mp",
        "desc": "Kikkoken (Fierce)",
        "pic": "framedata/img/ch-hcfp.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "32",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "hcf.2p",
        "desc": "Kikkoken (EX)",
        "pic": "framedata/img/ch-hcfp.gif",
        "damage": "80",
        "startup": "14",
        "hit": "1",
        "recovery": "41",
        "block_adv": "-7",
        "hit_adv": "-6"
    },
    {
        "name": "rapid.lk",
        "desc": "Hyakuretsu Kyaku (Short)",
        "pic": "framedata/img/ch-legs.gif",
        "damage": "150",
        "startup": "6+10+13+17",
        "hit": "2+1+2+2",
        "recovery": "12",
        "block_adv": "+3",
        "hit_adv": "+5"
    },
    {
        "name": "rapid.mk",
        "desc": "Hyakuretsu Kyaku (Forward)",
        "pic": "framedata/img/ch-legs.gif",
        "damage": "160",
        "startup": "6+9+12+15",
        "hit": "1+1+1+1",
        "recovery": "13",
        "block_adv": "+1",
        "hit_adv": "+3"
    },
    {
        "name": "rapid.hk",
        "desc": "Hyakuretsu Kyaku (Roundhouse)",
        "pic": "framedata/img/ch-legs.gif",
        "damage": "165",
        "startup": "5+7+9+11+13+15+17+19",
        "hit": "1+1+1+1+1+1+1+1",
        "recovery": "15",
        "block_adv": "+1",
        "hit_adv": "-1"
    },
    {
        "name": "rapid.2k",
        "desc": "Hyakuretsu Kyaku (EX)",
        "pic": "framedata/img/ch-legs.gif",
        "damage": "210",
        "startup": "3+5+7+9",
        "hit": "1+1+1+1",
        "recovery": "17",
        "block_adv": "-36",
        "hit_adv": "knd"
    },
    {
        "name": "charge.lk",
        "desc": "Spinning Bird Kick (Short)",
        "pic": "framedata/img/ch-sbk.gif",
        "damage": "140",
        "startup": "12+13+18+23",
        "hit": "1x4",
        "recovery": "21",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "charge.mk",
        "desc": "Spinning Bird Kick (Forward)",
        "pic": "framedata/img/ch-sbk.gif",
        "damage": "175",
        "startup": "14+15+20+25+30+35",
        "hit": "1x6",
        "recovery": "22",
        "block_adv": "-4",
        "hit_adv": "-4"
    },
    {
        "name": "charge.hk",
        "desc": "Spinning Bird Kick (Roundhouse)",
        "pic": "framedata/img/ch-sbk.gif",
        "damage": "195",
        "startup": "17+18+23+28+33+38+43+48",
        "hit": "1x6",
        "recovery": "22",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "charge.2k",
        "desc": "Spinning Bird Kick (EX)",
        "pic": "framedata/img/ch-sbk.gif",
        "damage": "175",
        "startup": "12+17+22+27+32",
        "hit": "2x5",
        "recovery": "22",
        "block_adv": "-8",
        "hit_adv": "knd "
    },
    {
        "name": "hcb.lk",
        "desc": "Hazan Shu (Short)",
        "pic": "framedata/img/ch-hcbk.gif",
        "damage": "100",
        "startup": "22",
        "hit": "3",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "hcb.mk",
        "desc": "Hazan Shu (Forward)",
        "pic": "framedata/img/ch-hcbk.gif",
        "damage": "110",
        "startup": "24",
        "hit": "3",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "hcb.hk",
        "desc": "Hazan Shu (Roundhouse)",
        "pic": "framedata/img/ch-hcbk.gif",
        "damage": "120",
        "startup": "29",
        "hit": "3",
        "recovery": "17",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "hcb.2k",
        "desc": "Hazan Shu (EX)",
        "pic": "framedata/img/ch-hcbk.gif",
        "damage": "160",
        "startup": "6",
        "hit": "1",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Kikoshou",
        "pic": "framedata/img/ch-sa1.gif",
        "damage": "360",
        "startup": "1-30",
        "hit": "1x20",
        "recovery": "48",
        "block_adv": "-38",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Houyoku Sen",
        "pic": "framedata/img/ch-sa2.gif",
        "damage": "390",
        "startup": "3-71",
        "hit": "1x16 + 3",
        "recovery": "35",
        "block_adv": "-25",
        "hit_adv": "launch"
    },
    {
        "name": "sa3",
        "desc": "Tensei Ranka",
        "pic": "framedata/img/ch-sa3.gif",
        "damage": "280",
        "startup": "3-30",
        "hit": "3+1x5+3+4+1",
        "recovery": "46",
        "block_adv": "-30",
        "hit_adv": "knd"
    }
]