chun_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/b/bc/%28chunlit1%29.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "59",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/a/a9/%28chunlilp%29.gif",
        "damage": "15",
        "startup": "3",
        "hit": "5",
        "recovery": "4",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/3/3d/%28chunlimp%29.gif",
        "damage": "100",
        "startup": "6",
        "hit": "8",
        "recovery": "9",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/8/8b/%28chunlihp%29.gif",
        "damage": "110",
        "startup": "8",
        "hit": "6",
        "recovery": "17",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "http://wiki.shoryuken.com/images/c/cc/%28chunlicloselp%29.gif",
        "damage": "30",
        "startup": "2",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/6/61/%28chunlilk%29.gif",
        "damage": "40",
        "startup": "3",
        "hit": "5",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "http://wiki.shoryuken.com/images/8/8a/%28chunlimk%29.gif",
        "damage": "90",
        "startup": "7",
        "hit": "6",
        "recovery": "19",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/c/cd/%28chunlihk%29.gif",
        "damage": "120",
        "startup": "12",
        "hit": "1",
        "recovery": "15",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "http://wiki.shoryuken.com/images/d/d2/%28chunliclosemk%29.gif",
        "damage": "80",
        "startup": "6",
        "hit": "2",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "close.hk",
        "desc": "Close Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28chunliclosehk%29.gif",
        "damage": "120",
        "startup": "4",
        "hit": "9",
        "recovery": "12",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/a/a3/%28chunlijlp%29.gif",
        "damage": "40",
        "startup": "2(4 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/c/c1/%28chunlijmp%29.gif",
        "damage": "60(80 neutral jump)",
        "startup": "4(6 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-6~+10",
        "hit_adv": "-6~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/4/40/%28chunlijhp%29.gif",
        "damage": "80(130 neutral jump)",
        "startup": "9(10 neutral jump)",
        "hit": "6(3 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-1~+13(+4~+13 neutral jump)",
        "hit_adv": "-1~+13(+4~+13 neutral jump)"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/1/1f/%28chunlijlk%29.gif",
        "damage": "50(40 neutral jump)",
        "startup": "5",
        "hit": "until land(22 neutral jump)",
        "recovery": "N/A",
        "block_adv": "0~+7",
        "hit_adv": "0~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/a/a2/%28chunlijmk%29.gif",
        "damage": "90(80 neutral jump)",
        "startup": "6",
        "hit": "13(2 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+2~+10(-1~+10 neutral jump)",
        "hit_adv": "+2~+10(-1~+10 neutral jump)"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/6/64/%28chunlijhk%29.gif",
        "damage": "110(130 neutral jump)",
        "startup": "10(8 neutral jump)",
        "hit": "3(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+1~+13",
        "hit_adv": "+1~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/4/47/%28chunlioh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hiza Geri",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28chunlitr%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.lp+lk",
        "desc": "Seoi Nage",
        "pic": "http://wiki.shoryuken.com/images/a/ac/%28chunliatr%29.gif",
        "damage": "80",
        "startup": "5",
        "hit": "1",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/5/5f/%28chunliclp%29.gif",
        "damage": "15",
        "startup": "2",
        "hit": "4",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/f/ff/%28chunlicmp%29.gif",
        "damage": "90",
        "startup": "8",
        "hit": "2",
        "recovery": "18",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/3/3f/%28chunlichp%29.gif",
        "damage": "130",
        "startup": "8",
        "hit": "2",
        "recovery": "22",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/c/c7/%28chunliclk%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/f/f8/%28chunlicmk%29.gif",
        "damage": "90",
        "startup": "6",
        "hit": "2",
        "recovery": "14",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/c/cb/%28chunlichk%29.gif",
        "damage": "110",
        "startup": "7",
        "hit": "3",
        "recovery": "21",
        "block_adv": "-7",
        "hit_adv": "knd"
    },
    {
        "name": "b.mp",
        "desc": "Souren Shou",
        "pic": "http://wiki.shoryuken.com/images/8/81/%28chunlibmp%29.gif",
        "damage": "110",
        "startup": "5",
        "hit": "2,1",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "b.hp",
        "desc": "Hakkei",
        "pic": "http://wiki.shoryuken.com/images/1/10/%28chunlibhp%29.gif",
        "damage": "130",
        "startup": "7",
        "hit": "9",
        "recovery": "10",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "f.mk",
        "desc": "Senjou Shuu",
        "pic": "http://wiki.shoryuken.com/images/7/7a/%28chunlifmk%29.gif",
        "damage": "80",
        "startup": "11",
        "hit": "7",
        "recovery": "11",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "hold.mk",
        "desc": "Kakushu Raku Kyaku",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28chunlimkmk%29.gif",
        "damage": "120",
        "startup": "6",
        "hit": "6",
        "recovery": "2",
        "block_adv": "-1",
        "hit_adv": "+3"
    },
    {
        "name": "f.hk",
        "desc": "Yoku Sen Kyaku",
        "pic": "http://wiki.shoryuken.com/images/0/0e/%28chunlifhk%29.gif",
        "damage": "120",
        "startup": "12",
        "hit": "1",
        "recovery": "15",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "df.hk",
        "desc": "Tenshin Shuu Kyaku",
        "pic": "http://wiki.shoryuken.com/images/9/9e/%28chunlidfhk%29.gif",
        "damage": "110",
        "startup": "37",
        "hit": "5",
        "recovery": "2",
        "block_adv": "+9",
        "hit_adv": "+11"
    },
    {
        "name": "air.d.mk",
        "desc": "Yosou Kyaku",
        "pic": "http://wiki.shoryuken.com/images/3/36/%28chunlijdmk%29.gif",
        "damage": "50",
        "startup": "9",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "hcf.lp",
        "desc": "Kikkoken (Jab)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28chunlikikoken%29.gif",
        "damage": "45",
        "startup": "13",
        "hit": "1",
        "recovery": "45",
        "block_adv": "-17",
        "hit_adv": "-16"
    },
    {
        "name": "hcf.mp",
        "desc": "Kikkoken (Strong)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28chunlikikoken%29.gif",
        "damage": "50",
        "startup": "12",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-10",
        "hit_adv": "-0"
    },
    {
        "name": "hcf.mp",
        "desc": "Kikkoken (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28chunlikikoken%29.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "32",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "hcf.2p",
        "desc": "Kikkoken (EX)",
        "pic": "http://wiki.shoryuken.com/images/0/03/%28chunlikikokenex%29.gif",
        "damage": "80",
        "startup": "14",
        "hit": "1",
        "recovery": "41",
        "block_adv": "-7",
        "hit_adv": "-6"
    },
    {
        "name": "rapid.lk",
        "desc": "Hyakuretsu Kyaku (Short)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28chunlihkk%29.gif",
        "damage": "150",
        "startup": "6+10+13+17",
        "hit": "2+1+2+2",
        "recovery": "12",
        "block_adv": "+3",
        "hit_adv": "+5"
    },
    {
        "name": "rapid.mk",
        "desc": "Hyakuretsu Kyaku (Forward)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28chunlihkk%29.gif",
        "damage": "160",
        "startup": "6+9+12+15",
        "hit": "1+1+1+1",
        "recovery": "13",
        "block_adv": "+1",
        "hit_adv": "+3"
    },
    {
        "name": "rapid.mk",
        "desc": "Hyakuretsu Kyaku (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28chunlihkk%29.gif",
        "damage": "165",
        "startup": "5+7+9+11+13+15+17+19",
        "hit": "1+1+1+1+1+1+1+1",
        "recovery": "15",
        "block_adv": "+1",
        "hit_adv": "-1"
    },
    {
        "name": "rapid.2k",
        "desc": "Hyakuretsu Kyaku (EX)",
        "pic": "http://wiki.shoryuken.com/images/0/0e/%28chunlihrkex%29.gif",
        "damage": "210",
        "startup": "3+5+7+9",
        "hit": "1+1+1+1",
        "recovery": "17",
        "block_adv": "-36",
        "hit_adv": "knd"
    },
    {
        "name": "charge.lk",
        "desc": "Spinning Bird Kick (Short)",
        "pic": "http://wiki.shoryuken.com/images/6/6c/%28chunlisbk%29.gif",
        "damage": "140",
        "startup": "12+13+18+23",
        "hit": "1x4",
        "recovery": "21",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "charge.mk",
        "desc": "Spinning Bird Kick (Forward)",
        "pic": "http://wiki.shoryuken.com/images/6/6c/%28chunlisbk%29.gif",
        "damage": "175",
        "startup": "14+15+20+25+30+35",
        "hit": "1x6",
        "recovery": "22",
        "block_adv": "-4",
        "hit_adv": "-4"
    },
    {
        "name": "charge.hk",
        "desc": "Spinning Bird Kick (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/6/6c/%28chunlisbk%29.gif",
        "damage": "195",
        "startup": "17+18+23+28+33+38+43+48",
        "hit": "1x6",
        "recovery": "22",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "charge.2k",
        "desc": "Spinning Bird Kick (EX)",
        "pic": "http://wiki.shoryuken.com/images/6/6d/%28chunlisbkex%29.gif",
        "damage": "175",
        "startup": "12+17+22+27+32",
        "hit": "2x5",
        "recovery": "22",
        "block_adv": "-8",
        "hit_adv": "knd "
    },
    {
        "name": "hcb.lk",
        "desc": "Hazan Shu (Short)",
        "pic": "http://wiki.shoryuken.com/images/e/e4/%28chunlihzs%29.gif",
        "damage": "100",
        "startup": "22",
        "hit": "3",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "hcb.mk",
        "desc": "Hazan Shu (Forward)",
        "pic": "http://wiki.shoryuken.com/images/e/e4/%28chunlihzs%29.gif",
        "damage": "110",
        "startup": "24",
        "hit": "3",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "hcb.hk",
        "desc": "Hazan Shu (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/e/e4/%28chunlihzs%29.gif",
        "damage": "120",
        "startup": "29",
        "hit": "3",
        "recovery": "17",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "hcb.2k",
        "desc": "Hazan Shu (EX)",
        "pic": "http://wiki.shoryuken.com/images/7/75/%28chunlihzsex%29.gif",
        "damage": "160",
        "startup": "6",
        "hit": "1",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Kikoshou",
        "pic": "http://wiki.shoryuken.com/images/8/86/%28chunlisa1%29.gif",
        "damage": "360",
        "startup": "1-30",
        "hit": "1x20",
        "recovery": "48",
        "block_adv": "-38",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Houyoku Sen",
        "pic": "http://wiki.shoryuken.com/images/9/99/%28chunlisa2%29.gif",
        "damage": "390",
        "startup": "3-71",
        "hit": "1x16 + 3",
        "recovery": "35",
        "block_adv": "-25",
        "hit_adv": "launch"
    },
    {
        "name": "sa3",
        "desc": "Tensei Ranka",
        "pic": "http://wiki.shoryuken.com/images/e/ef/%28chunlisa3%29.gif",
        "damage": "280",
        "startup": "3-30",
        "hit": "3+1x5+3+4+1",
        "recovery": "46",
        "block_adv": "-30",
        "hit_adv": "knd"
    }
]