dudley_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/5/57/%28dudleyt%29.gif",
        "damage": "5",
        "startup": "19",
        "hit": "1",
        "recovery": "33",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/3/36/%28dudleylp%29.gif",
        "damage": "15",
        "startup": "3",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/7/7a/%28dudleymp%29.gif",
        "damage": "60",
        "startup": "3",
        "hit": "2",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/c/c7/%28dudleyhp%29.gif",
        "damage": "140",
        "startup": "7",
        "hit": "3",
        "recovery": "17",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/9/92/%28dudleylk%29.gif",
        "damage": "35",
        "startup": "5",
        "hit": "2",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "http://wiki.shoryuken.com/images/5/50/%28dudleymk%29.gif",
        "damage": "80",
        "startup": "5",
        "hit": "3",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/9/94/%28dudleyhk%29.gif",
        "damage": "120",
        "startup": "5",
        "hit": "3",
        "recovery": "12",
        "block_adv": "+4",
        "hit_adv": "+6"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/1/18/%28dudleyjlp%29.gif",
        "damage": "40",
        "startup": "3",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "+1~+7",
        "hit_adv": "+1~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/2/2d/%28dudleyjmp%29.gif",
        "damage": "70",
        "startup": "4",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+3~+10",
        "hit_adv": "+3~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/d/d7/%28dudleyjhp%29.gif",
        "damage": "120",
        "startup": "7",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "0~+13",
        "hit_adv": "0~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/1/1a/%28dudleyjlk%29.gif",
        "damage": "40",
        "startup": "3",
        "hit": "17",
        "recovery": "N/A",
        "block_adv": "-2~+7",
        "hit_adv": "-2~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/0/02/%28dudleyjmk%29.gif",
        "damage": "60",
        "startup": "4",
        "hit": "13",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "0~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/f/fb/%28dudleyjhk%29.gif",
        "damage": "90",
        "startup": "11",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/b/b4/%28dudleyoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Liver Crusher",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28dudleylct%29.gif",
        "damage": "160",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Dynamite Throw",
        "pic": "http://wiki.shoryuken.com/images/3/30/%28dudleydttr%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Dynamite Throw",
        "pic": "http://wiki.shoryuken.com/images/3/30/%28dudleydttr%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/3/3a/%28dudleyclp%29.gif",
        "damage": "15",
        "startup": "3",
        "hit": "1",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/c/c2/%28dudleycmp%29.gif",
        "damage": "70",
        "startup": "4",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+2",
        "hit_adv": "+3"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/0/09/%28dudleychp%29.gif",
        "damage": "130",
        "startup": "7",
        "hit": "4",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/f/fd/%28dudleyclk%29.gif",
        "damage": "30",
        "startup": "4",
        "hit": "1",
        "recovery": "10",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/c/c4/%28dudleycmk%29.gif",
        "damage": "60",
        "startup": "9",
        "hit": "3",
        "recovery": "22",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/1/1f/%28dudleychk%29.gif",
        "damage": "130",
        "startup": "15",
        "hit": "3",
        "recovery": "21",
        "block_adv": "+1",
        "hit_adv": "knd"
    },
    {
        "name": "f.lp",
        "desc": "Slipping Jab",
        "pic": "http://wiki.shoryuken.com/images/6/6a/%28dudleyflp%29.gif",
        "damage": "25",
        "startup": "4",
        "hit": "2",
        "recovery": "8",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "f.mp",
        "desc": "Stomach Blow",
        "pic": "http://wiki.shoryuken.com/images/4/4b/%28dudleyfmp%29.gif",
        "damage": "80",
        "startup": "8",
        "hit": "5",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "0"
    },
    {
        "name": "f.hp",
        "desc": "Step Straight",
        "pic": "http://wiki.shoryuken.com/images/4/40/%28dudleyfhp%29.gif",
        "damage": "140",
        "startup": "15",
        "hit": "5",
        "recovery": "16",
        "block_adv": "+2",
        "hit_adv": "0"
    },
    {
        "name": "f.mk",
        "desc": "Lever Blow",
        "pic": "http://wiki.shoryuken.com/images/e/eb/%28dudleyfmk%29.gif",
        "damage": "100",
        "startup": "5",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+2",
        "hit_adv": "+3"
    },
    {
        "name": "f.hk",
        "desc": "Dart Shot",
        "pic": "http://wiki.shoryuken.com/images/7/70/%28dudleyfhk%29.gif",
        "damage": "110",
        "startup": "12",
        "hit": "4",
        "recovery": "16",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "dp.lp",
        "desc": "Jet Upper (Jab)",
        "pic": "http://wiki.shoryuken.com/images/1/10/%28makotohayate%29.gif",
        "damage": "140",
        "startup": "4",
        "hit": "8",
        "recovery": "29",
        "block_adv": "-23",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mp",
        "desc": "Jet Upper (Strong)",
        "pic": "http://wiki.shoryuken.com/images/1/10/%28makotohayate%29.gif",
        "damage": "160",
        "startup": "4",
        "hit": "16",
        "recovery": "28",
        "block_adv": "-30",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Jet Upper (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/1/10/%28makotohayate%29.gif",
        "damage": "180",
        "startup": "3/4",
        "hit": "1/20",
        "recovery": "32",
        "block_adv": "-38",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2p",
        "desc": "Jet Upper (EX)",
        "pic": "http://wiki.shoryuken.com/images/f/f3/%28dudleyjupex%29.gif",
        "damage": "220",
        "startup": "3/4",
        "hit": "1/20",
        "recovery": "34",
        "block_adv": "-37",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.lp",
        "desc": "Machine Gun Blow (Jab)",
        "pic": "http://wiki.shoryuken.com/images/6/69/%28dudleymgb%29.gif",
        "damage": "150",
        "startup": "8/10/18",
        "hit": "2/2/4",
        "recovery": "18",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "hcf.mp",
        "desc": "Machine Gun Blow (Strong)",
        "pic": "http://wiki.shoryuken.com/images/6/69/%28dudleymgb%29.gif",
        "damage": "165",
        "startup": "15/17/19/27",
        "hit": "2/2/1/4",
        "recovery": "24",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "hcf.hp",
        "desc": "Machine Gun Blow (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/6/69/%28dudleymgb%29.gif",
        "damage": "185",
        "startup": "15/17/19/27",
        "hit": "2/2/1/4",
        "recovery": "2/2/1/1/4/4",
        "block_adv": "-12",
        "hit_adv": "N/A"
    },
    {
        "name": "hcf.2p",
        "desc": "Machine Gun Blow (EX)",
        "pic": "http://wiki.shoryuken.com/images/8/87/%28dudleymgbex%29.gif",
        "damage": "190",
        "startup": "16-46",
        "hit": "2/2/2/2/1/4/4",
        "recovery": "24",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.lp",
        "desc": "Cross Counter (Jab)",
        "pic": "http://wiki.shoryuken.com/images/9/91/%28dudleycrco%29.gif",
        "damage": "80+move damage",
        "startup": "2",
        "hit": "68",
        "recovery": "19",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mp",
        "desc": "Cross Counter (Strong)",
        "pic": "http://wiki.shoryuken.com/images/9/91/%28dudleycrco%29.gif",
        "damage": "100+move damage",
        "startup": "2",
        "hit": "49",
        "recovery": "19",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.hp",
        "desc": "Cross Counter (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/9/91/%28dudleycrco%29.gif",
        "damage": "130+move damage",
        "startup": "4",
        "hit": "28",
        "recovery": "19",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.2p",
        "desc": "Cross Counter (EX)",
        "pic": "http://wiki.shoryuken.com/images/a/ab/%28dudleyccex%29.gif",
        "damage": "160+move damage",
        "startup": "4",
        "hit": "29",
        "recovery": "19",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
   {
        "name": "hcb.lk",
        "desc": "Short Swing Blow (Short)",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28dudleyssbex%29.gif",
        "damage": "200",
        "startup": "17",
        "hit": "3",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mk",
        "desc": "Short Swing Blow (Forward)",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28dudleyssbex%29.gif",
        "damage": "200",
        "startup": "20",
        "hit": "3",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mk",
        "desc": "Short Swing Blow (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28dudleyssbex%29.gif",
        "damage": "200",
        "startup": "23",
        "hit": "3",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.2k",
        "desc": "Short Swing Blow (EX)",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28dudleyssbex%29.gif",
        "damage": "200",
        "startup": "17/27/41",
        "hit": "2/4/4",
        "recovery": "15",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.k,lp",
        "desc": "Ducking Straight (Jab)",
        "pic": "http://wiki.shoryuken.com/images/e/ec/%28dudleyduckst%29.gif",
        "damage": "160",
        "startup": "20",
        "hit": "4",
        "recovery": "19",
        "block_adv": "-7",
        "hit_adv": "-1"
    },
    {
        "name": "hcf.k,mp",
        "desc": "Ducking Straight (Strong)",
        "pic": "http://wiki.shoryuken.com/images/e/ec/%28dudleyduckst%29.gif",
        "damage": "160",
        "startup": "20",
        "hit": "4",
        "recovery": "19",
        "block_adv": "-7",
        "hit_adv": "-1"
    },
    {
        "name": "hcf.k,hp",
        "desc": "Ducking Straight (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/e/ec/%28dudleyduckst%29.gif",
        "damage": "160",
        "startup": "20",
        "hit": "4",
        "recovery": "19",
        "block_adv": "-7",
        "hit_adv": "-1"
    },
    {
        "name": "hcf.k,lk",
        "desc": "Ducking Uppercut (Short)",
        "pic": "http://wiki.shoryuken.com/images/e/ee/%28dudleyduckup%29.gif",
        "damage": "180",
        "startup": "19/20",
        "hit": "1/3",
        "recovery": "25",
        "block_adv": "-12",
        "hit_adv": "-5"
    },
    {
        "name": "hcf.k,mk",
        "desc": "Ducking Uppercut (Forward)",
        "pic": "http://wiki.shoryuken.com/images/e/ee/%28dudleyduckup%29.gif",
        "damage": "180",
        "startup": "19/20",
        "hit": "1/3",
        "recovery": "25",
        "block_adv": "-12",
        "hit_adv": "-5"
    },
    {
        "name": "hcf.k,hk",
        "desc": "Ducking Uppercut (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/e/ee/%28dudleyduckup%29.gif",
        "damage": "180",
        "startup": "19/20",
        "hit": "1/3",
        "recovery": "25",
        "block_adv": "-12",
        "hit_adv": "-5"
    },
    {
        "name": "sa1",
        "desc": "Rocket Upper",
        "pic": "http://wiki.shoryuken.com/images/4/45/%28dudleysa1%29.gif",
        "damage": "375",
        "startup": "1-70",
        "hit": "3/5/3/8/3/2/3/3/3/3/1",
        "recovery": "31",
        "block_adv": "-31",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Rolling Thunder",
        "pic": "http://wiki.shoryuken.com/images/e/e0/%28dudleysa2%29.gif",
        "damage": "415",
        "startup": "2",
        "hit": "2",
        "recovery": "61",
        "block_adv": "-9",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Corkscrew Blow",
        "pic": "http://wiki.shoryuken.com/images/5/5c/%28dudleysa3%29.gif",
        "damage": "275",
        "startup": "1/3/5/7/9",
        "hit": "2x5",
        "recovery": "24",
        "block_adv": "-10",
        "hit_adv": "knd"
    }
]