elena_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/6/64/%28elenat%29.gif",
        "damage": "5+5",
        "startup": "18/17",
        "hit": "2/3",
        "recovery": "62",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/d/de/%28elenalp%29.gif",
        "damage": "40",
        "startup": "5",
        "hit": "4",
        "recovery": "10",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/9/9c/%28elenamp%29.gif",
        "damage": "40+60",
        "startup": "6",
        "hit": "2,3",
        "recovery": "19",
        "block_adv": "-2",
        "hit_adv": "-10"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/2/27/%28elenahp%29.gif",
        "damage": "140",
        "startup": "13",
        "hit": "4",
        "recovery": "19",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/8/8f/%28elenalk%29.gif",
        "damage": "40",
        "startup": "3",
        "hit": "4",
        "recovery": "6",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "http://wiki.shoryuken.com/images/8/80/%28elenamk%29.gif",
        "damage": "90",
        "startup": "7",
        "hit": "2",
        "recovery": "17",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/3/34/%28elenahk%29.gif",
        "damage": "130",
        "startup": "10",
        "hit": "3",
        "recovery": "11",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/3/34/%28elenajlp%29.gif",
        "damage": "50",
        "startup": "4",
        "hit": "10",
        "recovery": "N/A",
        "block_adv": "-8~+7",
        "hit_adv": "-8~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/c/cf/%28elenajmp%29.gif",
        "damage": "100",
        "startup": "6",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "+3~+10",
        "hit_adv": "+3~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/a/a8/%28elenajhp%29.gif",
        "damage": "120",
        "startup": "7",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "-2~+13",
        "hit_adv": "-2~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/c/c7/%28elenajlk%29.gif",
        "damage": "50",
        "startup": "5",
        "hit": "8",
        "recovery": "N/A",
        "block_adv": "-7~+7",
        "hit_adv": "-7~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/b/bb/%28elenajmk%29.gif",
        "damage": "90",
        "startup": "7",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "-5~+10",
        "hit_adv": "-5~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/f/f4/%28elenajhk%29.gif",
        "damage": "40+110",
        "startup": "9/11",
        "hit": "2/4",
        "recovery": "N/A",
        "block_adv": "+4~+13",
        "hit_adv": "+4~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/b/bf/%28elenaoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "f.lp+lk",
        "desc": "Body Slam",
        "pic": "http://wiki.shoryuken.com/images/2/21/%28elenathrow%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Body Slam",
        "pic": "http://wiki.shoryuken.com/images/2/21/%28elenathrow%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/0/0b/%28elenaclp%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "4",
        "recovery": "7",
        "block_adv": "+1",
        "hit_adv": "-1"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/0/06/%28elenacmp%29.gif",
        "damage": "90",
        "startup": "6",
        "hit": "6",
        "recovery": "10",
        "block_adv": "-3",
        "hit_adv": "-2"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/9/9a/%28elenachp%29.gif",
        "damage": "110",
        "startup": "7",
        "hit": "2",
        "recovery": "2235",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/f/ff/%28elenaclk%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "4",
        "recovery": "8",
        "block_adv": "-2",
        "hit_adv": "-2"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/4/4f/%28elenacmk%29.gif",
        "damage": "70",
        "startup": "8",
        "hit": "3",
        "recovery": "13",
        "block_adv": "-3",
        "hit_adv": "-2"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/6/60/%28elenachk%29.gif",
        "damage": "100",
        "startup": "11",
        "hit": "2",
        "recovery": "26",
        "block_adv": "-9",
        "hit_adv": "knd"
    },
    {
        "name": "f.mp",
        "desc": "Handstand Kick",
        "pic": "http://wiki.shoryuken.com/images/f/f3/%28elenafmp%29.gif",
        "damage": "80",
        "startup": "9",
        "hit": "2",
        "recovery": "14",
        "block_adv": "-3",
        "hit_adv": "-2"
    },
    {
        "name": "f.mk",
        "desc": "Handstand Whip",
        "pic": "http://wiki.shoryuken.com/images/9/99/%28elenafmk%29.gif",
        "damage": "80",
        "startup": "11",
        "hit": "8",
        "recovery": "18",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "b.hk",
        "desc": "Round Arch",
        "pic": "http://wiki.shoryuken.com/images/a/a5/%28elenabhk%29.gif",
        "damage": "140",
        "startup": "12",
        "hit": "6",
        "recovery": "12",
        "block_adv": "+4",
        "hit_adv": "+6"
    },
    {
        "name": "df.hk",
        "desc": "Sliding (Sweep)",
        "pic": "http://wiki.shoryuken.com/images/8/8d/%28elenadfhk%29.gif",
        "damage": "100",
        "startup": "12",
        "hit": "6",
        "recovery": "24",
        "block_adv": "-14",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lk",
        "desc": "Scratch Wheel (Short)",
        "pic": "http://wiki.shoryuken.com/images/6/63/%28elenascrw%29.gif",
        "damage": "130",
        "startup": "6",
        "hit": "4",
        "recovery": "31",
        "block_adv": "-19",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mk",
        "desc": "Scratch Wheel (Forward)",
        "pic": "http://wiki.shoryuken.com/images/6/63/%28elenascrw%29.gif",
        "damage": "90+60",
        "startup": "4/7",
        "hit": "3/2",
        "recovery": "36",
        "block_adv": "-22",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hk",
        "desc": "Scratch Wheel (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/6/63/%28elenascrw%29.gif",
        "damage": "90+40+40",
        "startup": "3/5/7",
        "hit": "2/2/3",
        "recovery": "40",
        "block_adv": "-27",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lk",
        "desc": "Spin Scythe (Short)",
        "pic": "http://wiki.shoryuken.com/images/b/ba/%28elenascy%29.gif",
        "damage": "120+40",
        "startup": "15/36/54/62",
        "hit": "2/2/4/2",
        "recovery": "18/42",
        "block_adv": "-2/-28",
        "hit_adv": "0/knd"
    },
    {
        "name": "qcb.mk",
        "desc": "Spin Scythe (Forward)",
        "pic": "http://wiki.shoryuken.com/images/b/ba/%28elenascy%29.gif",
        "damage": "125+45",
        "startup": "16/41/59/67",
        "hit": "2/2/4/2",
        "recovery": "22/42",
        "block_adv": "-6/-33",
        "hit_adv": "-4/knd"
    },
    {
        "name": "qcb.hk",
        "desc": "Spin Scythe (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/b/ba/%28elenascy%29.gif",
        "damage": "130+50",
        "startup": "17/42/60/68",
        "hit": "2/2/4/2",
        "recovery": "24/52",
        "block_adv": "-8/-38",
        "hit_adv": "-6/knd"
    },
    {
        "name": "hcf.lk",
        "desc": "Rhino Horn (Short)",
        "pic": "http://wiki.shoryuken.com/images/d/d7/%28elenaryh%29.gif",
        "damage": "40+140",
        "startup": "14/18/27",
        "hit": "2/2/5",
        "recovery": "14",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.mk",
        "desc": "Rhino Horn (Forward)",
        "pic": "http://wiki.shoryuken.com/images/d/d7/%28elenaryh%29.gif",
        "damage": "40+170",
        "startup": "18/22/31",
        "hit": "3/2/5",
        "recovery": "15",
        "block_adv": "-4",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.hk",
        "desc": "Rhino Horn (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/d/d7/%28elenaryh%29.gif",
        "damage": "40+160",
        "startup": "23/27/36",
        "hit": "3/2/8",
        "recovery": "17",
        "block_adv": "-6",
        "hit_adv": "knd"
    },
    {
        "name": "bdp.lk",
        "desc": "Lynx Tail (Short)",
        "pic": "http://wiki.shoryuken.com/images/8/84/%28elenalxt%29.gif",
        "damage": "60",
        "startup": "11/22",
        "hit": "3/3",
        "recovery": "35",
        "block_adv": "-17",
        "hit_adv": "knd"
    },
    {
        "name": "bdp.mk",
        "desc": "Lynx Tail (Forward)",
        "pic": "http://wiki.shoryuken.com/images/8/84/%28elenalxt%29.gif",
        "damage": "70+60",
        "startup": "14/25",
        "hit": "3/3",
        "recovery": "33",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "bdp.hk",
        "desc": "Lynx Tail (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/8/84/%28elenalxt%29.gif",
        "damage": "80+(10x2)+40",
        "startup": "16/27/54/64",
        "hit": "3/3",
        "recovery": "33",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.lp",
        "desc": "Mallet Smash (Jab)",
        "pic": "http://wiki.shoryuken.com/images/4/4d/%28elenamlsm%29.gif",
        "damage": "120+40",
        "startup": "21/27",
        "hit": "6/2",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "hcb.mp",
        "desc": "Mallet Smash (Strong)",
        "pic": "http://wiki.shoryuken.com/images/4/4d/%28elenamlsm%29.gif",
        "damage": "130+40",
        "startup": "24/29",
        "hit": "5/2",
        "recovery": "12",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "hcb.hp",
        "desc": "Mallet Smash (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/4/4d/%28elenamlsm%29.gif",
        "damage": "140+40",
        "startup": "27/31",
        "hit": "4/2",
        "recovery": "11",
        "block_adv": "+5",
        "hit_adv": "+5"
    },
    {
        "name": "dp.2k",
        "desc": "Scratch Wheel (EX)",
        "pic": "http://wiki.shoryuken.com/images/1/16/%28elenaswex%29.gif",
        "damage": "100+40x3",
        "startup": "3/5/7/9",
        "hit": "2/2/2/2",
        "recovery": "42",
        "block_adv": "-26",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.2k",
        "desc": "Rhino Horn (EX)",
        "pic": "http://wiki.shoryuken.com/images/f/f6/%28elenarhex%29.gif",
        "damage": "45+100+80",
        "startup": "11/15/23",
        "hit": "3/2/8",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2k",
        "desc": "Spin Scythe (EX)",
        "pic": "http://wiki.shoryuken.com/images/7/77/%28elenassex%29.gif",
        "damage": "60x3+40",
        "startup": "10/24/38/50",
        "hit": "2/22/2",
        "recovery": "31/42",
        "block_adv": "-15/-15",
        "hit_adv": "-1/knd"
    },
    {
        "name": "hcb.2p",
        "desc": "Mallet Smash (EX)",
        "pic": "http://wiki.shoryuken.com/images/3/3a/%28elenamsmex%29.gif",
        "damage": "120+60",
        "startup": "21/23",
        "hit": "2/2",
        "recovery": "10",
        "block_adv": "+4",
        "hit_adv": "+5"
    },
    {
        "name": "bdp.2k",
        "desc": "Lynx Tail (EX)",
        "pic": "http://wiki.shoryuken.com/images/a/a4/%28elenaltex%29.gif",
        "damage": "80+10x3+40",
        "startup": "10/18/36/44/66",
        "hit": "4x4/6",
        "recovery": "25",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Spinning Beat",
        "pic": "http://wiki.shoryuken.com/images/4/4b/%28elenasa1%29.gif",
        "damage": "310",
        "startup": "1/21/43",
        "hit": "4/5/8",
        "recovery": "43",
        "block_adv": "-30",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Brave Dance",
        "pic": "http://wiki.shoryuken.com/images/e/ef/%28elenasa2%29.gif",
        "damage": "400",
        "startup": "1",
        "hit": "15+2x7+3+5",
        "recovery": "29",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Healing",
        "pic": "http://wiki.shoryuken.com/images/8/86/%28elenasa3%29.gif",
        "damage": "N/A",
        "startup": "33",
        "hit": "75",
        "recovery": "15",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    }
]