gouki_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "framedata/img/go-taunt.gif",
        "damage": "N/A",
        "startup": "66",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "framedata/img/go-lp.gif",
        "damage": "20",
        "startup": "4",
        "hit": "3",
        "recovery": "4",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "framedata/img/go-mp.gif",
        "damage": "105",
        "startup": "5",
        "hit": "4",
        "recovery": "9",
        "block_adv": "+4",
        "hit_adv": "+5"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "framedata/img/go-hp.gif",
        "damage": "140",
        "startup": "8",
        "hit": "5",
        "recovery": "22",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "framedata/img/go-closelp.gif",
        "damage": "30",
        "startup": "3",
        "hit": "3",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "framedata/img/go-closemp.gif",
        "damage": "115",
        "startup": "5",
        "hit": "4",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "framedata/img/go-closehp.gif",
        "damage": "135",
        "startup": "4",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "framedata/img/go-lk.gif",
        "damage": "40",
        "startup": "4",
        "hit": "4",
        "recovery": "7",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "framedata/img/go-mk.gif",
        "damage": "95",
        "startup": "5",
        "hit": "5",
        "recovery": "17",
        "block_adv": "-7",
        "hit_adv": "-6"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "framedata/img/go-hk.gif",
        "damage": "145",
        "startup": "9",
        "hit": "5",
        "recovery": "20",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "framedata/img/go-closemk.gif",
        "damage": "115",
        "startup": "4",
        "hit": "5",
        "recovery": "11",
        "block_adv": "+2",
        "hit_adv": "+4"
    },
    {
        "name": "close.hk",
        "desc": "Close Roundhouse",
        "pic": "framedata/img/go-closehk.gif",
        "damage": "120+80",
        "startup": "5/7",
        "hit": "3/5",
        "recovery": "19",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "framedata/img/go-alp.gif",
        "damage": "40",
        "startup": "4",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "framedata/img/go-amp.gif",
        "damage": "90",
        "startup": "5",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "framedata/img/go-ahp.gif",
        "damage": "90(130 neutral jump)",
        "startup": "6",
        "hit": "4(3 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+3~+13(+6~+13 neutral jump)",
        "hit_adv": "+3~+13(+6~+13 neutral jump)"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "framedata/img/go-alk.gif",
        "damage": "40",
        "startup": "4",
        "hit": "10(19 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-6~+7",
        "hit_adv": "-6~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "framedata/img/go-amk.gif",
        "damage": "80",
        "startup": "5",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "framedata/img/go-ahk.gif",
        "damage": "120",
        "startup": "6",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "framedata/img/go-overhead.gif",
        "damage": "40",
        "startup": "15",
        "hit": "8",
        "recovery": "7",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Seoi Nage",
        "pic": "framedata/img/go-fthrow.gif",
        "damage": "110",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Tomoe Nage",
        "pic": "framedata/img/go-bthrow.gif",
        "damage": "110",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "framedata/img/go-clp.gif",
        "damage": "20",
        "startup": "4",
        "hit": "3",
        "recovery": "4",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "framedata/img/go-cmp.gif",
        "damage": "95",
        "startup": "5",
        "hit": "4",
        "recovery": "7",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "framedata/img/go-chp.gif",
        "damage": "135",
        "startup": "5",
        "hit": "5",
        "recovery": "19",
        "block_adv": "-8",
        "hit_adv": "-6"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "framedata/img/go-clk.gif",
        "damage": "20",
        "startup": "5",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "framedata/img/go-cmk.gif",
        "damage": "90",
        "startup": "6",
        "hit": "5",
        "recovery": "16",
        "block_adv": "-3",
        "hit_adv": "-2"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "framedata/img/go-chk.gif",
        "damage": "135",
        "startup": "7",
        "hit": "5",
        "recovery": "25",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "f.mp",
        "desc": "Zugai Hasatsu",
        "pic": "framedata/img/go-fmp.gif",
        "damage": "40+50",
        "startup": "14",
        "hit": "1",
        "recovery": "22",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "air.d.mk",
        "desc": "Tenma Kuujin Kyaku",
        "pic": "framedata/img/go-adk.gif",
        "damage": "90",
        "startup": "8",
        "hit": "until land",
        "recovery": "3",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "qcf.lp",
        "desc": "Gou Hadouken",
        "pic": "framedata/img/go-qcfp.gif",
        "damage": "60",
        "startup": "7",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-11",
        "hit_adv": "-10"
    },
    {
        "name": "qcf.mp",
        "desc": "Gou Hadouken",
        "pic": "framedata/img/go-qcfp.gif",
        "damage": "60",
        "startup": "7",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-11",
        "hit_adv": "-10"
    },
    {
        "name": "qcf.hp",
        "desc": "Gou Hadouken",
        "pic": "framedata/img/go-qcfp.gif",
        "damage": "60",
        "startup": "7",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-11",
        "hit_adv": "-10"
    },
    {
        "name": "air.qcf.lp",
        "desc": "Zankuu Hadouken",
        "pic": "framedata/img/go-aqcfp.gif",
        "damage": "60",
        "startup": "11",
        "hit": "1",
        "recovery": "7",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcf.mp",
        "desc": "Zankuu Hadouken",
        "pic": "framedata/img/go-aqcfp.gif",
        "damage": "60",
        "startup": "11",
        "hit": "1",
        "recovery": "7",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcf.hp",
        "desc": "Zankuu Hadouken",
        "pic": "framedata/img/go-aqcfp.gif",
        "damage": "60",
        "startup": "11",
        "hit": "1",
        "recovery": "7",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "hcb.lp",
        "desc": "Shakunestsu Hadouken (Jab)",
        "pic": "framedata/img/go-hcbp.gif",
        "damage": "50",
        "startup": "13",
        "hit": "1",
        "recovery": "42",
        "block_adv": "-23",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mp",
        "desc": "Shakunestsu Hadouken (Strong)",
        "pic": "framedata/img/go-hcbp.gif",
        "damage": "50",
        "startup": "17",
        "hit": "1",
        "recovery": "43",
        "block_adv": "-18",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.hp",
        "desc": "Shakunestsu Hadouken (Fierce)",
        "pic": "framedata/img/go-hcbp.gif",
        "damage": "50",
        "startup": "21",
        "hit": "1",
        "recovery": "44",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcb.lk",
        "desc": "Air Tatsumaki Zankuukyaku (Short)",
        "pic": "framedata/img/go-aqcbk.gif",
        "damage": "80",
        "startup": "5/9",
        "hit": "2/1",
        "recovery": "9",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcb.mk",
        "desc": "Air Tatsumaki Zankuukyaku (Forward)",
        "pic": "framedata/img/go-aqcbk.gif",
        "damage": "80x2",
        "startup": "5/9/12/16",
        "hit": "2/1/2/1",
        "recovery": "9",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcb.hk",
        "desc": "Air Tatsumaki Zankuukyaku (Roundhouse)",
        "pic": "framedata/img/go-aqcbk.gif",
        "damage": "80x3",
        "startup": "5-30",
        "hit": "2/1/2/1/2/1/2/1",
        "recovery": "9",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lk",
        "desc": "Tatsumaki Zankuukyaku (Short)",
        "pic": "framedata/img/go-qcbk.gif",
        "damage": "100",
        "startup": "11/(14)",
        "hit": "2/(2)",
        "recovery": "17",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.mk",
        "desc": "Tatsumaki Zankuukyaku (Forward)",
        "pic": "framedata/img/go-qcbk.gif",
        "damage": "120",
        "startup": "2/11/(14)/18/(21)",
        "hit": "2/2/(2)/2/(2)",
        "recovery": "16",
        "block_adv": "-8",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.hk",
        "desc": "Tatsumaki Zankuukyaku (Roundhouse)",
        "pic": "framedata/img/go-qcbk.gif",
        "damage": "150",
        "startup": "2/11/(14)/18/(21)/25/(28)/32/(35)",
        "hit": "2/2/(2)/2/(2)/2/(2)/2/(2)",
        "recovery": "10",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lp",
        "desc": "Gou Shoryuken (Jab)",
        "pic": "framedata/img/go-dp.gif",
        "damage": "130",
        "startup": "3",
        "hit": "14",
        "recovery": "26",
        "block_adv": "-24",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mp",
        "desc": "Gou Shoryuken (Strong)",
        "pic": "framedata/img/go-dp.gif",
        "damage": "150",
        "startup": "2",
        "hit": "2/5",
        "recovery": "41",
        "block_adv": "-30",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Gou Shoryuken (Fierce)",
        "pic": "framedata/img/go-dp.gif",
        "damage": "180",
        "startup": "1",
        "hit": "2/2/19",
        "recovery": "35",
        "block_adv": "-34",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lk",
        "desc": "Hyakki Gouzan",
        "pic": "framedata/img/go-dpk.gif",
        "damage": "100",
        "startup": "41",
        "hit": "15",
        "recovery": "13",
        "block_adv": "-1",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lk,lp",
        "desc": "Hyakki Goushou",
        "pic": "framedata/img/go-dpktop.gif",
        "damage": "130",
        "startup": "10",
        "hit": "3",
        "recovery": "17",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lk,lk",
        "desc": "Hyakki Goujin",
        "pic": "framedata/img/go-dpktok.gif",
        "damage": "100",
        "startup": "9",
        "hit": "until land",
        "recovery": "3",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "dp.lk,lp+lk",
        "desc": "Hyakki Gousai",
        "pic": "framedata/img/go-dpktokp.gif",
        "damage": "110",
        "startup": "3",
        "hit": "2",
        "recovery": "17",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2p",
        "desc": "Ashura Senkuu (PP)",
        "pic": "framedata/img/go-dp2p.gif",
        "damage": "N/A",
        "startup": "20",
        "hit": "46",
        "recovery": "9",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "dp.2k",
        "desc": "Ashura Senkuu (KK)",
        "pic": "framedata/img/go-dp2k.gif",
        "damage": "N/A",
        "startup": "20",
        "hit": "30",
        "recovery": "9",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "sa1",
        "desc": "Messatsu-Gou Hadou",
        "pic": "framedata/img/go-sa1.gif",
        "damage": "290",
        "startup": "2",
        "hit": "1",
        "recovery": "49",
        "block_adv": "-13",
        "hit_adv": "knd"
    },
    {
        "name": "air.sa1",
        "desc": "Tenma-Gou Zankuu",
        "pic": "framedata/img/go-airsa1.gif",
        "damage": "320",
        "startup": "7",
        "hit": "1",
        "recovery": "13",
        "block_adv": "-49",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Messatsu Gou Shoryu",
        "pic": "framedata/img/go-sa2.gif",
        "damage": "390",
        "startup": "1",
        "hit": "2",
        "recovery": "37",
        "block_adv": "-25",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Messatsu Gou Rasen",
        "pic": "framedata/img/go-sa3.gif",
        "damage": "390",
        "startup": "14",
        "hit": "2",
        "recovery": "51",
        "block_adv": "-35",
        "hit_adv": "knd"
    },
    {
        "name": "air.sa3",
        "desc": "Messatsu Gou Senpuu",
        "pic": "framedata/img/go-sa3.gif",
        "damage": "405",
        "startup": "9",
        "hit": "1",
        "recovery": "51",
        "block_adv": "-35",
        "hit_adv": "knd"
    },
    {
        "name": "lp,lp,f,lk,hp",
        "desc": "Shun Goku Satsu",
        "pic": "framedata/img/go-super.gif",
        "damage": "490",
        "startup": "1",
        "hit": "38",
        "recovery": "2",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "d,d,d+3p",
        "desc": "Kongou Kokuretsu Zan",
        "pic": "framedata/img/go-dddppp.gif",
        "damage": "640",
        "startup": "16",
        "hit": "6",
        "recovery": "58",
        "block_adv": "-26",
        "hit_adv": "knd"
    }
]