gouki_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/c/c6/%28akumat%29.gif",
        "damage": "N/A",
        "startup": "66",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/e/e8/%28akumalp%29.gif",
        "damage": "20",
        "startup": "4",
        "hit": "3",
        "recovery": "4",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/b/be/%28akumamp%29.gif",
        "damage": "105",
        "startup": "5",
        "hit": "4",
        "recovery": "9",
        "block_adv": "+4",
        "hit_adv": "+5"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/c/cf/%28akumahp%29.gif",
        "damage": "140",
        "startup": "8",
        "hit": "5",
        "recovery": "22",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "http://wiki.shoryuken.com/images/b/bf/%28akumacloselp%29.gif",
        "damage": "30",
        "startup": "3",
        "hit": "3",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "http://wiki.shoryuken.com/images/d/d9/%28akumaclosemp%29.gif",
        "damage": "115",
        "startup": "5",
        "hit": "4",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "http://wiki.shoryuken.com/images/9/94/%28akumaclosehp%29.gif",
        "damage": "135",
        "startup": "4",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/d/d7/%28akumalk%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "4",
        "recovery": "7",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "http://wiki.shoryuken.com/images/4/43/%28akumamk%29.gif",
        "damage": "95",
        "startup": "5",
        "hit": "5",
        "recovery": "17",
        "block_adv": "-7",
        "hit_adv": "-6"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/2/22/%28akumahk%29.gif",
        "damage": "145",
        "startup": "9",
        "hit": "5",
        "recovery": "20",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "http://wiki.shoryuken.com/images/4/49/%28akumaclosemk%29.gif",
        "damage": "115",
        "startup": "4",
        "hit": "5",
        "recovery": "11",
        "block_adv": "+2",
        "hit_adv": "+4"
    },
    {
        "name": "close.hk",
        "desc": "Close Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/b/b4/%28akumaclosehk%29.gif",
        "damage": "120+80",
        "startup": "5/7",
        "hit": "3/5",
        "recovery": "19",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28akumajlp%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/a/ab/%28akumajmp%29.gif",
        "damage": "90",
        "startup": "5",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/a/a2/%28akumajhp%29.gif",
        "damage": "90(130 neutral jump)",
        "startup": "6",
        "hit": "4(3 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+3~+13(+6~+13 neutral jump)",
        "hit_adv": "+3~+13(+6~+13 neutral jump)"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/1/1a/%28akumajlk%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "10(19 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-6~+7",
        "hit_adv": "-6~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/5/51/%28akumajmk%29.gif",
        "damage": "80",
        "startup": "5",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/5/50/%28akumajhk%29.gif",
        "damage": "120",
        "startup": "6",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/1/1e/%28akumaoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "8",
        "recovery": "7",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Seoi Nage",
        "pic": "http://wiki.shoryuken.com/images/a/a4/%28akumasn%29.gif",
        "damage": "110",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Tomoe Nage",
        "pic": "http://wiki.shoryuken.com/images/5/5a/%28akumatn%29.gif",
        "damage": "110",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/4/44/%28akumaclp%29.gif",
        "damage": "20",
        "startup": "4",
        "hit": "3",
        "recovery": "4",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/a/ae/%28akumacmp%29.gif",
        "damage": "95",
        "startup": "5",
        "hit": "4",
        "recovery": "7",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/1/18/%28akumachp%29.gif",
        "damage": "135",
        "startup": "5",
        "hit": "5",
        "recovery": "19",
        "block_adv": "-8",
        "hit_adv": "-6"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/3/34/%28akumaclk%29.gif",
        "damage": "20",
        "startup": "5",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/3/34/%28akumaclk%29.gif",
        "damage": "90",
        "startup": "6",
        "hit": "5",
        "recovery": "16",
        "block_adv": "-3",
        "hit_adv": "-2"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/3/34/%28akumaclk%29.gif",
        "damage": "135",
        "startup": "7",
        "hit": "5",
        "recovery": "25",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "f.mp",
        "desc": "Zugai Hasatsu",
        "pic": "http://wiki.shoryuken.com/images/7/70/%28akumafmp%29.gif",
        "damage": "40+50",
        "startup": "14",
        "hit": "1",
        "recovery": "22",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "air.d.mk",
        "desc": "Tenma Kuujin Kyaku",
        "pic": "http://wiki.shoryuken.com/images/9/93/%28akumajdmk%29.gif",
        "damage": "90",
        "startup": "8",
        "hit": "until land",
        "recovery": "3",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "qcf.lp",
        "desc": "Gou Hadouken",
        "pic": "http://wiki.shoryuken.com/images/d/d0/%28akumahdk%29.gif",
        "damage": "60",
        "startup": "7",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-11",
        "hit_adv": "-10"
    },
    {
        "name": "qcf.mp",
        "desc": "Gou Hadouken",
        "pic": "http://wiki.shoryuken.com/images/d/d0/%28akumahdk%29.gif",
        "damage": "60",
        "startup": "7",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-11",
        "hit_adv": "-10"
    },
    {
        "name": "qcf.hp",
        "desc": "Gou Hadouken",
        "pic": "http://wiki.shoryuken.com/images/d/d0/%28akumahdk%29.gif",
        "damage": "60",
        "startup": "7",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-11",
        "hit_adv": "-10"
    },
    {
        "name": "air.qcf.lp",
        "desc": "Zankuu Hadouken",
        "pic": "http://wiki.shoryuken.com/images/8/84/%28akumazhdk%29.gif",
        "damage": "60",
        "startup": "11",
        "hit": "1",
        "recovery": "7",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcf.mp",
        "desc": "Zankuu Hadouken",
        "pic": "http://wiki.shoryuken.com/images/8/84/%28akumazhdk%29.gif",
        "damage": "60",
        "startup": "11",
        "hit": "1",
        "recovery": "7",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcf.hp",
        "desc": "Zankuu Hadouken",
        "pic": "http://wiki.shoryuken.com/images/8/84/%28akumazhdk%29.gif",
        "damage": "60",
        "startup": "11",
        "hit": "1",
        "recovery": "7",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "hcb.lp",
        "desc": "Shakunestsu Hadouken (Jab)",
        "pic": "http://wiki.shoryuken.com/images/5/5a/%28akumashdk%29.gif",
        "damage": "50",
        "startup": "13",
        "hit": "1",
        "recovery": "42",
        "block_adv": "-23",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mp",
        "desc": "Shakunestsu Hadouken (Strong)",
        "pic": "http://wiki.shoryuken.com/images/5/5a/%28akumashdk%29.gif",
        "damage": "50",
        "startup": "17",
        "hit": "1",
        "recovery": "43",
        "block_adv": "-18",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.hp",
        "desc": "Shakunestsu Hadouken (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/5/5a/%28akumashdk%29.gif",
        "damage": "50",
        "startup": "21",
        "hit": "1",
        "recovery": "44",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcb.lk",
        "desc": "Air Tatsumaki Zankuukyaku (Short)",
        "pic": "http://wiki.shoryuken.com/images/1/1b/%28akumaatzk%29.gif",
        "damage": "80",
        "startup": "5/9",
        "hit": "2/1",
        "recovery": "9",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcb.mk",
        "desc": "Air Tatsumaki Zankuukyaku (Forward)",
        "pic": "http://wiki.shoryuken.com/images/1/1b/%28akumaatzk%29.gif",
        "damage": "80x2",
        "startup": "5/9/12/16",
        "hit": "2/1/2/1",
        "recovery": "9",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcb.hk",
        "desc": "Air Tatsumaki Zankuukyaku (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/1/1b/%28akumaatzk%29.gif",
        "damage": "80x3",
        "startup": "5-30",
        "hit": "2/1/2/1/2/1/2/1",
        "recovery": "9",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lk",
        "desc": "Tatsumaki Zankuukyaku (Short)",
        "pic": "http://wiki.shoryuken.com/images/0/07/%28akumatzk%29.gif",
        "damage": "100",
        "startup": "11/(14)",
        "hit": "2/(2)",
        "recovery": "17",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.mk",
        "desc": "Tatsumaki Zankuukyaku (Forward)",
        "pic": "http://wiki.shoryuken.com/images/0/07/%28akumatzk%29.gif",
        "damage": "120",
        "startup": "2/11/(14)/18/(21)",
        "hit": "2/2/(2)/2/(2)",
        "recovery": "16",
        "block_adv": "-8",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.hk",
        "desc": "Tatsumaki Zankuukyaku (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/0/07/%28akumatzk%29.gif",
        "damage": "150",
        "startup": "2/11/(14)/18/(21)/25/(28)/32/(35)",
        "hit": "2/2/(2)/2/(2)/2/(2)/2/(2)",
        "recovery": "10",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lp",
        "desc": "Gou Shoryuken (Jab)",
        "pic": "http://wiki.shoryuken.com/images/7/7e/%28akumasrk%29.gif",
        "damage": "130",
        "startup": "3",
        "hit": "14",
        "recovery": "26",
        "block_adv": "-24",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mp",
        "desc": "Gou Shoryuken (Strong)",
        "pic": "http://wiki.shoryuken.com/images/7/7e/%28akumasrk%29.gif",
        "damage": "150",
        "startup": "2",
        "hit": "2/5",
        "recovery": "41",
        "block_adv": "-30",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Gou Shoryuken (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/7/7e/%28akumasrk%29.gif",
        "damage": "180",
        "startup": "1",
        "hit": "2/2/19",
        "recovery": "35",
        "block_adv": "-34",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lk",
        "desc": "Hyakki Gouzan",
        "pic": "http://wiki.shoryuken.com/images/9/9e/%28akumahgouzan%29.gif",
        "damage": "100",
        "startup": "41",
        "hit": "15",
        "recovery": "13",
        "block_adv": "-1",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lk,lp",
        "desc": "Hyakki Goushou",
        "pic": "http://wiki.shoryuken.com/images/3/36/%28akumahgoushou%29.gif",
        "damage": "130",
        "startup": "10",
        "hit": "3",
        "recovery": "17",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lk,lk",
        "desc": "Hyakki Goujin",
        "pic": "http://wiki.shoryuken.com/images/1/13/%28akumahgoujin%29.gif",
        "damage": "100",
        "startup": "9",
        "hit": "until land",
        "recovery": "3",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "dp.lk,lp+lk",
        "desc": "Hyakki Gousai",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28akumahgousai%29.gif",
        "damage": "110",
        "startup": "3",
        "hit": "2",
        "recovery": "17",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2p",
        "desc": "Ashura Senkuu (PP)",
        "pic": "http://wiki.shoryuken.com/images/7/7c/%28akumaasf%29.gif",
        "damage": "N/A",
        "startup": "20",
        "hit": "46",
        "recovery": "9",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "dp.2k",
        "desc": "Ashura Senkuu (KK)",
        "pic": "http://wiki.shoryuken.com/images/7/7c/%28akumaasf%29.gif",
        "damage": "N/A",
        "startup": "20",
        "hit": "30",
        "recovery": "9",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "sa1",
        "desc": "Messatsu-Gou Hadou",
        "pic": "http://wiki.shoryuken.com/images/6/69/%28akumamgh%29.gif",
        "damage": "290",
        "startup": "2",
        "hit": "1",
        "recovery": "49",
        "block_adv": "-13",
        "hit_adv": "knd"
    },
    {
        "name": "air.sa1",
        "desc": "Tenma-Gou Zankuu",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28akumatgz%29.gif",
        "damage": "320",
        "startup": "7",
        "hit": "1",
        "recovery": "13",
        "block_adv": "-49",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Messatsu Gou Shoryu",
        "pic": "http://wiki.shoryuken.com/images/8/82/%28akumamgs%29.gif",
        "damage": "390",
        "startup": "1",
        "hit": "2",
        "recovery": "37",
        "block_adv": "-25",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Messatsu Gou Rasen",
        "pic": "http://wiki.shoryuken.com/images/e/e8/%28akumamgr%29.gif",
        "damage": "390",
        "startup": "14",
        "hit": "2",
        "recovery": "51",
        "block_adv": "-35",
        "hit_adv": "knd"
    },
    {
        "name": "air.sa3",
        "desc": "Messatsu Gou Senpuu",
        "pic": "http://wiki.shoryuken.com/images/e/e8/%28akumamgr%29.gif",
        "damage": "405",
        "startup": "9",
        "hit": "1",
        "recovery": "51",
        "block_adv": "-35",
        "hit_adv": "knd"
    },
    {
        "name": "lp,lp,f,lk,hp",
        "desc": "Shun Goku Satsu",
        "pic": "http://wiki.shoryuken.com/images/e/e8/%28akumamgr%29.gif",
        "damage": "490",
        "startup": "1",
        "hit": "38",
        "recovery": "2",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "d,d,d+3p",
        "desc": "Kongou Kokuretsu Zan",
        "pic": "http://wiki.shoryuken.com/images/1/11/%28akumakkz%29.gif",
        "damage": "640",
        "startup": "16",
        "hit": "6",
        "recovery": "58",
        "block_adv": "-26",
        "hit_adv": "knd"
    }
]