hugo_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/7/75/%28hugotaunt%29.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "68(95 hold)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Jab",
        "pic": "http://wiki.shoryuken.com/images/d/dc/%28hugolp%29.gif",
        "damage": "35",
        "startup": "4",
        "hit": "4",
        "recovery": "8",
        "block_adv": "-1",
        "hit_adv": "-1"
    },
    {
        "name": "mp",
        "desc": "Strong",
        "pic": "http://wiki.shoryuken.com/images/0/0c/%28hugomp%29.gif",
        "damage": "120",
        "startup": "10",
        "hit": "7",
        "recovery": "12",
        "block_adv": "-5",
        "hit_adv": "0"
    },
    {
        "name": "hp",
        "desc": "Fierce",
        "pic": "http://wiki.shoryuken.com/images/6/69/%28hugohp%29.gif",
        "damage": "170",
        "startup": "16",
        "hit": "7",
        "recovery": "15",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/0/02/%28hugolk%29.gif",
        "damage": "50",
        "startup": "5",
        "hit": "4",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "http://wiki.shoryuken.com/images/7/7b/%28hugomk%29.gif",
        "damage": "115",
        "startup": "9/14",
        "hit": "2/4",
        "recovery": "23",
        "block_adv": "-4",
        "hit_adv": "+1"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/c/cf/%28hugojhk%29.gif",
        "damage": "150",
        "startup": "21",
        "hit": "8",
        "recovery": "28",
        "block_adv": "-13",
        "hit_adv": "+3"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/e/ec/%28hugojlp%29.gif",
        "damage": "40",
        "startup": "3",
        "hit": "11",
        "recovery": "N/A",
        "block_adv": "-3~+7",
        "hit_adv": "-3~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/6/61/%28hugojmp%29.gif",
        "damage": "100",
        "startup": "6",
        "hit": "8",
        "recovery": "N/A",
        "block_adv": "0~+10",
        "hit_adv": "0~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/1/18/%28hugojhp%29.gif",
        "damage": "150",
        "startup": "11",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "+4~+13",
        "hit_adv": "+4~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/2/25/%28hugojlk%29.gif",
        "damage": "60",
        "startup": "3",
        "hit": "16",
        "recovery": "N/A",
        "block_adv": "-9~+7",
        "hit_adv": "-9~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/9/99/%28hugojmk%29.gif",
        "damage": "100",
        "startup": "5",
        "hit": "7",
        "recovery": "N/A",
        "block_adv": "-4~+10",
        "hit_adv": "-4~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/c/cf/%28hugojhk%29.gif",
        "damage": "130",
        "startup": "11",
        "hit": "7",
        "recovery": "N/A",
        "block_adv": "-2~+13",
        "hit_adv": "-2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/9/9b/%28hugouoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Neck Hanging Three",
        "pic": "http://wiki.shoryuken.com/images/8/88/%28hugonht%29.gif",
        "damage": "130",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Body Slam",
        "pic": "http://wiki.shoryuken.com/images/7/76/%28hugobs%29.gif",
        "damage": "160",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Body Slam",
        "pic": "http://wiki.shoryuken.com/images/7/76/%28hugobs%29.gif",
        "damage": "160",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/4/46/%28hugoclp%29.gif",
        "damage": "30",
        "startup": "4",
        "hit": "3",
        "recovery": "8",
        "block_adv": "-1",
        "hit_adv": "-1"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/c/ca/%28hugocmp%29.gif",
        "damage": "120",
        "startup": "7",
        "hit": "5",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/7/7d/%28hugochp%29.gif",
        "damage": "110",
        "startup": "13",
        "hit": "10",
        "recovery": "37",
        "block_adv": "-29",
        "hit_adv": "knd"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/4/42/%28hugoclk%29.gif",
        "damage": "40",
        "startup": "3",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/b/b7/%28hugocmk%29.gif",
        "damage": "100",
        "startup": "8",
        "hit": "5",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/0/07/%28hugochk%29.gif",
        "damage": "170",
        "startup": "11",
        "hit": "23",
        "recovery": "24~38",
        "block_adv": "-43",
        "hit_adv": "knd"
    },
    {
        "name": "f.hp",
        "desc": "Hammer Hook",
        "pic": "http://wiki.shoryuken.com/images/2/20/%28hugofhp%29.gif",
        "damage": "160",
        "startup": "14",
        "hit": "4",
        "recovery": "33",
        "block_adv": "-14",
        "hit_adv": "+4"
    },
    {
        "name": "f.hk",
        "desc": "Drop Kick",
        "pic": "http://wiki.shoryuken.com/images/c/cf/%28hugojhk%29.gif",
        "damage": "150",
        "startup": "21",
        "hit": "8",
        "recovery": "27",
        "block_adv": "-12",
        "hit_adv": "+4"
    },
    {
        "name": "b.hk",
        "desc": "Drop Kick",
        "pic": "http://wiki.shoryuken.com/images/c/cf/%28hugojhk%29.gif",
        "damage": "150",
        "startup": "21",
        "hit": "8",
        "recovery": "27",
        "block_adv": "-12",
        "hit_adv": "+4"
    },
    {
        "name": "air.d.hp",
        "desc": "Body Press",
        "pic": "http://wiki.shoryuken.com/images/e/e2/%28hugojdhp%29.gif",
        "damage": "100",
        "startup": "9",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "qcb.lp",
        "desc": "Giant Palm Bomber (Jab)",
        "pic": "http://wiki.shoryuken.com/images/3/3d/%28hugogpb%29.gif",
        "damage": "110",
        "startup": "17",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+11",
        "hit_adv": "+13"
    },
    {
        "name": "qcb.mp",
        "desc": "Giant Palm Bomber (Strong)",
        "pic": "http://wiki.shoryuken.com/images/3/3d/%28hugogpb%29.gif",
        "damage": "125",
        "startup": "19",
        "hit": "2",
        "recovery": "7",
        "block_adv": "+16",
        "hit_adv": "+18"
    },
    {
        "name": "qcb.hp",
        "desc": "Giant Palm Bomber (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/3/3d/%28hugogpb%29.gif",
        "damage": "140",
        "startup": "22",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+19",
        "hit_adv": "+21"
    },
    {
        "name": "360.lp",
        "desc": "Moonsault Press (Jab)",
        "pic": "http://wiki.shoryuken.com/images/6/6f/%28hugomsp%29.gif",
        "damage": "240",
        "startup": "2",
        "hit": "2",
        "recovery": "36",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "360.mp",
        "desc": "Moonsault Press (Strong)",
        "pic": "http://wiki.shoryuken.com/images/6/6f/%28hugomsp%29.gif",
        "damage": "255",
        "startup": "2",
        "hit": "2",
        "recovery": "36",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "360.hp",
        "desc": "Moonsault Press (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/6/6f/%28hugomsp%29.gif",
        "damage": "280",
        "startup": "2",
        "hit": "2",
        "recovery": "36",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.lk",
        "desc": "Monster Lariat (Short)",
        "pic": "http://wiki.shoryuken.com/images/f/f6/%28hugoml%29.gif",
        "damage": "150",
        "startup": "11",
        "hit": "5",
        "recovery": "21~25",
        "block_adv": "-8",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.mk",
        "desc": "Monster Lariat (Short)",
        "pic": "http://wiki.shoryuken.com/images/f/f6/%28hugoml%29.gif",
        "damage": "160",
        "startup": "15",
        "hit": "5",
        "recovery": "23~27",
        "block_adv": "-10",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.hk",
        "desc": "Monster Lariat (Short)",
        "pic": "http://wiki.shoryuken.com/images/f/f6/%28hugoml%29.gif",
        "damage": "170",
        "startup": "24",
        "hit": "5",
        "recovery": "24~28",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lk",
        "desc": "Shootdown Backbreaker (Short)",
        "pic": "http://wiki.shoryuken.com/images/9/96/%28hugosbb%29.gif",
        "damage": "180",
        "startup": "5",
        "hit": "9",
        "recovery": "30",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mk",
        "desc": "Shootdown Backbreaker (Forward)",
        "pic": "http://wiki.shoryuken.com/images/9/96/%28hugosbb%29.gif",
        "damage": "200",
        "startup": "17",
        "hit": "10",
        "recovery": "25",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hk",
        "desc": "Shootdown Backbreaker (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/9/96/%28hugosbb%29.gif",
        "damage": "220",
        "startup": "12",
        "hit": "12",
        "recovery": "29",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "360.lk",
        "desc": "Meat Squasher (Short)",
        "pic": "http://wiki.shoryuken.com/images/9/9c/%28hugomsquasher%29.gif",
        "damage": "160",
        "startup": "20~24",
        "hit": "2",
        "recovery": "30",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "360.mk",
        "desc": "Meat Squasher (Forward)",
        "pic": "http://wiki.shoryuken.com/images/9/9c/%28hugomsquasher%29.gif",
        "damage": "160",
        "startup": "30~52",
        "hit": "2",
        "recovery": "33",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "360.hk",
        "desc": "Meat Squasher (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/9/9c/%28hugomsquasher%29.gif",
        "damage": "160",
        "startup": "47~67",
        "hit": "2",
        "recovery": "36",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.lk",
        "desc": "Ultra Throw (Short)",
        "pic": "http://wiki.shoryuken.com/images/a/a8/%28hugout%29.gif",
        "damage": "70",
        "startup": "7",
        "hit": "2",
        "recovery": "36",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mk",
        "desc": "Ultra Throw (Forward)",
        "pic": "http://wiki.shoryuken.com/images/a/a8/%28hugout%29.gif",
        "damage": "70",
        "startup": "7",
        "hit": "2",
        "recovery": "36",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mk",
        "desc": "Ultra Throw (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/a/a8/%28hugout%29.gif",
        "damage": "70",
        "startup": "7",
        "hit": "2",
        "recovery": "36",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2p",
        "desc": "Giant Palm Bomber (EX)",
        "pic": "http://wiki.shoryuken.com/images/b/b1/%28hugogpbex%29.gif",
        "damage": "220",
        "startup": "22",
        "hit": "1",
        "recovery": "10",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.2k",
        "desc": "Giant Palm Bomber (EX)",
        "pic": "http://wiki.shoryuken.com/images/a/a0/%28hugomlex%29.gif",
        "damage": "140~180",
        "startup": "6~26",
        "hit": "6",
        "recovery": "31~35",
        "block_adv": "-22",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Gigas Breaker",
        "pic": "http://wiki.shoryuken.com/images/8/87/%28hugosa1%29.gif",
        "damage": "610",
        "startup": "1",
        "hit": "2",
        "recovery": "36",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Megaton Press",
        "pic": "http://wiki.shoryuken.com/images/e/ea/%28hugosa2%29.gif",
        "damage": "450",
        "startup": "3/5/7",
        "hit": "12/16/34",
        "recovery": "30/34/36",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Hammer Frenzy",
        "pic": "http://wiki.shoryuken.com/images/7/70/%28hugosa3%29.gif",
        "damage": "390",
        "startup": "4",
        "hit": "5",
        "recovery": "47",
        "block_adv": "-29",
        "hit_adv": "knd"
    }
]