ibuki_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/d/db/%28ibukit%29.gif",
        "damage": "5",
        "startup": "14",
        "hit": "9",
        "recovery": "8",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/d/d5/%28ibukilp%29.gif",
        "damage": "30",
        "startup": "2",
        "hit": "1",
        "recovery": "5",
        "block_adv": "+6",
        "hit_adv": "+6"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/9/90/%28ibukimp%29.gif",
        "damage": "70",
        "startup": "6",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+6",
        "hit_adv": "+7"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/3/35/%28ibukihp%29.gif",
        "damage": "70",
        "startup": "13",
        "hit": "4",
        "recovery": "14",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "http://wiki.shoryuken.com/images/4/47/%28ibukicloselp%29.gif",
        "damage": "25",
        "startup": "2",
        "hit": "2",
        "recovery": "2",
        "block_adv": "+5",
        "hit_adv": "+5"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "http://wiki.shoryuken.com/images/e/ea/%28ibukiclosehp%29.gif",
        "damage": "60+70",
        "startup": "9",
        "hit": "1,4",
        "recovery": "15",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/5/5a/%28ibukilk%29.gif",
        "damage": "20",
        "startup": "4",
        "hit": "4",
        "recovery": "6",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "http://wiki.shoryuken.com/images/9/9b/%28ibukimk%29.gif",
        "damage": "100",
        "startup": "5",
        "hit": "4",
        "recovery": "14",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/5/51/%28ibukihk%29.gif",
        "damage": "110",
        "startup": "9",
        "hit": "3",
        "recovery": "21",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "close.hk",
        "desc": "Close Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/d/df/%28ibukiclosehk%29.gif",
        "damage": "50+70",
        "startup": "5",
        "hit": "1,6",
        "recovery": "22",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/e/e7/%28ibukijlp%29.gif",
        "damage": "60(50 neutral jump)",
        "startup": "3",
        "hit": "19(until land neutral jump)",
        "recovery": "N/A",
        "block_adv": "-4~+7",
        "hit_adv": "-4~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/4/41/%28ibukijmp%29.gif",
        "damage": "80(70 neutral jump)",
        "startup": "6(5 neutral jump)",
        "hit": "13(7 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-1~+10",
        "hit_adv": "-1~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/b/b0/%28ibukijhp%29.gif",
        "damage": "120",
        "startup": "11",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/b/b7/%28ibukijlk%29.gif",
        "damage": "50(40 neutral jump)",
        "startup": "3(4 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-9~+7",
        "hit_adv": "-9~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/7/75/%28ibukijmk%29.gif",
        "damage": "70",
        "startup": "7(5 neutral jump)",
        "hit": "13(7 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-3~+10(-6~+10 neutral jump)",
        "hit_adv": "-3~+10(-6~+10 neutral jump)"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/0/04/%28ibukijhk%29.gif",
        "damage": "110",
        "startup": "11(10 neutral jump)",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/c/c5/%28ibukioh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "b.lp+lk",
        "desc": "Yamitsudzura",
        "pic": "http://wiki.shoryuken.com/images/6/6a/%28ibukigtr%29.gif",
        "damage": "140",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Yamitsudzura",
        "pic": "http://wiki.shoryuken.com/images/6/6a/%28ibukigtr%29.gif",
        "damage": "140",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.lp+lk",
        "desc": "Tobizaru",
        "pic": "http://wiki.shoryuken.com/images/5/59/%28ibukiatr%29.gif",
        "damage": "160",
        "startup": "6",
        "hit": "1",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/f/fb/%28ibukiclp%29.gif",
        "damage": "20",
        "startup": "3",
        "hit": "3",
        "recovery": "3",
        "block_adv": "+5",
        "hit_adv": "+5"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/9/94/%28ibukicmp%29.gif",
        "damage": "70",
        "startup": "9",
        "hit": "7",
        "recovery": "9",
        "block_adv": "+2",
        "hit_adv": "+3"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/e/ea/%28ibukichp%29.gif",
        "damage": "110",
        "startup": "8",
        "hit": "3",
        "recovery": "18",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/4/4d/%28ibukiclk%29.gif",
        "damage": "20",
        "startup": "5",
        "hit": "3",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/d/d2/%28ibukicmk%29.gif",
        "damage": "70",
        "startup": "6",
        "hit": "5",
        "recovery": "11",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/5/56/%28ibukichk%29.gif",
        "damage": "100",
        "startup": "10",
        "hit": "2",
        "recovery": "24",
        "block_adv": "-8",
        "hit_adv": "knd"
    },
    {
        "name": "f.lk",
        "desc": "Maki Geri",
        "pic": "http://wiki.shoryuken.com/images/a/a7/%28ibukiflk%29.gif",
        "damage": "20",
        "startup": "5",
        "hit": "4",
        "recovery": "8",
        "block_adv": "-1",
        "hit_adv": "-1"
    },
     {
        "name": "f.mk",
        "desc": "Koube Kudaki",
        "pic": "http://wiki.shoryuken.com/images/0/0c/%28ibukifmk%29.gif",
        "damage": "80",
        "startup": "27",
        "hit": "3",
        "recovery": "3",
        "block_adv": "+9",
        "hit_adv": "+10"
    },
    {
        "name": "b.mp",
        "desc": "You Men",
        "pic": "http://wiki.shoryuken.com/images/0/02/%28ibukibmp%29.gif",
        "damage": "90",
        "startup": "6",
        "hit": "1,6",
        "recovery": "10",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "b.mk",
        "desc": "Ura Maki Geri",
        "pic": "http://wiki.shoryuken.com/images/c/cc/%28ibukibmk%29.gif",
        "damage": "70",
        "startup": "13",
        "hit": "2",
        "recovery": "13",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "df.mk",
        "desc": "Sazan",
        "pic": "http://wiki.shoryuken.com/images/5/5a/%28ibukidfmk%29.gif",
        "damage": "70",
        "startup": "6",
        "hit": "11",
        "recovery": "9",
        "block_adv": "-16",
        "hit_adv": "-6"
    },
    {
        "name": "hp,hp",
        "desc": "Oiura Ken",
        "pic": "http://wiki.shoryuken.com/images/3/36/%28ibukihphp%29.gif",
        "damage": "80",
        "startup": "2",
        "hit": "3",
        "recovery": "31",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "f.hk",
        "desc": "Bonshou Geri",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28ibukifhk%29.gif",
        "damage": "130",
        "startup": "12",
        "hit": "1",
        "recovery": "20",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "air.qcf.lp",
        "desc": "Kunai (Jab)",
        "pic": "http://wiki.shoryuken.com/images/7/71/%28ibukikunail%29.gif",
        "damage": "50",
        "startup": "8",
        "hit": "1",
        "recovery": "9",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcf.mp",
        "desc": "Kunai (Strong)",
        "pic": "http://wiki.shoryuken.com/images/f/f5/%28ibukikunaim%29.gif",
        "damage": "50",
        "startup": "9",
        "hit": "1",
        "recovery": "11",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcf.hp",
        "desc": "Kunai (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/8/8d/%28ibukikunaih%29.gif",
        "damage": "50",
        "startup": "10",
        "hit": "1",
        "recovery": "14",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "hcb.lp",
        "desc": "Raida (Jab)",
        "pic": "http://wiki.shoryuken.com/images/e/ea/%28ibukiraida%29.gif",
        "damage": "150",
        "startup": "4",
        "hit": "3",
        "recovery": "28",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mp",
        "desc": "Raida (Strong)",
        "pic": "http://wiki.shoryuken.com/images/e/ea/%28ibukiraida%29.gif",
        "damage": "150",
        "startup": "5",
        "hit": "5",
        "recovery": "30",
        "block_adv": "-6",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.hp",
        "desc": "Raida (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/e/ea/%28ibukiraida%29.gif",
        "damage": "150",
        "startup": "6",
        "hit": "7",
        "recovery": "32",
        "block_adv": "-7",
        "hit_adv": "knd"
    },
    {
        "name": "bdp.lk",
        "desc": "Hien (Short)",
        "pic": "http://wiki.shoryuken.com/images/9/92/%28ibukihien%29.gif",
        "damage": "115",
        "startup": "22/25",
        "hit": "3/2",
        "recovery": "13",
        "block_adv": "-31",
        "hit_adv": "-31"
    },
    {
        "name": "bdp.mk",
        "desc": "Hien (Forward)",
        "pic": "http://wiki.shoryuken.com/images/9/92/%28ibukihien%29.gif",
        "damage": "130",
        "startup": "25/29",
        "hit": "3/2",
        "recovery": "13",
        "block_adv": "-38",
        "hit_adv": "-38"
    },
    {
        "name": "bdp.hk",
        "desc": "Hien (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/9/92/%28ibukihien%29.gif",
        "damage": "150",
        "startup": "28/32",
        "hit": "4/2",
        "recovery": "11",
        "block_adv": "-35",
        "hit_adv": "-35"
    },
    {
        "name": "qcb.lk",
        "desc": "Tsumuji (Short)",
        "pic": "http://wiki.shoryuken.com/images/8/81/%28ibukitsumuji%29.gif",
        "damage": "60+50",
        "startup": "11/26",
        "hit": "1/1",
        "recovery": "19/21",
        "block_adv": "-4",
        "hit_adv": "0/+1/knd"
    },
    {
        "name": "qcb.mk",
        "desc": "Tsumuji (Forward)",
        "pic": "http://wiki.shoryuken.com/images/8/81/%28ibukitsumuji%29.gif",
        "damage": "60+50+50",
        "startup": "13/29/45",
        "hit": "1/1/1",
        "recovery": "21/27",
        "block_adv": "-2/-7",
        "hit_adv": "0/knd"
    },
    {
        "name": "qcb.hk",
        "desc": "Tsumuji (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/8/81/%28ibukitsumuji%29.gif",
        "damage": "60+50+80",
        "startup": "14/28/44",
        "hit": "1/1/1",
        "recovery": "24/30",
        "block_adv": "-8",
        "hit_adv": "0/knd"
    },
    {
        "name": "qcf.lp",
        "desc": "Kubiori (Jab)",
        "pic": "http://wiki.shoryuken.com/images/a/a5/%28ibukikbr%29.gif",
        "damage": "150",
        "startup": "14",
        "hit": "11",
        "recovery": "15",
        "block_adv": "-10",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.mp",
        "desc": "Kubiori (Strong)",
        "pic": "http://wiki.shoryuken.com/images/a/a5/%28ibukikbr%29.gif",
        "damage": "150",
        "startup": "15",
        "hit": "12",
        "recovery": "18",
        "block_adv": "-16",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.hp",
        "desc": "Kubiori (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/a/a5/%28ibukikbr%29.gif",
        "damage": "150",
        "startup": "17",
        "hit": "14",
        "recovery": "19",
        "block_adv": "-19",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.lk",
        "desc": "Kasumi Gake",
        "pic": "http://wiki.shoryuken.com/images/b/bd/%28ibukiksmg%29.gif",
        "damage": "N/A",
        "startup": "20/22/25",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "dp.lp",
        "desc": "Tsuiji Goe",
        "pic": "http://wiki.shoryuken.com/images/8/80/%28ibukitjgo%29.gif",
        "damage": "N/A",
        "startup": "42/44/48",
        "hit": "2",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcf.2p",
        "desc": "Kunai (EX)",
        "pic": "http://wiki.shoryuken.com/images/e/ee/%28ibukikunaiex%29.gif",
        "damage": "60+60",
        "startup": "7/9",
        "hit": "1/1",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "dp.2k",
        "desc": "Kazekiri (EX)",
        "pic": "http://wiki.shoryuken.com/images/8/87/%28ibukikkiex%29.gif",
        "damage": "180",
        "startup": "4/5/6/7",
        "hit": "1/1/1/8",
        "recovery": "33",
        "block_adv": "-21",
        "hit_adv": "-15"
    },
    {
        "name": "qcb.2k",
        "desc": "Tsumuji (EX)",
        "pic": "http://wiki.shoryuken.com/images/4/49/%28ibukitsjex%29.gif",
        "damage": "150+70",
        "startup": "7/17/27/38-42",
        "hit": "1/1/1/2",
        "recovery": "28/30",
        "block_adv": "-11/-16",
        "hit_adv": "knd"
    },
    {
        "name": "bdp.2k",
        "desc": "Hien (EX)",
        "pic": "http://wiki.shoryuken.com/images/e/ed/%28ibukihienex%29.gif",
        "damage": "190",
        "startup": "26/30",
        "hit": "4/2",
        "recovery": "11",
        "block_adv": "-30",
        "hit_adv": "-30"
    },
    {
        "name": "qcf.2p",
        "desc": "Kubiori (EX)",
        "pic": "http://wiki.shoryuken.com/images/8/88/%28ibukikubiex%29.gif",
        "damage": "200",
        "startup": "14",
        "hit": "10",
        "recovery": "19",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Kazumi Suzaku",
        "pic": "http://wiki.shoryuken.com/images/6/6f/%28ibukisa1%29.gif",
        "damage": "35x20",
        "startup": "4/6/8",
        "hit": "1/1/1",
        "recovery": "4/6/8",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "sa2",
        "desc": "Yoroi Doushi",
        "pic": "http://wiki.shoryuken.com/images/2/28/%28ibukisa2%29.gif",
        "damage": "435/280",
        "startup": "1",
        "hit": "1",
        "recovery": "65",
        "block_adv": "N/A(-54 far)",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Yami Shigure",
        "pic": "http://wiki.shoryuken.com/images/c/c4/%28ibukisa3%29.gif",
        "damage": "335",
        "startup": "2/3/6",
        "hit": "1",
        "recovery": "32",
        "block_adv": "-10~-6",
        "hit_adv": "knd"
    }
]