ken_frames=[{
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "framedata/img/ke-taunt.gif",
        "damage": "5/5",
        "startup": "15/9",
        "hit": "1/1",
        "recovery": "27",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "framedata/img/ke-lp.gif",
        "damage": "20",
        "startup": "5",
        "hit": "3",
        "recovery": "4",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "framedata/img/ke-mp.gif",
        "damage": "90",
        "startup": "6",
        "hit": "3",
        "recovery": "10",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "framedata/img/ke-hp.gif",
        "damage": "130",
        "startup": "9",
        "hit": "3",
        "recovery": "15",
        "block_adv": "+2",
        "hit_adv": "+4"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "framedata/img/ke-closelp.gif",
        "damage": "20",
        "startup": "3",
        "hit": "3",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "framedata/img/ke-closemp.gif",
        "damage": "100",
        "startup": "4",
        "hit": "4",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "framedata/img/ke-closehp.gif",
        "damage": "130",
        "startup": "6",
        "hit": "3",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "framedata/img/ke-lk.gif",
        "damage": "40",
        "startup": "4",
        "hit": "4",
        "recovery": "7",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "framedata/img/ke-mk.gif",
        "damage": "110",
        "startup": "8",
        "hit": "7",
        "recovery": "16",
        "block_adv": "-6",
        "hit_adv": "-2"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "framedata/img/ke-hk.gif",
        "damage": "150",
        "startup": "11",
        "hit": "6",
        "recovery": "19",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "framedata/img/ke-alp.gif",
        "damage": "50",
        "startup": "4(5 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "framedata/img/ke-amp.gif",
        "damage": "100",
        "startup": "5(6 neutral jump)",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "framedata/img/ke-ahp.gif",
        "damage": "130",
        "startup": "6(7 neutral jump)",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "+3~+13",
        "hit_adv": "+3~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "framedata/img/ke-alk.gif",
        "damage": "50",
        "startup": "4(5 neutral jump)",
        "hit": "10(19 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-8~+7",
        "hit_adv": "-8~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "framedata/img/ke-amk.gif",
        "damage": "90",
        "startup": "5",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "-6~10",
        "hit_adv": "-6~10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "framedata/img/ke-ahk.gif",
        "damage": "125(130 neutral jump)",
        "startup": "6(7 neutral jump)",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "framedata/img/ke-overhead.gif",
        "damage": "40",
        "startup": "15",
        "hit": "8",
        "recovery": "7",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hiza Geri",
        "pic": "framedata/img/ke-throw.gif",
        "damage": "160",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Seoi Nage",
        "pic": "framedata/img/ke-fthrow.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Jigoku Guruma",
        "pic": "framedata/img/ke-bthrow.gif",
        "damage": "110",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "framedata/img/ke-clp.gif",
        "damage": "20",
        "startup": "4",
        "hit": "3",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "framedata/img/ke-cmp.gif",
        "damage": "90",
        "startup": "5",
        "hit": "4",
        "recovery": "7",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "framedata/img/ke-chp.gif",
        "damage": "130",
        "startup": "7",
        "hit": "5",
        "recovery": "17",
        "block_adv": "-8",
        "hit_adv": "-6"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "framedata/img/ke-clk.gif",
        "damage": "20",
        "startup": "5",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "framedata/img/ke-cmk.gif",
        "damage": "85",
        "startup": "6",
        "hit": "5",
        "recovery": "17",
        "block_adv": "-3",
        "hit_adv": "-3"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "framedata/img/ke-chk.gif",
        "damage": "130",
        "startup": "5",
        "hit": "5",
        "recovery": "26",
        "block_adv": "-13",
        "hit_adv": "knd"
    },
    {
        "name": "f.mk",
        "desc": "Fumikomi Mae Geri",
        "pic": "framedata/img/ke-fmk.gif",
        "damage": "80",
        "startup": "16",
        "hit": "4",
        "recovery": "15",
        "block_adv": "-4",
        "hit_adv": "-1"
    },
    {
        "name": "b.mk",
        "desc": "Inazuma Kakato Wari",
        "pic": "framedata/img/ke-bmk.gif",
        "damage": "130",
        "startup": "8",
        "hit": "2/2",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "f.hk",
        "desc": "Shiden Kakato Otoshi",
        "pic": "framedata/img/ke-fhk.gif",
        "damage": "120",
        "startup": "30",
        "hit": "5",
        "recovery": "14(18 on fake)",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "hold.mk",
        "desc": "Inazuma Kakato Wari",
        "pic": "framedata/img/ke-mk.gif",
        "damage": "110/130",
        "startup": "8/25",
        "hit": "7/2/2",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "qcf.lp",
        "desc": "Hadouken",
        "pic": "framedata/img/ke-qcfp.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-11",
        "hit_adv": "-10"
    },
    {
        "name": "qcf.mp",
        "desc": "Hadouken",
        "pic": "framedata/img/ke-qcfp.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-11",
        "hit_adv": "-10"
    },
    {
        "name": "qcf.hp",
        "desc": "Hadouken",
        "pic": "framedata/img/ke-qcfp.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-11",
        "hit_adv": "-10"
    },
    {
        "name": "qcf.2p",
        "desc": "Hadouken (EX)",
        "pic": "framedata/img/ke-qcfp.gif",
        "damage": "60+60",
        "startup": "10",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-6",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lp",
        "desc": "Shoryuken (Jab)",
        "pic": "framedata/img/ke-dp.gif",
        "damage": "150",
        "startup": "2",
        "hit": "8",
        "recovery": "26",
        "block_adv": "-17",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mp",
        "desc": "Shoryuken (Strong)",
        "pic": "framedata/img/ke-dp.gif",
        "damage": "165",
        "startup": "3",
        "hit": "2/12",
        "recovery": "28",
        "block_adv": "-24",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Shoryuken (Fierce)",
        "pic": "framedata/img/ke-dp.gif",
        "damage": "185",
        "startup": "1",
        "hit": "2/2/7",
        "recovery": "32",
        "block_adv": "-31",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2p",
        "desc": "Shoryuken (EX)",
        "pic": "framedata/img/ke-dp.gif",
        "damage": "80+50+40+40",
        "startup": "1",
        "hit": "2/2/2/14",
        "recovery": "38",
        "block_adv": "-36",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lk",
        "desc": "Tatsumaki Senpuu Kyaku (Short)",
        "pic": "framedata/img/ke-qcbk.gif",
        "damage": "80+30",
        "startup": "6+16+22",
        "hit": "2+3+2",
        "recovery": "14",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "qcb.mk",
        "desc": "Tatsumaki Senpuu Kyaku (Forward)",
        "pic": "framedata/img/ke-qcbk.gif",
        "damage": "60+30(x3)",
        "startup": "6-37",
        "hit": "2x7",
        "recovery": "15",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "qcb.hk",
        "desc": "Tatsumaki Senpuu Kyaku (Roundhouse)",
        "pic": "framedata/img/ke-qcbk.gif",
        "damage": "60+30(x4)",
        "startup": "6-48",
        "hit": "2x9",
        "recovery": "15",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "qcb.2k",
        "desc": "Tatsumaki Senpuu Kyaku (EX)",
        "pic": "framedata/img/ke-qcbk.gif",
        "damage": "200",
        "startup": "4-48",
        "hit": "2x11",
        "recovery": "13",
        "block_adv": "-3",
        "hit_adv": "-1 "
    },
   {
        "name": "air.qcb.lk",
        "desc": "Air Tatsumaki Senpuu Kyaku (Short)",
        "pic": "framedata/img/ke-qcbk.gif",
        "damage": "160",
        "startup": "7-18",
        "hit": "1x4",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.mk",
        "desc": "Air Tatsumaki Senpuu Kyaku (Forward)",
        "pic": "framedata/img/ke-qcbk.gif",
        "damage": "160",
        "startup": "7-26",
        "hit": "1x6",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.hk",
        "desc": "Air Tatsumaki Senpuu Kyaku (Roundhouse)",
        "pic": "framedata/img/ke-qcbk.gif",
        "damage": "160",
        "startup": "7-34",
        "hit": "1x8",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.2k",
        "desc": "Air Tatsumaki Senpuu Kyaku (EX)",
        "pic": "framedata/img/ke-qcbk.gif",
        "damage": "240",
        "startup": "6-42",
        "hit": "1x13",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Shoryureppa",
        "pic": "framedata/img/ke-sa1.gif",
        "damage": "400",
        "startup": "1",
        "hit": "1",
        "recovery": "11",
        "block_adv": "-38",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Shinryuken",
        "pic": "framedata/img/ke-sa2.gif",
        "damage": "495",
        "startup": "2",
        "hit": "2",
        "recovery": "61",
        "block_adv": "-80",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Shippu Jinrai Kyaku",
        "pic": "framedata/img/ke-sa3.gif",
        "damage": "290",
        "startup": "2",
        "hit": "2",
        "recovery": "27",
        "block_adv": "-11",
        "hit_adv": "knd"
    }]