makoto_frames=[{
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "framedata/img/ma-taunt.gif",
        "damage": "10",
        "startup": "79",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "framedata/img/ma-lp.gif",
        "damage": "30",
        "startup": "4",
        "hit": "6",
        "recovery": "6",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "framedata/img/ma-mp.gif",
        "damage": "80",
        "startup": "8",
        "hit": "11",
        "recovery": "4",
        "block_adv": "+6",
        "hit_adv": "+7"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "framedata/img/ma-hp.gif",
        "damage": "120",
        "startup": "8",
        "hit": "2",
        "recovery": "22",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "framedata/img/ma-lk.gif",
        "damage": "40",
        "startup": "4",
        "hit": "5",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "-2"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "framedata/img/ma-mk.gif",
        "damage": "90",
        "startup": "7",
        "hit": "5",
        "recovery": "13",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "framedata/img/ma-hk.gif",
        "damage": "130",
        "startup": "11",
        "hit": "9",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "+2"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "framedata/img/ma-alp.gif",
        "damage": "50",
        "startup": "4(9 neutral jump)",
        "hit": "21(17 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-9~+7(-2~+7 neutral jump)",
        "hit_adv": "-9~+7(-2~+7 neutral jump)"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "framedata/img/ma-amp.gif",
        "damage": "80",
        "startup": "11",
        "hit": "24(6 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-3~+10(+2~+10 neutral jump)",
        "hit_adv": "-3~+10(+2~+10 neutral jump)"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "framedata/img/ma-ahp.gif",
        "damage": "130",
        "startup": "10(13 neutral jump)",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "+1~+13(+7~+13 neutral jump)",
        "hit_adv": "+1~+13(+7~+13 neutral jump)"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "framedata/img/ma-alk.gif",
        "damage": "60",
        "startup": "2",
        "hit": "14",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "framedata/img/ma-amk.gif",
        "damage": "90",
        "startup": "7",
        "hit": "13",
        "recovery": "N/A",
        "block_adv": "-5~+10",
        "hit_adv": "-5~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "framedata/img/ma-ahk.gif",
        "damage": "130",
        "startup": "6",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "+4~+13",
        "hit_adv": "+4~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "framedata/img/ma-overhead.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hikiyose Zutsuki (Tacchuu)",
        "pic": "framedata/img/ma-throw.gif",
        "damage": "90",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Hiji Otoshi Sanren Tsuki (Araiso)",
        "pic": "framedata/img/ma-fthrow.gif",
        "damage": "150",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Hiji Otoshi Sanren Tsuki (Araiso)",
        "pic": "framedata/img/ma-fthrow.gif",
        "damage": "150",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "framedata/img/ma-clp.gif",
        "damage": "20",
        "startup": "5",
        "hit": "4",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "framedata/img/ma-cmp.gif",
        "damage": "70",
        "startup": "7",
        "hit": "7",
        "recovery": "11",
        "block_adv": "-1",
        "hit_adv": "0"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "framedata/img/ma-chp.gif",
        "damage": "130",
        "startup": "10",
        "hit": "2",
        "recovery": "21",
        "block_adv": "-8",
        "hit_adv": "knd"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "framedata/img/ma-clk.gif",
        "damage": "40",
        "startup": "4",
        "hit": "6",
        "recovery": "10",
        "block_adv": "-3",
        "hit_adv": "-3"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "framedata/img/ma-cmk.gif",
        "damage": "90",
        "startup": "7",
        "hit": "8",
        "recovery": "7",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "framedata/img/ma-chk.gif",
        "damage": "130",
        "startup": "10",
        "hit": "4",
        "recovery": "12",
        "block_adv": "+2",
        "hit_adv": "+4"
    },
    {
        "name": "f.lp",
        "desc": "Kazami",
        "pic": "framedata/img/ma-flp.gif",
        "damage": "25",
        "startup": "4",
        "hit": "4",
        "recovery": "8",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "f.mp",
        "desc": "Kaoruna",
        "pic": "framedata/img/ma-fmp.gif",
        "damage": "85",
        "startup": "9",
        "hit": "6",
        "recovery": "9",
        "block_adv": "+2",
        "hit_adv": "+3"
    },
    {
        "name": "f.hp",
        "desc": "Shikami",
        "pic": "framedata/img/ma-fhp.gif",
        "damage": "150",
        "startup": "16",
        "hit": "4,15",
        "recovery": "13",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "f.lk",
        "desc": "Shinbuki",
        "pic": "framedata/img/ma-flk.gif",
        "damage": "350",
        "startup": "6",
        "hit": "6",
        "recovery": "13",
        "block_adv": "-5",
        "hit_adv": "-5"
    },
    {
        "name": "f.mk",
        "desc": "Naruto",
        "pic": "framedata/img/ma-fmk.gif",
        "damage": "100",
        "startup": "17",
        "hit": "5",
        "recovery": "18",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "f.hk",
        "desc": "Kurushio",
        "pic": "framedata/img/ma-fhk.gif",
        "damage": "120",
        "startup": "22",
        "hit": "3",
        "recovery": "25",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.lp",
        "desc": "Hayate (Jab)",
        "pic": "framedata/img/ma-qcfp.gif",
        "damage": "100",
        "startup": "6",
        "hit": "6",
        "recovery": "12",
        "block_adv": "-12",
        "hit_adv": "+2"
    },
    {
        "name": "qcf.mp",
        "desc": "Hayate (Strong)",
        "pic": "framedata/img/ma-qcfp.gif",
        "damage": "100",
        "startup": "9",
        "hit": "6",
        "recovery": "12",
        "block_adv": "-12",
        "hit_adv": "+2"
    },
    {
        "name": "qcf.hp",
        "desc": "Hayate (Fierce)",
        "pic": "framedata/img/ma-qcfp.gif",
        "damage": "100",
        "startup": "11",
        "hit": "6",
        "recovery": "12",
        "block_adv": "-12",
        "hit_adv": "+2"
    },
    {
        "name": "hold.qcf.lp",
        "desc": "Hayate (Levels 1-4)",
        "pic": "framedata/img/ma-qcfp.gif",
        "damage": "110,120,130,140",
        "startup": "7-26, 27-46,47-66,67-126",
        "hit": "6",
        "recovery": "11,10,10,8",
        "block_adv": "-9, -6, -2, +2",
        "hit_adv": "+2, +2, knd, knd"
    },
    {
        "name": "qcf.2p",
        "desc": "Hayate (EX)",
        "pic": "framedata/img/ma-qcfp.gif",
        "damage": "160",
        "startup": "17",
        "hit": "1",
        "recovery": "8/12",
        "block_adv": "+2",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lp",
        "desc": "Fukiage (Jab)",
        "pic": "framedata/img/ma-dp.gif",
        "damage": "120",
        "startup": "7",
        "hit": "8",
        "recovery": "26",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mp",
        "desc": "Fukiage (Strong)",
        "pic": "framedata/img/ma-dp.gif",
        "damage": "140",
        "startup": "10",
        "hit": "8",
        "recovery": "26",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Fukiage (Fierce)",
        "pic": "framedata/img/ma-dp.gif",
        "damage": "140",
        "startup": "10",
        "hit": "7",
        "recovery": "26",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2p",
        "desc": "Fukiage (EX)",
        "pic": "framedata/img/ma-dp.gif",
        "damage": "140",
        "startup": "11",
        "hit": "8",
        "recovery": "17/26",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lp",
        "desc": "Oroshi (Jab)",
        "pic": "framedata/img/ma-qcbp.gif",
        "damage": "100",
        "startup": "19",
        "hit": "7",
        "recovery": "17",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "qcb.mp",
        "desc": "Oroshi (Strong)",
        "pic": "framedata/img/ma-qcbp.gif",
        "damage": "110",
        "startup": "23",
        "hit": "7",
        "recovery": "17",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "qcb.hp",
        "desc": "Oroshi (Fierce)",
        "pic": "framedata/img/ma-qcbp.gif",
        "damage": "100",
        "startup": "28",
        "hit": "7",
        "recovery": "17",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2p",
        "desc": "Oroshi (EX)",
        "pic": "framedata/img/ma-qcbp.gif",
        "damage": "160",
        "startup": "13",
        "hit": "7",
        "recovery": "17",
        "block_adv": "+3~+9",
        "hit_adv": "knd"
    },
   {
        "name": "hcb.lk",
        "desc": "Karakusa (Short)",
        "pic": "framedata/img/ma-hcbk.gif",
        "damage": "30",
        "startup": "7",
        "hit": "3",
        "recovery": "28",
        "block_adv": "N/A",
        "hit_adv": "+14"
    },
    {
        "name": "hcb.mk",
        "desc": "Karakusa (Forward)",
        "pic": "framedata/img/ma-hcbk.gif",
        "damage": "30",
        "startup": "8",
        "hit": "4",
        "recovery": "29",
        "block_adv": "N/A",
        "hit_adv": "+14"
    },
    {
        "name": "hcb.hk",
        "desc": "Karakusa (Roundhouse)",
        "pic": "framedata/img/ma-hcbk.gif",
        "damage": "30",
        "startup": "9",
        "hit": "4",
        "recovery": "30",
        "block_adv": "N/A",
        "hit_adv": "+14"
    },
    {
        "name": "air.qcb.lk",
        "desc": "Tsurugi (Short)",
        "pic": "framedata/img/ma-aqcbk.gif",
        "damage": "140",
        "startup": "7",
        "hit": "1",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.mk",
        "desc": "Tsurugi (Forward)",
        "pic": "framedata/img/ma-aqcbk.gif",
        "damage": "150",
        "startup": "7",
        "hit": "1",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.hk",
        "desc": "Tsurugi (Roundhouse)",
        "pic": "framedata/img/ma-aqcbk.gif",
        "damage": "160",
        "startup": "7",
        "hit": "1",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.2k",
        "desc": "Tsurugi (EX)",
        "pic": "framedata/img/ma-aqcbk.gif",
        "damage": "80+100",
        "startup": "15+17",
        "hit": "2+2",
        "recovery": "8",
        "block_adv": "+2~+9",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Seichu Sen Godanzuki",
        "pic": "framedata/img/ma-sa1.gif",
        "damage": "500",
        "startup": "1",
        "hit": "3",
        "recovery": "133/65 far/71 parry",
        "block_adv": "-17",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Abare To Sadami Kudaki",
        "pic": "framedata/img/ma-sa2.gif",
        "damage": "360",
        "startup": "14~18",
        "hit": "5/6/9",
        "recovery": "6/25 far/32 parry",
        "block_adv": "-20",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Tanden Renki-Seme no Kata",
        "pic": "framedata/img/ma-sa3.gif",
        "damage": "N/A",
        "startup": "2",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    }]