necro_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/5/5f/%28necrot%29.gif",
        "damage": "10x2",
        "startup": "21",
        "hit": "6",
        "recovery": "23",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/4/4c/%28necrolp%29.gif",
        "damage": "30",
        "startup": "5",
        "hit": "1",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/4/41/%28necromp%29.gif",
        "damage": "50",
        "startup": "8",
        "hit": "1",
        "recovery": "12",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/f/f2/%28necrohp%29.gif",
        "damage": "100",
        "startup": "15",
        "hit": "11",
        "recovery": "28",
        "block_adv": "-13",
        "hit_adv": "-11"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28necrolk%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "1",
        "recovery": "97",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "http://wiki.shoryuken.com/images/3/33/%28necromk%29.gif",
        "damage": "70",
        "startup": "9",
        "hit": "1",
        "recovery": "14",
        "block_adv": "-1",
        "hit_adv": "0"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/4/4a/%28necrohk%29.gif",
        "damage": "110",
        "startup": "18",
        "hit": "1",
        "recovery": "24",
        "block_adv": "-8",
        "hit_adv": "-6"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/2/26/%28necrojlp%29.gif",
        "damage": "40",
        "startup": "4(5 neutral jump)",
        "hit": "14(6 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-12~+7",
        "hit_adv": "-12~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/c/c1/%28necrojmp%29.gif",
        "damage": "80(70 neutral jump)",
        "startup": "9(8 neutral jump)",
        "hit": "1",
        "recovery": "N/A",
        "block_adv": "-8~+10",
        "hit_adv": "-8~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/0/0e/%28necrojhp%29.gif",
        "damage": "100",
        "startup": "13",
        "hit": "2",
        "recovery": "N/A",
        "block_adv": "+1~+13",
        "hit_adv": "+1~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/e/eb/%28necrojlk%29.gif",
        "damage": "30",
        "startup": "2",
        "hit": "15",
        "recovery": "N/A",
        "block_adv": "-6~+7",
        "hit_adv": "-6~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/4/44/%28necrojmk%29.gif",
        "damage": "90",
        "startup": "10",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "+4~+10",
        "hit_adv": "+4~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/b/b9/%28necrojhk%29.gif",
        "damage": "120",
        "startup": "15",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/6/66/%28necrooh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Shoulder Attack",
        "pic": "http://wiki.shoryuken.com/images/5/5c/%28necroshat%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Shoulder Attack",
        "pic": "http://wiki.shoryuken.com/images/5/5c/%28necroshat%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Frankensteiner/ German Suplex (back turned)",
        "pic": "http://wiki.shoryuken.com/images/d/db/%28necrofrank%29.gif",
        "damage": "100/200",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp",
        "desc": "Back Jab",
        "pic": "http://wiki.shoryuken.com/images/0/0b/%28necroblp%29.gif",
        "damage": "50",
        "startup": "3",
        "hit": "1",
        "recovery": "6",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "b.mp",
        "desc": "Back Strong",
        "pic": "http://wiki.shoryuken.com/images/a/ad/%28necrobmp%29.gif",
        "damage": "70",
        "startup": "4",
        "hit": "2",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "b.hp",
        "desc": "Back Fierce",
        "pic": "http://wiki.shoryuken.com/images/5/51/%28necrobhp%29.gif",
        "damage": "130",
        "startup": "11",
        "hit": "4",
        "recovery": "15",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "b.lk",
        "desc": "Back Short",
        "pic": "http://wiki.shoryuken.com/images/a/a5/%28necroblk%29.gif",
        "damage": "45",
        "startup": "3",
        "hit": "2",
        "recovery": "7",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "b.mk",
        "desc": "Back Forward",
        "pic": "http://wiki.shoryuken.com/images/3/36/%28necrobmk%29.gif",
        "damage": "80",
        "startup": "5",
        "hit": "1",
        "recovery": "10",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "b.hk",
        "desc": "Back Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/1/12/%28necrobhk%29.gif",
        "damage": "140",
        "startup": "12",
        "hit": "1",
        "recovery": "16",
        "block_adv": "+10",
        "hit_adv": "+12"
    },
    {
        "name": "air.d.lk",
        "desc": "Short Drill Kick",
        "pic": "http://wiki.shoryuken.com/images/1/1f/%28necrojdlk%29.gif",
        "damage": "50+15",
        "startup": "9,6",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-23~+5",
        "hit_adv": "-23~+5"
    },
    {
        "name": "air.d.mk",
        "desc": "Forward Drill Kick",
        "pic": "http://wiki.shoryuken.com/images/3/36/%28necrojdmk%29.gif",
        "damage": "60+20",
        "startup": "9,6",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-14~+7",
        "hit_adv": "-14~+7"
    },
    {
        "name": "air.d.hk",
        "desc": "Roundhouse Drill Kick",
        "pic": "http://wiki.shoryuken.com/images/6/65/%28necrojdhk%29.gif",
        "damage": "80+20",
        "startup": "9,6",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-17~+9",
        "hit_adv": "-17~+9"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/7/72/%28necroclp%29.gif",
        "damage": "30",
        "startup": "6",
        "hit": "1",
        "recovery": "4",
        "block_adv": "+5",
        "hit_adv": "+5"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/8/82/%28necrocmp%29.gif",
        "damage": "60",
        "startup": "8",
        "hit": "1",
        "recovery": "12",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28necrochp%29.gif",
        "damage": "90",
        "startup": "8",
        "hit": "1",
        "recovery": "12",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/b/b4/%28necroclk%29.gif",
        "damage": "35",
        "startup": "6",
        "hit": "1",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/3/3a/%28necrocmk%29.gif",
        "damage": "60",
        "startup": "12",
        "hit": "1",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/b/b9/%28necrochk%29.gif",
        "damage": "100",
        "startup": "13",
        "hit": "1",
        "recovery": "26",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.lp",
        "desc": "Tornado Hook (Jab)",
        "pic": "http://wiki.shoryuken.com/images/1/1a/%28necrothk%29.gif",
        "damage": "50+70",
        "startup": "6/17",
        "hit": "4/4",
        "recovery": "13",
        "block_adv": "+1",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.mp",
        "desc": "Tornado Hook (Strong)",
        "pic": "http://wiki.shoryuken.com/images/1/1a/%28necrothk%29.gif",
        "damage": "50+80",
        "startup": "10/22",
        "hit": "3/4",
        "recovery": "18",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "hcf.hp",
        "desc": "Tornado Hook (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/1/1a/%28necrothk%29.gif",
        "damage": "50+50+80",
        "startup": "17/33/45",
        "hit": "4/3/4",
        "recovery": "17hit/19far/34guard",
        "block_adv": "-18",
        "hit_adv": "+15"
    },
    {
        "name": "qcb.lp",
        "desc": "Flying Viper (Jab)",
        "pic": "http://wiki.shoryuken.com/images/4/4e/%28necrofvi%29.gif",
        "damage": "120",
        "startup": "26",
        "hit": "5",
        "recovery": "17",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.mp",
        "desc": "Flying Viper (Strong)",
        "pic": "http://wiki.shoryuken.com/images/4/4e/%28necrofvi%29.gif",
        "damage": "140",
        "startup": "26",
        "hit": "6",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.hp",
        "desc": "Flying Viper (Strong)",
        "pic": "http://wiki.shoryuken.com/images/4/4e/%28necrofvi%29.gif",
        "damage": "160",
        "startup": "26",
        "hit": "7",
        "recovery": "14",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lk",
        "desc": "Rising Cobra (Short)",
        "pic": "http://wiki.shoryuken.com/images/8/89/%28necrorsc%29.gif",
        "damage": "130",
        "startup": "23",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.mk",
        "desc": "Rising Cobra (Forward)",
        "pic": "http://wiki.shoryuken.com/images/8/89/%28necrorsc%29.gif",
        "damage": "150",
        "startup": "25",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.hk",
        "desc": "Rising Cobra (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/8/89/%28necrorsc%29.gif",
        "damage": "170",
        "startup": "27",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lp",
        "desc": "Denji Blast (Jab)",
        "pic": "http://wiki.shoryuken.com/images/9/93/%28necrodjbl%29.gif",
        "damage": "60",
        "startup": "6/11/16",
        "hit": "2",
        "recovery": "16",
        "block_adv": "-10",
        "hit_adv": "0"
    },
    {
        "name": "dp.mp",
        "desc": "Denji Blast (Strong)",
        "pic": "http://wiki.shoryuken.com/images/9/93/%28necrodjbl%29.gif",
        "damage": "60x3",
        "startup": "8/10/14",
        "hit": "2",
        "recovery": "33",
        "block_adv": "-26",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Denji Blast (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/9/93/%28necrodjbl%29.gif",
        "damage": "60x5",
        "startup": "10/12/14/16/18",
        "hit": "2",
        "recovery": "35",
        "block_adv": "-24",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.lk",
        "desc": "Snake Fang/ German Suplex (Short)",
        "pic": "http://wiki.shoryuken.com/images/2/20/%28necrosnkf%29.gif",
        "damage": "140/200",
        "startup": "12/6",
        "hit": "1/2",
        "recovery": "28/14",
        "block_adv": "-13",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.mk",
        "desc": "Snake Fang/ German Suplex (Forward)",
        "pic": "http://wiki.shoryuken.com/images/2/20/%28necrosnkf%29.gif",
        "damage": "150/240",
        "startup": "12/6",
        "hit": "1/2",
        "recovery": "30/15",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.hk",
        "desc": "Snake Fang/ German Suplex (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/2/20/%28necrosnkf%29.gif",
        "damage": "160/280",
        "startup": "12/6",
        "hit": "1/2",
        "recovery": "32/15",
        "block_adv": "-17",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.2p",
        "desc": "Tornado Hook (EX)",
        "pic": "http://wiki.shoryuken.com/images/e/ef/%28necrothkex%29.gif",
        "damage": "50x5",
        "startup": "8/21/31/41/52",
        "hit": "4/3/3/3/4",
        "recovery": "21/23guard/23far",
        "block_adv": "-9",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2p",
        "desc": "Flying Viper (EX)",
        "pic": "http://wiki.shoryuken.com/images/d/de/%28necrofvex%29.gif",
        "damage": "80+120",
        "startup": "24/28",
        "hit": "5/4",
        "recovery": "10",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "qcb.2k",
        "desc": "Rising Cobra (EX)",
        "pic": "http://wiki.shoryuken.com/images/5/5d/%28necrorsex%29.gif",
        "damage": "100+110",
        "startup": "25/27",
        "hit": "2/2",
        "recovery": "17",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Magnetic Storm",
        "pic": "http://wiki.shoryuken.com/images/8/83/%28necrosa1%29.gif",
        "damage": "370",
        "startup": "2",
        "hit": "4+(3+3)x5+8",
        "recovery": "22",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Slam Dance",
        "pic": "http://wiki.shoryuken.com/images/d/d1/%28necrosa2%29.gif",
        "damage": "470",
        "startup": "3",
        "hit": "6",
        "recovery": "8",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Electric Snake",
        "pic": "http://wiki.shoryuken.com/images/0/0d/%28necrosa3%29.gif",
        "damage": "280",
        "startup": "3/11/21",
        "hit": "3",
        "recovery": "39",
        "block_adv": "-11",
        "hit_adv": "knd"
    }
]