necro_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "framedata/img/ne-taunt.gif",
        "damage": "10x2",
        "startup": "21",
        "hit": "6",
        "recovery": "23",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "framedata/img/ne-lp.gif",
        "damage": "30",
        "startup": "5",
        "hit": "1",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "framedata/img/ne-mp.gif",
        "damage": "50",
        "startup": "8",
        "hit": "1",
        "recovery": "12",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "framedata/img/ne-hp.gif",
        "damage": "100",
        "startup": "15",
        "hit": "11",
        "recovery": "28",
        "block_adv": "-13",
        "hit_adv": "-11"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "framedata/img/ne-lk.gif",
        "damage": "40",
        "startup": "4",
        "hit": "1",
        "recovery": "97",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "framedata/img/ne-mk.gif",
        "damage": "70",
        "startup": "9",
        "hit": "1",
        "recovery": "14",
        "block_adv": "-1",
        "hit_adv": "0"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "framedata/img/ne-hk.gif",
        "damage": "110",
        "startup": "18",
        "hit": "1",
        "recovery": "24",
        "block_adv": "-8",
        "hit_adv": "-6"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "framedata/img/ne-alp.gif",
        "damage": "40",
        "startup": "4(5 neutral jump)",
        "hit": "14(6 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-12~+7",
        "hit_adv": "-12~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "framedata/img/ne-amp.gif",
        "damage": "80(70 neutral jump)",
        "startup": "9(8 neutral jump)",
        "hit": "1",
        "recovery": "N/A",
        "block_adv": "-8~+10",
        "hit_adv": "-8~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "framedata/img/ne-ahp.gif",
        "damage": "100",
        "startup": "13",
        "hit": "2",
        "recovery": "N/A",
        "block_adv": "+1~+13",
        "hit_adv": "+1~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "framedata/img/ne-alk.gif",
        "damage": "30",
        "startup": "2",
        "hit": "15",
        "recovery": "N/A",
        "block_adv": "-6~+7",
        "hit_adv": "-6~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "framedata/img/ne-amk.gif",
        "damage": "90",
        "startup": "10",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "+4~+10",
        "hit_adv": "+4~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "framedata/img/ne-ahk.gif",
        "damage": "120",
        "startup": "15",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "framedata/img/ne-overhead.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Shoulder Attack",
        "pic": "framedata/img/ne-throw.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Shoulder Attack",
        "pic": "framedata/img/ne-throw.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Frankensteiner/ German Suplex (back turned)",
        "pic": "framedata/img/ne-bthrow.gif",
        "damage": "100/200",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp",
        "desc": "Back Jab",
        "pic": "framedata/img/ne-blp.gif",
        "damage": "50",
        "startup": "3",
        "hit": "1",
        "recovery": "6",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "b.mp",
        "desc": "Back Strong",
        "pic": "framedata/img/ne-bmp.gif",
        "damage": "70",
        "startup": "4",
        "hit": "2",
        "recovery": "10",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "b.hp",
        "desc": "Back Fierce",
        "pic": "framedata/img/ne-bhp.gif",
        "damage": "130",
        "startup": "11",
        "hit": "4",
        "recovery": "15",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "b.lk",
        "desc": "Back Short",
        "pic": "framedata/img/ne-blk.gif",
        "damage": "45",
        "startup": "3",
        "hit": "2",
        "recovery": "7",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "b.mk",
        "desc": "Back Forward",
        "pic": "framedata/img/ne-bmk.gif",
        "damage": "80",
        "startup": "5",
        "hit": "1",
        "recovery": "10",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "b.hk",
        "desc": "Back Roundhouse",
        "pic": "framedata/img/ne-bhk.gif",
        "damage": "140",
        "startup": "12",
        "hit": "1",
        "recovery": "16",
        "block_adv": "+10",
        "hit_adv": "+12"
    },
    {
        "name": "air.d.lk",
        "desc": "Short Drill Kick",
        "pic": "framedata/img/ne-adlk.gif",
        "damage": "50+15",
        "startup": "9,6",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-23~+5",
        "hit_adv": "-23~+5"
    },
    {
        "name": "air.d.mk",
        "desc": "Forward Drill Kick",
        "pic": "framedata/img/ne-admk.gif",
        "damage": "60+20",
        "startup": "9,6",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-14~+7",
        "hit_adv": "-14~+7"
    },
    {
        "name": "air.d.hk",
        "desc": "Roundhouse Drill Kick",
        "pic": "framedata/img/ne-adhk.gif",
        "damage": "80+20",
        "startup": "9,6",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-17~+9",
        "hit_adv": "-17~+9"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "framedata/img/ne-clp.gif",
        "damage": "30",
        "startup": "6",
        "hit": "1",
        "recovery": "4",
        "block_adv": "+5",
        "hit_adv": "+5"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "framedata/img/ne-cmp.gif",
        "damage": "60",
        "startup": "8",
        "hit": "1",
        "recovery": "12",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "framedata/img/ne-chp.gif",
        "damage": "90",
        "startup": "8",
        "hit": "1",
        "recovery": "12",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "framedata/img/ne-clk.gif",
        "damage": "35",
        "startup": "6",
        "hit": "1",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "framedata/img/ne-cmk.gif",
        "damage": "60",
        "startup": "12",
        "hit": "1",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "framedata/img/ne-chk.gif",
        "damage": "100",
        "startup": "13",
        "hit": "1",
        "recovery": "26",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.lp",
        "desc": "Tornado Hook (Jab)",
        "pic": "framedata/img/ne-hcfp.gif",
        "damage": "50+70",
        "startup": "6/17",
        "hit": "4/4",
        "recovery": "13",
        "block_adv": "+1",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.mp",
        "desc": "Tornado Hook (Strong)",
        "pic": "framedata/img/ne-hcfp.gif",
        "damage": "50+80",
        "startup": "10/22",
        "hit": "3/4",
        "recovery": "18",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "hcf.hp",
        "desc": "Tornado Hook (Fierce)",
        "pic": "framedata/img/ne-hcfp.gif",
        "damage": "50+50+80",
        "startup": "17/33/45",
        "hit": "4/3/4",
        "recovery": "17hit/19far/34guard",
        "block_adv": "-18",
        "hit_adv": "+15"
    },
    {
        "name": "qcb.lp",
        "desc": "Flying Viper (Jab)",
        "pic": "framedata/img/ne-qcbp.gif",
        "damage": "120",
        "startup": "26",
        "hit": "5",
        "recovery": "17",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.mp",
        "desc": "Flying Viper (Strong)",
        "pic": "framedata/img/ne-qcbp.gif",
        "damage": "140",
        "startup": "26",
        "hit": "6",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.hp",
        "desc": "Flying Viper (Strong)",
        "pic": "framedata/img/ne-qcbp.gif",
        "damage": "160",
        "startup": "26",
        "hit": "7",
        "recovery": "14",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lk",
        "desc": "Rising Cobra (Short)",
        "pic": "framedata/img/ne-qcbk.gif",
        "damage": "130",
        "startup": "23",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.mk",
        "desc": "Rising Cobra (Forward)",
        "pic": "framedata/img/ne-qcbk.gif",
        "damage": "150",
        "startup": "25",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.hk",
        "desc": "Rising Cobra (Roundhouse)",
        "pic": "framedata/img/ne-qcbk.gif",
        "damage": "170",
        "startup": "27",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lp",
        "desc": "Denji Blast (Jab)",
        "pic": "framedata/img/ne-dp.gif",
        "damage": "60",
        "startup": "6/11/16",
        "hit": "2",
        "recovery": "16",
        "block_adv": "-10",
        "hit_adv": "0"
    },
    {
        "name": "dp.mp",
        "desc": "Denji Blast (Strong)",
        "pic": "framedata/img/ne-dp.gif",
        "damage": "60x3",
        "startup": "8/10/14",
        "hit": "2",
        "recovery": "33",
        "block_adv": "-26",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Denji Blast (Fierce)",
        "pic": "framedata/img/ne-dp.gif",
        "damage": "60x5",
        "startup": "10/12/14/16/18",
        "hit": "2",
        "recovery": "35",
        "block_adv": "-24",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.lk",
        "desc": "Snake Fang/ German Suplex (Short)",
        "pic": "framedata/img/ne-hcfk.gif",
        "damage": "140/200",
        "startup": "12/6",
        "hit": "1/2",
        "recovery": "28/14",
        "block_adv": "-13",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.mk",
        "desc": "Snake Fang/ German Suplex (Forward)",
        "pic": "framedata/img/ne-hcfk.gif",
        "damage": "150/240",
        "startup": "12/6",
        "hit": "1/2",
        "recovery": "30/15",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.hk",
        "desc": "Snake Fang/ German Suplex (Roundhouse)",
        "pic": "framedata/img/ne-hcfk.gif",
        "damage": "160/280",
        "startup": "12/6",
        "hit": "1/2",
        "recovery": "32/15",
        "block_adv": "-17",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.2p",
        "desc": "Tornado Hook (EX)",
        "pic": "framedata/img/ne-hcfp.gif",
        "damage": "50x5",
        "startup": "8/21/31/41/52",
        "hit": "4/3/3/3/4",
        "recovery": "21/23guard/23far",
        "block_adv": "-9",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2p",
        "desc": "Flying Viper (EX)",
        "pic": "framedata/img/ne-qcbp.gif",
        "damage": "80+120",
        "startup": "24/28",
        "hit": "5/4",
        "recovery": "10",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "qcb.2k",
        "desc": "Rising Cobra (EX)",
        "pic": "framedata/img/ne-qcbk.gif",
        "damage": "100+110",
        "startup": "25/27",
        "hit": "2/2",
        "recovery": "17",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Magnetic Storm",
        "pic": "framedata/img/ne-sa1.gif",
        "damage": "370",
        "startup": "2",
        "hit": "4+(3+3)x5+8",
        "recovery": "22",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Slam Dance",
        "pic": "framedata/img/ne-sa2.gif",
        "damage": "470",
        "startup": "3",
        "hit": "6",
        "recovery": "8",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Electric Snake",
        "pic": "framedata/img/ne-sa3.gif",
        "damage": "280",
        "startup": "3/11/21",
        "hit": "3",
        "recovery": "39",
        "block_adv": "-11",
        "hit_adv": "knd"
    }
]