oro_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "framedata/img/or-taunt.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "framedata/img/or-lp.gif",
        "damage": "30",
        "startup": "4",
        "hit": "1",
        "recovery": "10",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "framedata/img/or-mp.gif",
        "damage": "80",
        "startup": "8",
        "hit": "4",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "framedata/img/or-hp.gif",
        "damage": "60+80",
        "startup": "17",
        "hit": "1",
        "recovery": "19",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "framedata/img/or-closelp.gif",
        "damage": "35",
        "startup": "2",
        "hit": "1",
        "recovery": "5",
        "block_adv": "+5",
        "hit_adv": "+5"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "framedata/img/or-closemp.gif",
        "damage": "40+30",
        "startup": "5",
        "hit": "2",
        "recovery": "16",
        "block_adv": "-4",
        "hit_adv": "0"
    },
    {
        "name": "lk",
        "desc": "Far Short",
        "pic": "framedata/img/or-lk.gif",
        "damage": "35",
        "startup": "3",
        "hit": "1",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "framedata/img/or-mk.gif",
        "damage": "100",
        "startup": "8",
        "hit": "6",
        "recovery": "12",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "framedata/img/or-hk.gif",
        "damage": "120",
        "startup": "7",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "close.lk",
        "desc": "Close Short",
        "pic": "framedata/img/or-closelk.gif",
        "damage": "40",
        "startup": "2",
        "hit": "2",
        "recovery": "4",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "framedata/img/or-closemk.gif",
        "damage": "110",
        "startup": "4",
        "hit": "3",
        "recovery": "15",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "framedata/img/or-alp.gif",
        "damage": "60",
        "startup": "7(3 neutral jump)",
        "hit": "17(12 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "framedata/img/or-amp.gif",
        "damage": "100(110 neutral jump)",
        "startup": "10(5 meutral jump)",
        "hit": "8(6 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "framedata/img/or-ahp.gif",
        "damage": "100+40",
        "startup": "9(7 neutral jump)",
        "hit": "2(4 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "framedata/img/or-alk.gif",
        "damage": "60",
        "startup": "3(2 neutral jump)",
        "hit": "13(10 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "framedata/img/or-amk.gif",
        "damage": "100(110 neutral jump)",
        "startup": "3(4 neutral jump)",
        "hit": "6(8 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "framedata/img/or-ahk.gif",
        "damage": "120(140 neutral jump)",
        "startup": "5",
        "hit": "3(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "mp+mk",
        "desc": "Tobi Hiza",
        "pic": "framedata/img/or-overhead.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Kubi-jime Kataguruma",
        "pic": "framedata/img/or-throw.gif",
        "damage": "115",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Tomoe Nage",
        "pic": "framedata/img/or-bthrow.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.lp+lk",
        "desc": "Kuuchuu Jigoku Guruma",
        "pic": "framedata/img/or-airthrow.gif",
        "damage": "180",
        "startup": "6",
        "hit": "1",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.mp",
        "desc": "Mawashi Hiji",
        "pic": "framedata/img/or-fmp.gif",
        "damage": "90",
        "startup": "8",
        "hit": "2",
        "recovery": "18",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "framedata/img/or-clp.gif",
        "damage": "30",
        "startup": "4",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "framedata/img/or-cmp.gif",
        "damage": "65",
        "startup": "7",
        "hit": "6",
        "recovery": "12",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "framedata/img/or-chp.gif",
        "damage": "120",
        "startup": "6",
        "hit": "4",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "framedata/img/or-clk.gif",
        "damage": "20",
        "startup": "4",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "framedata/img/or-cmk.gif",
        "damage": "80",
        "startup": "6",
        "hit": "4",
        "recovery": "11",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "framedata/img/or-chk.gif",
        "damage": "100",
        "startup": "10",
        "hit": "2",
        "recovery": "20",
        "block_adv": "-6",
        "hit_adv": "knd"
    },
    {
        "name": "chargef.lp",
        "desc": "Sun Disk Palm (Jab)",
        "pic": "framedata/img/or-fhcargep.gif",
        "damage": "50",
        "startup": "14",
        "hit": "1",
        "recovery": "27",
        "block_adv": "-6",
        "hit_adv": "-5"
    },
    {
        "name": "chargef.mp",
        "desc": "Sun Disk Palm (Strong)",
        "pic": "framedata/img/or-fchargep.gif",
        "damage": "50",
        "startup": "12",
        "hit": "1",
        "recovery": "25",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "chargef.hp",
        "desc": "Sun Disk Palm (Fierce)",
        "pic": "framedata/img/or-fchargep.gif",
        "damage": "60",
        "startup": "14",
        "hit": "1",
        "recovery": "23",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "chargeu.lp",
        "desc": "Oniyama (Jab)",
        "pic": "framedata/img/or-uchargep.gif",
        "damage": "140",
        "startup": "6",
        "hit": "10",
        "recovery": "29",
        "block_adv": "-22",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.mp",
        "desc": "Oniyama (Strong)",
        "pic": "framedata/img/or-uchargep.gif",
        "damage": "160",
        "startup": "6",
        "hit": "17",
        "recovery": "30",
        "block_adv": "-30",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.hp",
        "desc": "Oniyama (Fierce)",
        "pic": "framedata/img/or-uchargep.gif",
        "damage": "180",
        "startup": "1",
        "hit": "1/1/1/20",
        "recovery": "33",
        "block_adv": "-38",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.lk",
        "desc": "Jinchu Nobori (Short)",
        "pic": "framedata/img/or-qcfk.gif",
        "damage": "100",
        "startup": "27/35",
        "hit": "3/3",
        "recovery": "13",
        "block_adv": "-40~-35",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.mk",
        "desc": "Jinchu Nobori (Forward)",
        "pic": "framedata/img/or-qcfk.gif",
        "damage": "115",
        "startup": "31/39",
        "hit": "3/3",
        "recovery": "13",
        "block_adv": "-40~-35",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.hk",
        "desc": "Jinchu Nobori (Roundhouse)",
        "pic": "framedata/img/or-qcfk.gif",
        "damage": "130",
        "startup": "34/42",
        "hit": "3/3",
        "recovery": "13",
        "block_adv": "-40~-35",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcf.lk",
        "desc": "Air Jinchu Nobori (Short)",
        "pic": "framedata/img/or-aqcfk.gif",
        "damage": "160",
        "startup": "8",
        "hit": "3",
        "recovery": "13",
        "block_adv": "-40~+5",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcf.mk",
        "desc": "Air Jinchu Nobori (Forward)",
        "pic": "framedata/img/or-aqcfk.gif",
        "damage": "160",
        "startup": "8",
        "hit": "3",
        "recovery": "13",
        "block_adv": "-40~+5",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcf.hk",
        "desc": "Air Jinchu Nobori (Roundhouse)",
        "pic": "framedata/img/or-aqcfk.gif",
        "damage": "160",
        "startup": "8",
        "hit": "3",
        "recovery": "13",
        "block_adv": "-40~+5",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.lp",
        "desc": "Human Pillar Driver (Jab)",
        "pic": "framedata/img/or-hcbp.gif",
        "damage": "150",
        "startup": "9",
        "hit": "2",
        "recovery": "29",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mp",
        "desc": "Human Pillar Driver (Strong)",
        "pic": "framedata/img/or-hcbp.gif",
        "damage": "170",
        "startup": "10",
        "hit": "2",
        "recovery": "29",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.hp",
        "desc": "Human Pillar Driver (Fierce)",
        "pic": "framedata/img/or-hcp.gif",
        "damage": "190",
        "startup": "11",
        "hit": "2",
        "recovery": "29",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "chargef.2p",
        "desc": "Sun Disk Palm (EX)",
        "pic": "framedata/img/or-fhcargep.gif",
        "damage": "60+60",
        "startup": "14/20",
        "hit": "120",
        "recovery": "27/37",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "chargeu.2p",
        "desc": "Oniyama (EX)",
        "pic": "framedata/img/or-uchargep.gif",
        "damage": "220(4 hits)",
        "startup": "5",
        "hit": "3/1/1/20",
        "recovery": "43",
        "block_adv": "-47",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.2k",
        "desc": "Jinchu Nobori (EX)",
        "pic": "framedata/img/or-qcfk.gif",
        "damage": "65+65+75",
        "startup": "31/41/45",
        "hit": "6/3/3",
        "recovery": "13",
        "block_adv": "-40~-35",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcf.2k",
        "desc": "Air Jinchu Nobori (EX)",
        "pic": "framedata/img/or-aqcfk.gif",
        "damage": "45+45+25x7",
        "startup": "8",
        "hit": "3",
        "recovery": "13",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Kishin Riki/Kishin Riki Air/Kishin Tisui",
        "pic": "framedata/img/or-sa1.gif",
        "damage": "345/310/430",
        "startup": "4-10/5/12",
        "hit": "1/4/1",
        "recovery": "18-25/N/A/25",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Yagyou Dama/ Oodama",
        "pic": "framedata/img/or-sa2.gif",
        "damage": "210/600",
        "startup": "28/26",
        "hit": "144-134/1",
        "recovery": "19/3",
        "block_adv": "+27/+73",
        "hit_adv": "knd/+74"
    },
    {
        "name": "sa3",
        "desc": "Tengu Stone",
        "pic": "framedata/img/or-sa3.gif",
        "damage": "40xrock or wall hit/ 20xother hit",
        "startup": "17",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    }
]