oro_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/e/ec/%28orot%29.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28orolp%29.gif",
        "damage": "30",
        "startup": "4",
        "hit": "1",
        "recovery": "10",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/f/f1/%28oromp%29.gif",
        "damage": "80",
        "startup": "8",
        "hit": "4",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/b/b1/%28orohp%29.gif",
        "damage": "60+80",
        "startup": "17",
        "hit": "1",
        "recovery": "19",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "http://wiki.shoryuken.com/images/5/50/%28orocloselp%29.gif",
        "damage": "35",
        "startup": "2",
        "hit": "1",
        "recovery": "5",
        "block_adv": "+5",
        "hit_adv": "+5"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "http://wiki.shoryuken.com/images/c/c9/%28oroclosemp%29.gif",
        "damage": "40+30",
        "startup": "5",
        "hit": "2",
        "recovery": "16",
        "block_adv": "-4",
        "hit_adv": "0"
    },
    {
        "name": "lk",
        "desc": "Far Short",
        "pic": "http://wiki.shoryuken.com/images/f/fa/%28orolk%29.gif",
        "damage": "35",
        "startup": "3",
        "hit": "1",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "http://wiki.shoryuken.com/images/7/75/%28oromk%29.gif",
        "damage": "100",
        "startup": "8",
        "hit": "6",
        "recovery": "12",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/2/2b/%28orohk%29.gif",
        "damage": "120",
        "startup": "7",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "close.lk",
        "desc": "Close Short",
        "pic": "http://wiki.shoryuken.com/images/0/04/%28orocloselk%29.gif",
        "damage": "40",
        "startup": "2",
        "hit": "2",
        "recovery": "4",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "http://wiki.shoryuken.com/images/7/74/%28oroclosemk%29.gif",
        "damage": "110",
        "startup": "4",
        "hit": "3",
        "recovery": "15",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/3/3d/%28orojlp%29.gif",
        "damage": "60",
        "startup": "7(3 neutral jump)",
        "hit": "17(12 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/7/7e/%28orojmp%29.gif",
        "damage": "100(110 neutral jump)",
        "startup": "10(5 meutral jump)",
        "hit": "8(6 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/c/c4/%28orojhp%29.gif",
        "damage": "100+40",
        "startup": "9(7 neutral jump)",
        "hit": "2(4 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/8/8c/%28oronjlk%29.gif",
        "damage": "60",
        "startup": "3(2 neutral jump)",
        "hit": "13(10 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/5/50/%28orojmk%29.gif",
        "damage": "100(110 neutral jump)",
        "startup": "3(4 neutral jump)",
        "hit": "6(8 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/4/48/%28orojhk%29.gif",
        "damage": "120(140 neutral jump)",
        "startup": "5",
        "hit": "3(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "mp+mk",
        "desc": "Tobi Hiza",
        "pic": "http://wiki.shoryuken.com/images/9/95/%28orouoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Kubi-jime Kataguruma",
        "pic": "http://wiki.shoryuken.com/images/e/e3/%28orokjk%29.gif",
        "damage": "115",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Tomoe Nage",
        "pic": "http://wiki.shoryuken.com/images/0/07/%28orotn%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.lp+lk",
        "desc": "Kuuchuu Jigoku Guruma",
        "pic": "http://wiki.shoryuken.com/images/a/a5/%28orokjg%29.gif",
        "damage": "180",
        "startup": "6",
        "hit": "1",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.mp",
        "desc": "Mawashi Hiji",
        "pic": "http://wiki.shoryuken.com/images/9/93/%28orofmp%29.gif",
        "damage": "90",
        "startup": "8",
        "hit": "2",
        "recovery": "18",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/6/63/%28oroclp%29.gif",
        "damage": "30",
        "startup": "4",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/9/91/%28orocmp%29.gif",
        "damage": "65",
        "startup": "7",
        "hit": "6",
        "recovery": "12",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/c/c5/%28orochp%29.gif",
        "damage": "120",
        "startup": "6",
        "hit": "4",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/0/01/%28oroclk%29.gif",
        "damage": "20",
        "startup": "4",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/4/4b/%28orocmk%29.gif",
        "damage": "80",
        "startup": "6",
        "hit": "4",
        "recovery": "11",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/f/f4/%28orochk%29.gif",
        "damage": "100",
        "startup": "10",
        "hit": "2",
        "recovery": "20",
        "block_adv": "-6",
        "hit_adv": "knd"
    },
    {
        "name": "chargef.lp",
        "desc": "Sun Disk Palm (Jab)",
        "pic": "http://wiki.shoryuken.com/images/8/85/%28orosdp%29.gif",
        "damage": "50",
        "startup": "14",
        "hit": "1",
        "recovery": "27",
        "block_adv": "-6",
        "hit_adv": "-5"
    },
    {
        "name": "chargef.mp",
        "desc": "Sun Disk Palm (Strong)",
        "pic": "http://wiki.shoryuken.com/images/8/85/%28orosdp%29.gif",
        "damage": "50",
        "startup": "12",
        "hit": "1",
        "recovery": "25",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "chargef.hp",
        "desc": "Sun Disk Palm (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/8/85/%28orosdp%29.gif",
        "damage": "60",
        "startup": "14",
        "hit": "1",
        "recovery": "23",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "chargeu.lp",
        "desc": "Oniyama (Jab)",
        "pic": "http://wiki.shoryuken.com/images/7/7d/%28orooniyama%29.gif",
        "damage": "140",
        "startup": "6",
        "hit": "10",
        "recovery": "29",
        "block_adv": "-22",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.mp",
        "desc": "Oniyama (Strong)",
        "pic": "http://wiki.shoryuken.com/images/7/7d/%28orooniyama%29.gif",
        "damage": "160",
        "startup": "6",
        "hit": "17",
        "recovery": "30",
        "block_adv": "-30",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.hp",
        "desc": "Oniyama (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/7/7d/%28orooniyama%29.gif",
        "damage": "180",
        "startup": "1",
        "hit": "1/1/1/20",
        "recovery": "33",
        "block_adv": "-38",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.lk",
        "desc": "Jinchu Nobori (Short)",
        "pic": "http://wiki.shoryuken.com/images/a/a8/%28orojn%29.gif",
        "damage": "100",
        "startup": "27/35",
        "hit": "3/3",
        "recovery": "13",
        "block_adv": "-40~-35",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.mk",
        "desc": "Jinchu Nobori (Forward)",
        "pic": "http://wiki.shoryuken.com/images/a/a8/%28orojn%29.gif",
        "damage": "115",
        "startup": "31/39",
        "hit": "3/3",
        "recovery": "13",
        "block_adv": "-40~-35",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.hk",
        "desc": "Jinchu Nobori (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/a/a8/%28orojn%29.gif",
        "damage": "130",
        "startup": "34/42",
        "hit": "3/3",
        "recovery": "13",
        "block_adv": "-40~-35",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcf.lk",
        "desc": "Air Jinchu Nobori (Short)",
        "pic": "http://wiki.shoryuken.com/images/0/06/%28oroajn%29.gif",
        "damage": "160",
        "startup": "8",
        "hit": "3",
        "recovery": "13",
        "block_adv": "-40~+5",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcf.mk",
        "desc": "Air Jinchu Nobori (Forward)",
        "pic": "http://wiki.shoryuken.com/images/0/06/%28oroajn%29.gif",
        "damage": "160",
        "startup": "8",
        "hit": "3",
        "recovery": "13",
        "block_adv": "-40~+5",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcf.hk",
        "desc": "Air Jinchu Nobori (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/0/06/%28oroajn%29.gif",
        "damage": "160",
        "startup": "8",
        "hit": "3",
        "recovery": "13",
        "block_adv": "-40~+5",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.lp",
        "desc": "Human Pillar Driver (Jab)",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28orohpd%29.gif",
        "damage": "150",
        "startup": "9",
        "hit": "2",
        "recovery": "29",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mp",
        "desc": "Human Pillar Driver (Strong)",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28orohpd%29.gif",
        "damage": "170",
        "startup": "10",
        "hit": "2",
        "recovery": "29",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.hp",
        "desc": "Human Pillar Driver (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28orohpd%29.gif",
        "damage": "190",
        "startup": "11",
        "hit": "2",
        "recovery": "29",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "chargef.2p",
        "desc": "Sun Disk Palm (EX)",
        "pic": "http://wiki.shoryuken.com/images/5/50/%28orosdp2ex%29.gif",
        "damage": "60+60",
        "startup": "14/20",
        "hit": "120",
        "recovery": "27/37",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "chargeu.2p",
        "desc": "Oniyama (EX)",
        "pic": "http://wiki.shoryuken.com/images/9/92/%28orooyex%29.gif",
        "damage": "220(4 hits)",
        "startup": "5",
        "hit": "3/1/1/20",
        "recovery": "43",
        "block_adv": "-47",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.2k",
        "desc": "Jinchu Nobori (EX)",
        "pic": "http://wiki.shoryuken.com/images/0/0a/%28orojnex%29.gif",
        "damage": "65+65+75",
        "startup": "31/41/45",
        "hit": "6/3/3",
        "recovery": "13",
        "block_adv": "-40~-35",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcf.2k",
        "desc": "Air Jinchu Nobori (EX)",
        "pic": "http://wiki.shoryuken.com/images/4/48/%28oroajnex%29.gif",
        "damage": "45+45+25x7",
        "startup": "8",
        "hit": "3",
        "recovery": "13",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Kishin Riki/Kishin Riki Air/Kishin Tisui",
        "pic": "http://wiki.shoryuken.com/images/7/79/%28orosa1%29.gif",
        "damage": "345/310/430",
        "startup": "4-10/5/12",
        "hit": "1/4/1",
        "recovery": "18-25/N/A/25",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Yagyou Dama/ Oodama",
        "pic": "http://wiki.shoryuken.com/images/5/5f/%28orosa2%29.gif",
        "damage": "210/600",
        "startup": "28/26",
        "hit": "144-134/1",
        "recovery": "19/3",
        "block_adv": "+27/+73",
        "hit_adv": "knd/+74"
    },
    {
        "name": "sa3",
        "desc": "Tengu Stone",
        "pic": "http://wiki.shoryuken.com/images/b/b6/%28orosa3%29.gif",
        "damage": "40xrock or wall hit/ 20xother hit",
        "startup": "17",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    }
]