q_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "framedata/img/q-taunt.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "framedata/img/q-lp.gif",
        "damage": "30",
        "startup": "6",
        "hit": "4",
        "recovery": "4",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "framedata/img/q-mp.gif",
        "damage": "90",
        "startup": "12",
        "hit": "5",
        "recovery": "19",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "framedata/img/q-hp.gif",
        "damage": "130",
        "startup": "18",
        "hit": "16",
        "recovery": "23",
        "block_adv": "-23",
        "hit_adv": "knd"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "framedata/img/q-closelp.gif",
        "damage": "35",
        "startup": "4",
        "hit": "4",
        "recovery": "6",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "framedata/img/q-lk.gif",
        "damage": "40",
        "startup": "4",
        "hit": "4",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "framedata/img/q-mk.gif",
        "damage": "110",
        "startup": "8",
        "hit": "5",
        "recovery": "14",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "framedata/img/q-hk.gif",
        "damage": "150",
        "startup": "20",
        "hit": "5",
        "recovery": "28",
        "block_adv": "-12",
        "hit_adv": "-10"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "framedata/img/q-closemk.gif",
        "damage": "100",
        "startup": "7",
        "hit": "2",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "framedata/img/q-alp.gif",
        "damage": "40",
        "startup": "2",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-8~+7(+2~+7 neutral jump)",
        "hit_adv": "-8~+7(+2~+7 neutral jump)"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "framedata/img/q-amp.gif",
        "damage": "100",
        "startup": "7",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "+4~+10",
        "hit_adv": "+4~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "framedata/img/q-ahp.gif",
        "damage": "130",
        "startup": "10",
        "hit": "8",
        "recovery": "N/A",
        "block_adv": "0~+13",
        "hit_adv": "0~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "framedata/img/q-alk.gif",
        "damage": "40",
        "startup": "4",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-8~+7",
        "hit_adv": "-8~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "framedata/img/q-amk.gif",
        "damage": "90",
        "startup": "9",
        "hit": "8",
        "recovery": "N/A",
        "block_adv": "-5~+10",
        "hit_adv": "-5~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "framedata/img/q-ahk.gif",
        "damage": "145",
        "startup": "17",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "+3~+13",
        "hit_adv": "+3~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "framedata/img/q-overhead.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hokaku Oyobi Shippu o Mochi ta Tsuuda",
        "pic": "framedata/img/q-throw.gif",
        "damage": "110",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Hokaku Oyobi Touteki ni yoru Daraku Shougeki",
        "pic": "framedata/img/q-fthrow.gif",
        "damage": "140",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Hokaku Oyobi Touteki ni yoru Daraku Shougeki",
        "pic": "framedata/img/q-fthrow.gif",
        "damage": "140",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "framedata/img/q-clp.gif",
        "damage": "20",
        "startup": "5",
        "hit": "4",
        "recovery": "4",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "framedata/img/q-cmp.gif",
        "damage": "90",
        "startup": "8",
        "hit": "5",
        "recovery": "13",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "framedata/img/q-chp.gif",
        "damage": "120",
        "startup": "14",
        "hit": "1",
        "recovery": "20",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "framedata/img/q-clk.gif",
        "damage": "20",
        "startup": "6",
        "hit": "5",
        "recovery": "8",
        "block_adv": "-2",
        "hit_adv": "-2"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "framedata/img/q-cmk.gif",
        "damage": "80",
        "startup": "7",
        "hit": "3",
        "recovery": "14",
        "block_adv": "-3",
        "hit_adv": "-2"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "framedata/img/q-chk.gif",
        "damage": "130",
        "startup": "12",
        "hit": "8",
        "recovery": "33",
        "block_adv": "-25",
        "hit_adv": "knd"
    },
    {
        "name": "b.mp",
        "desc": "Toubu ni yaru Jouhou Kougeki",
        "pic": "framedata/img/q-bmp.gif",
        "damage": "100",
        "startup": "8",
        "hit": "4",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "b.hp",
        "desc": "Ryouude ni yaru Zenshin Tsuugeki",
        "pic": "framedata/img/q-bhp.gif",
        "damage": "120",
        "startup": "13",
        "hit": "11",
        "recovery": "15",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "b.hk",
        "desc": "Ryouude ni yaru Zenshin Tsuugeki",
        "pic": "framedata/img/q-bhk.gif",
        "damage": "140",
        "startup": "11",
        "hit": "7",
        "recovery": "35",
        "block_adv": "-26",
        "hit_adv": "knd"
    },
    {
        "name": "db.hk",
        "desc": "Tentou kara no Kyakubu Tsuugeki",
        "pic": "framedata/img/q-taunt.gif",
        "damage": "130",
        "startup": "12",
        "hit": "8",
        "recovery": "33",
        "block_adv": "-25",
        "hit_adv": "knd"
    },
    {
        "name": "df.hk",
        "desc": "Tentou kara no Kyakubu Tsuugeki",
        "pic": "framedata/img/q-taunt.gif",
        "damage": "130",
        "startup": "12",
        "hit": "8",
        "recovery": "33",
        "block_adv": "-25",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lp",
        "desc": "High Speed Barrage (Jab)",
        "pic": "framedata/img/q-qcbp.gif",
        "damage": "50x3",
        "startup": "9/19/29",
        "hit": "1/1/1",
        "recovery": "26",
        "block_adv": "-6",
        "hit_adv": "+1"
    },
    {
        "name": "qcb.mp",
        "desc": "High Speed Barrage (Strong)",
        "pic": "framedata/img/q-qcbp.gif",
        "damage": "50x3",
        "startup": "8/18/28",
        "hit": "1/1/2",
        "recovery": "28",
        "block_adv": "-9",
        "hit_adv": "0"
    },
    {
        "name": "qcb.hp",
        "desc": "High Speed Barrage (Fierce)",
        "pic": "framedata/img/q-qcbp.gif",
        "damage": "50x3",
        "startup": "9/19/29",
        "hit": "1/1/1",
        "recovery": "28",
        "block_adv": "-8",
        "hit_adv": "+1"
    },
    {
        "name": "chargef.lp",
        "desc": "Dashing Head Attack (Jab)",
        "pic": "framedata/img/q-fchargep.gif",
        "damage": "120",
        "startup": "13",
        "hit": "3",
        "recovery": "16",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "chargef.mp",
        "desc": "Dashing Head Attack (Strong)",
        "pic": "framedata/img/q-fchargep.gif",
        "damage": "140",
        "startup": "15",
        "hit": "3",
        "recovery": "16",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "chargef.hp",
        "desc": "Dashing Head Attack (Fierce)",
        "pic": "framedata/img/q-fchargep.gif",
        "damage": "155",
        "startup": "19",
        "hit": "4",
        "recovery": "16",
        "block_adv": "-3",
        "hit_adv": "-2"
    },
    {
        "name": "chargef.hold.lp",
        "desc": "Dashing Head Attack Overhead (Jab)",
        "pic": "framedata/img/q-fchargehold.gif",
        "damage": "100",
        "startup": "24",
        "hit": "3",
        "recovery": "23",
        "block_adv": "-10",
        "hit_adv": "+2"
    },
    {
        "name": "chargef.hold.mp",
        "desc": "Dashing Head Attack Overhead (Strong)",
        "pic": "framedata/img/q-fchargehold.gif",
        "damage": "115",
        "startup": "28",
        "hit": "3",
        "recovery": "24",
        "block_adv": "-11",
        "hit_adv": "+2"
    },
    {
        "name": "chargef.hold.hp",
        "desc": "Dashing Head Attack Overhead (Fierce)",
        "pic": "framedata/img/q-fchargehold.gif",
        "damage": "130",
        "startup": "32",
        "hit": "3",
        "recovery": "25",
        "block_adv": "-12",
        "hit_adv": "+2"
    },
    {
        "name": "chargef.lk",
        "desc": "Dashing Leg Attack (Short)",
        "pic": "framedata/img/q-fchargek.gif",
        "damage": "100",
        "startup": "25",
        "hit": "2",
        "recovery": "29",
        "block_adv": "-13",
        "hit_adv": "knd"
    },
    {
        "name": "chargef.mk",
        "desc": "Dashing Leg Attack (Forward)",
        "pic": "framedata/img/q-fchargek.gif",
        "damage": "125",
        "startup": "28",
        "hit": "2",
        "recovery": "30",
        "block_adv": "-14",
        "hit_adv": "knd"
    },
    {
        "name": "chargef.hk",
        "desc": "Dashing Leg Attack (Roundhouse)",
        "pic": "framedata/img/q-fchargek.gif",
        "damage": "140",
        "startup": "31",
        "hit": "2",
        "recovery": "31",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.lk",
        "desc": "Capture and Deadly Blow (Short)",
        "pic": "framedata/img/q-hcbk.gif",
        "damage": "110",
        "startup": "12",
        "hit": "2",
        "recovery": "42",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.mk",
        "desc": "Capture and Deadly Blow (Forward)",
        "pic": "framedata/img/q-hcbk.gif",
        "damage": "120",
        "startup": "13",
        "hit": "2",
        "recovery": "44",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.hk",
        "desc": "Capture and Deadly Blow (Roundhouse)",
        "pic": "framedata/img/q-hcbk.gif",
        "damage": "130",
        "startup": "14",
        "hit": "2",
        "recovery": "46",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2p",
        "desc": "High Speed Barrage (EX)",
        "pic": "framedata/img/q-qcbp.gif",
        "damage": "(30x2+40x4+50)",
        "startup": "6/14/24/33/41/42/43",
        "hit": "1/1/1/1/3/1/3",
        "recovery": "36",
        "block_adv": "-23",
        "hit_adv": "knd"
    },
    {
        "name": "chargef.2p",
        "desc": "Dashing Head Attack (EX)",
        "pic": "framedata/img/q-fchargep.gif",
        "damage": "160",
        "startup": "14",
        "hit": "3",
        "recovery": "36",
        "block_adv": "-21",
        "hit_adv": "knd"
    },
    {
        "name": "chargef.2k",
        "desc": "Dashing Leg Attack (EX)",
        "pic": "framedata/img/q-fchargek.gif",
        "damage": "90+80",
        "startup": "26",
        "hit": "2",
        "recovery": "34",
        "block_adv": "-18",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Critical Combo Attack",
        "pic": "framedata/img/q-sa1.gif",
        "damage": "380",
        "startup": "6",
        "hit": "3",
        "recovery": "31",
        "block_adv": "-19",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Deadly Double Combination",
        "pic": "framedata/img/q-sa2.gif",
        "damage": "480",
        "startup": "2",
        "hit": "1",
        "recovery": "38",
        "block_adv": "-25",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Total Destruction (Punch/Grab)",
        "pic": "framedata/img/q-sa3.gif",
        "damage": "350/470",
        "startup": "12/6",
        "hit": "1/3",
        "recovery": "39/59",
        "block_adv": "-17/N.A",
        "hit_adv": "knd/knd"
    }
]