remy_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/c/c2/%28remyt%29.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "131",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/5/5e/%28remylp%29.gif",
        "damage": "30",
        "startup": "4",
        "hit": "4",
        "recovery": "4",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/c/cd/%28remymp%29.gif",
        "damage": "60",
        "startup": "7",
        "hit": "3",
        "recovery": "12",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/5/51/%28remyhp%29.gif",
        "damage": "110",
        "startup": "10",
        "hit": "5",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "http://wiki.shoryuken.com/images/a/af/%28remycloselp%29.gif",
        "damage": "30",
        "startup": "4",
        "hit": "4",
        "recovery": "3",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "http://wiki.shoryuken.com/images/9/98/%28remyclosemp%29.gif",
        "damage": "70",
        "startup": "5",
        "hit": "5",
        "recovery": "8",
        "block_adv": "+5",
        "hit_adv": "+6"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "http://wiki.shoryuken.com/images/b/bc/%28remyclosehp%29.gif",
        "damage": "130",
        "startup": "6",
        "hit": "3",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/8/81/%28remylk%29.gif",
        "damage": "35",
        "startup": "3",
        "hit": "5",
        "recovery": "4",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "http://wiki.shoryuken.com/images/3/34/%28remymk%29.gif",
        "damage": "80",
        "startup": "8",
        "hit": "5",
        "recovery": "14",
        "block_adv": "-6",
        "hit_adv": "-2"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/d/d9/%28remyhk%29.gif",
        "damage": "130",
        "startup": "10",
        "hit": "3",
        "recovery": "23",
        "block_adv": "-9",
        "hit_adv": "-7"
    },
    {
        "name": "close.lk",
        "desc": "Close Short",
        "pic": "http://wiki.shoryuken.com/images/c/c1/%28remycloselk%29.gif",
        "damage": "35",
        "startup": "2",
        "hit": "5",
        "recovery": "7",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "http://wiki.shoryuken.com/images/d/dd/%28remyclosemk%29.gif",
        "damage": "80",
        "startup": "4",
        "hit": "6",
        "recovery": "11",
        "block_adv": "+1",
        "hit_adv": "+3"
    },
    {
        "name": "close.hk",
        "desc": "Close Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/e/e7/%28remyclosehk%29.gif",
        "damage": "140",
        "startup": "6",
        "hit": "3",
        "recovery": "15",
        "block_adv": "+3",
        "hit_adv": "+5"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/9/94/%28remyjlp%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "20",
        "recovery": "N/A",
        "block_adv": "-3~+7",
        "hit_adv": "-3~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/5/59/%28remyjmp%29.gif",
        "damage": "70",
        "startup": "5",
        "hit": "14",
        "recovery": "N/A",
        "block_adv": "-3~+10",
        "hit_adv": "-3~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/d/d8/%28remyjhp%29.gif",
        "damage": "125",
        "startup": "9",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "-2~+13",
        "hit_adv": "-2~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/c/cd/%28remyjlk%29.gif",
        "damage": "50",
        "startup": "4",
        "hit": "14",
        "recovery": "N/A",
        "block_adv": "-4~+7",
        "hit_adv": "-4~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/6/61/%28remyjmk%29.gif",
        "damage": "90",
        "startup": "6",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/6/6e/%28remyjhk%29.gif",
        "damage": "120",
        "startup": "10",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "-1~+13",
        "hit_adv": "-1~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/7/70/%28remyoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Valse no you ni Kuruoshiku",
        "pic": "http://wiki.shoryuken.com/images/8/82/%28remyvnk%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Nemuri wo Midasu Contour",
        "pic": "http://wiki.shoryuken.com/images/6/6f/%28remynmm%29.gif",
        "damage": "130",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Nemuri wo Midasu Contour",
        "pic": "http://wiki.shoryuken.com/images/6/6f/%28remynmm%29.gif",
        "damage": "130",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/b/be/%28remyclp%29.gif",
        "damage": "30",
        "startup": "5",
        "hit": "2",
        "recovery": "7",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/4/40/%28remycmp%29.gif",
        "damage": "55",
        "startup": "5",
        "hit": "5",
        "recovery": "1",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/9/9e/%28remychp%29.gif",
        "damage": "100",
        "startup": "9",
        "hit": "5",
        "recovery": "18",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/9/93/%28remyclk%29.gif",
        "damage": "30",
        "startup": "3",
        "hit": "4",
        "recovery": "7",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/9/94/%28remycmk%29.gif",
        "damage": "60",
        "startup": "8",
        "hit": "5",
        "recovery": "18",
        "block_adv": "-9",
        "hit_adv": "-8"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/4/47/%28remychk%29.gif",
        "damage": "100+110",
        "startup": "9",
        "hit": "2/5",
        "recovery": "21",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "f.mk",
        "desc": "Amari ni Muku na Aiguille",
        "pic": "http://wiki.shoryuken.com/images/0/03/%28remyfmk%29.gif",
        "damage": "80",
        "startup": "18",
        "hit": "3",
        "recovery": "20",
        "block_adv": "-7",
        "hit_adv": "-6"
    },
    {
        "name": "chargef.lp",
        "desc": "Light of Virtue (Jab)",
        "pic": "http://wiki.shoryuken.com/images/d/d7/%28remyhlov%29.gif",
        "damage": "60",
        "startup": "8",
        "hit": "1",
        "recovery": "22",
        "block_adv": "+5",
        "hit_adv": "+6"
    },
    {
        "name": "chargef.mp",
        "desc": "Light of Virtue (Strong)",
        "pic": "http://wiki.shoryuken.com/images/d/d7/%28remyhlov%29.gif",
        "damage": "60",
        "startup": "9",
        "hit": "1",
        "recovery": "22",
        "block_adv": "+5",
        "hit_adv": "+6"
    },
    {
        "name": "chargef.hp",
        "desc": "Light of Virtue (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/d/d7/%28remyhlov%29.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "22",
        "block_adv": "+5",
        "hit_adv": "+6"
    },
    {
        "name": "chargef.lk",
        "desc": "Light of Virtue (Short)",
        "pic": "http://wiki.shoryuken.com/images/4/43/%28remyllov%29.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "22",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "chargef.mk",
        "desc": "Light of Virtue (Forward)",
        "pic": "http://wiki.shoryuken.com/images/4/43/%28remyllov%29.gif",
        "damage": "60",
        "startup": "11",
        "hit": "1",
        "recovery": "22",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "chargef.hk",
        "desc": "Light of Virtue (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/4/43/%28remyllov%29.gif",
        "damage": "60",
        "startup": "12",
        "hit": "1",
        "recovery": "22",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "qcb.lk",
        "desc": "Cold Blue Kick (Short)",
        "pic": "http://wiki.shoryuken.com/images/7/7b/%28remycbk%29.gif",
        "damage": "120",
        "startup": "17",
        "hit": "12",
        "recovery": "10",
        "block_adv": "-4/+5 low",
        "hit_adv": "-4/+5 low"
    },
    {
        "name": "qcb.mk",
        "desc": "Cold Blue Kick (Forward)",
        "pic": "http://wiki.shoryuken.com/images/7/7b/%28remycbk%29.gif",
        "damage": "120",
        "startup": "18",
        "hit": "12",
        "recovery": "10",
        "block_adv": "-4/+5 low",
        "hit_adv": "-4/+5 low"
    },
    {
        "name": "qcb.hk",
        "desc": "Cold Blue Kick (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/7/7b/%28remycbk%29.gif",
        "damage": "120",
        "startup": "19",
        "hit": "12",
        "recovery": "10",
        "block_adv": "-4/+5 low",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.lk",
        "desc": "Rising Rage Flash (Short)",
        "pic": "http://wiki.shoryuken.com/images/a/a5/%28remyrsf%29.gif",
        "damage": "120",
        "startup": "3",
        "hit": "3",
        "recovery": "32",
        "block_adv": "-17",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.mk",
        "desc": "Rising Rage Flash (Forward)",
        "pic": "http://wiki.shoryuken.com/images/a/a5/%28remyrsf%29.gif",
        "damage": "130",
        "startup": "4",
        "hit": "3",
        "recovery": "39",
        "block_adv": "-23",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.hk",
        "desc": "Rising Rage Flash (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/a/a5/%28remyrsf%29.gif",
        "damage": "140",
        "startup": "5",
        "hit": "3",
        "recovery": "44",
        "block_adv": "-26",
        "hit_adv": "knd"
    },
    {
        "name": "chargef.2p",
        "desc": "Light of Virtue (EX)",
        "pic": "http://wiki.shoryuken.com/images/8/8e/%28remyhlovex%29.gif",
        "damage": "60+60",
        "startup": "7/8",
        "hit": "1",
        "recovery": "23",
        "block_adv": "+4",
        "hit_adv": "+5"
    },
    {
        "name": "chargef.2k",
        "desc": "Light of Virtue (EX)",
        "pic": "http://wiki.shoryuken.com/images/6/6d/%28remyllovex%29.gif",
        "damage": "60+60",
        "startup": "8/7",
        "hit": "1",
        "recovery": "27",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "chargeu.2k",
        "desc": "Rising Rage Flash (EX)",
        "pic": "http://wiki.shoryuken.com/images/e/e2/%28remyrrgex%29.gif",
        "damage": "120+70",
        "startup": "6",
        "hit": "5",
        "recovery": "41",
        "block_adv": "-21",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2k",
        "desc": "Cold Blue Kick (EX)",
        "pic": "http://wiki.shoryuken.com/images/1/13/%28remycbkex%29.gif",
        "damage": "90+70",
        "startup": "18",
        "hit": "9",
        "recovery": "10",
        "block_adv": "-2/+5 low",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Light of Justice",
        "pic": "http://wiki.shoryuken.com/images/8/89/%28remysa1%29.gif",
        "damage": "320",
        "startup": "1",
        "hit": "1x7",
        "recovery": "24",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "sa2",
        "desc": "Supreme Rising Rage Flash",
        "pic": "http://wiki.shoryuken.com/images/9/92/%28remysa2%29.gif",
        "damage": "390",
        "startup": "1-49",
        "hit": "1x6/2x3/5",
        "recovery": "53",
        "block_adv": "-80",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Blue Nocturne",
        "pic": "http://wiki.shoryuken.com/images/8/82/%28remysa3%29.gif",
        "damage": "465",
        "startup": "1",
        "hit": "21",
        "recovery": "39",
        "block_adv": "-21",
        "hit_adv": "knd"
    }
]