remy_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "framedata/img/re-taunt.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "131",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "framedata/img/re-lp.gif",
        "damage": "30",
        "startup": "4",
        "hit": "4",
        "recovery": "4",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "framedata/img/re-mp.gif",
        "damage": "60",
        "startup": "7",
        "hit": "3",
        "recovery": "12",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "framedata/img/re-hp.gif",
        "damage": "110",
        "startup": "10",
        "hit": "5",
        "recovery": "18",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "framedata/img/re-closelp.gif",
        "damage": "30",
        "startup": "4",
        "hit": "4",
        "recovery": "3",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "framedata/img/re-closemp.gif",
        "damage": "70",
        "startup": "5",
        "hit": "5",
        "recovery": "8",
        "block_adv": "+5",
        "hit_adv": "+6"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "framedata/img/re-closehp.gif",
        "damage": "130",
        "startup": "6",
        "hit": "3",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "0"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "framedata/img/re-lk.gif",
        "damage": "35",
        "startup": "3",
        "hit": "5",
        "recovery": "4",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "framedata/img/re-mk.gif",
        "damage": "80",
        "startup": "8",
        "hit": "5",
        "recovery": "14",
        "block_adv": "-6",
        "hit_adv": "-2"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "framedata/img/re-hk.gif",
        "damage": "130",
        "startup": "10",
        "hit": "3",
        "recovery": "23",
        "block_adv": "-9",
        "hit_adv": "-7"
    },
    {
        "name": "close.lk",
        "desc": "Close Short",
        "pic": "framedata/img/re-closelk.gif",
        "damage": "35",
        "startup": "2",
        "hit": "5",
        "recovery": "7",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "framedata/img/re-closemk.gif",
        "damage": "80",
        "startup": "4",
        "hit": "6",
        "recovery": "11",
        "block_adv": "+1",
        "hit_adv": "+3"
    },
    {
        "name": "close.hk",
        "desc": "Close Roundhouse",
        "pic": "framedata/img/re-closehk.gif",
        "damage": "140",
        "startup": "6",
        "hit": "3",
        "recovery": "15",
        "block_adv": "+3",
        "hit_adv": "+5"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "framedata/img/re-alp.gif",
        "damage": "40",
        "startup": "4",
        "hit": "20",
        "recovery": "N/A",
        "block_adv": "-3~+7",
        "hit_adv": "-3~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "framedata/img/re-amp.gif",
        "damage": "70",
        "startup": "5",
        "hit": "14",
        "recovery": "N/A",
        "block_adv": "-3~+10",
        "hit_adv": "-3~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "framedata/img/re-ahp.gif",
        "damage": "125",
        "startup": "9",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "-2~+13",
        "hit_adv": "-2~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "framedata/img/re-alk.gif",
        "damage": "50",
        "startup": "4",
        "hit": "14",
        "recovery": "N/A",
        "block_adv": "-4~+7",
        "hit_adv": "-4~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "framedata/img/re-amk.gif",
        "damage": "90",
        "startup": "6",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "framedata/img/re-ahk.gif",
        "damage": "120",
        "startup": "10",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "-1~+13",
        "hit_adv": "-1~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "framedata/img/re-overhead.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Valse no you ni Kuruoshiku",
        "pic": "framedata/img/re-throw.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Nemuri wo Midasu Contour",
        "pic": "framedata/img/re-fthrow.gif",
        "damage": "130",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Nemuri wo Midasu Contour",
        "pic": "framedata/img/re-fthrow.gif",
        "damage": "130",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "framedata/img/re-clp.gif",
        "damage": "30",
        "startup": "5",
        "hit": "2",
        "recovery": "7",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "framedata/img/re-cmp.gif",
        "damage": "55",
        "startup": "5",
        "hit": "5",
        "recovery": "1",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "framedata/img/re-chp.gif",
        "damage": "100",
        "startup": "9",
        "hit": "5",
        "recovery": "18",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "framedata/img/re-clk.gif",
        "damage": "30",
        "startup": "3",
        "hit": "4",
        "recovery": "7",
        "block_adv": "0",
        "hit_adv": "0"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "framedata/img/re-cmk.gif",
        "damage": "60",
        "startup": "8",
        "hit": "5",
        "recovery": "18",
        "block_adv": "-9",
        "hit_adv": "-8"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "framedata/img/re-chk.gif",
        "damage": "100+110",
        "startup": "9",
        "hit": "2/5",
        "recovery": "21",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "f.mk",
        "desc": "Amari ni Muku na Aiguille",
        "pic": "framedata/img/re-fmk.gif",
        "damage": "80",
        "startup": "18",
        "hit": "3",
        "recovery": "20",
        "block_adv": "-7",
        "hit_adv": "-6"
    },
    {
        "name": "chargef.lp",
        "desc": "Light of Virtue (Jab)",
        "pic": "framedata/img/re-fchargep.gif",
        "damage": "60",
        "startup": "8",
        "hit": "1",
        "recovery": "22",
        "block_adv": "+5",
        "hit_adv": "+6"
    },
    {
        "name": "chargef.mp",
        "desc": "Light of Virtue (Strong)",
        "pic": "framedata/img/re-fchargep.gif",
        "damage": "60",
        "startup": "9",
        "hit": "1",
        "recovery": "22",
        "block_adv": "+5",
        "hit_adv": "+6"
    },
    {
        "name": "chargef.hp",
        "desc": "Light of Virtue (Fierce)",
        "pic": "framedata/img/re-fchargep.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "22",
        "block_adv": "+5",
        "hit_adv": "+6"
    },
    {
        "name": "chargef.lk",
        "desc": "Light of Virtue (Short)",
        "pic": "framedata/img/re-fchargek.gif",
        "damage": "60",
        "startup": "10",
        "hit": "1",
        "recovery": "22",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "chargef.mk",
        "desc": "Light of Virtue (Forward)",
        "pic": "framedata/img/re-fchargek.gif",
        "damage": "60",
        "startup": "11",
        "hit": "1",
        "recovery": "22",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "chargef.hk",
        "desc": "Light of Virtue (Roundhouse)",
        "pic": "framedata/img/re-fchargek.gif",
        "damage": "60",
        "startup": "12",
        "hit": "1",
        "recovery": "22",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "qcb.lk",
        "desc": "Cold Blue Kick (Short)",
        "pic": "framedata/img/re-qcbk.gif",
        "damage": "120",
        "startup": "17",
        "hit": "12",
        "recovery": "10",
        "block_adv": "-4/+5 low",
        "hit_adv": "-4/+5 low"
    },
    {
        "name": "qcb.mk",
        "desc": "Cold Blue Kick (Forward)",
        "pic": "framedata/img/re-qcbk.gif",
        "damage": "120",
        "startup": "18",
        "hit": "12",
        "recovery": "10",
        "block_adv": "-4/+5 low",
        "hit_adv": "-4/+5 low"
    },
    {
        "name": "qcb.hk",
        "desc": "Cold Blue Kick (Roundhouse)",
        "pic": "framedata/img/re-qcbk.gif",
        "damage": "120",
        "startup": "19",
        "hit": "12",
        "recovery": "10",
        "block_adv": "-4/+5 low",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.lk",
        "desc": "Rising Rage Flash (Short)",
        "pic": "framedata/img/re-qcbk.gif",
        "damage": "120",
        "startup": "3",
        "hit": "3",
        "recovery": "32",
        "block_adv": "-17",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.mk",
        "desc": "Rising Rage Flash (Forward)",
        "pic": "framedata/img/re-uchargek.gif",
        "damage": "130",
        "startup": "4",
        "hit": "3",
        "recovery": "39",
        "block_adv": "-23",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.hk",
        "desc": "Rising Rage Flash (Roundhouse)",
        "pic": "framedata/img/re-uchargek.gif",
        "damage": "140",
        "startup": "5",
        "hit": "3",
        "recovery": "44",
        "block_adv": "-26",
        "hit_adv": "knd"
    },
    {
        "name": "chargef.2p",
        "desc": "Light of Virtue (EX)",
        "pic": "framedata/img/re-fchargep.gif",
        "damage": "60+60",
        "startup": "7/8",
        "hit": "1",
        "recovery": "23",
        "block_adv": "+4",
        "hit_adv": "+5"
    },
    {
        "name": "chargef.2k",
        "desc": "Light of Virtue (EX)",
        "pic": "framedata/img/re-fchargek.gif",
        "damage": "60+60",
        "startup": "8/7",
        "hit": "1",
        "recovery": "27",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "chargeu.2k",
        "desc": "Rising Rage Flash (EX)",
        "pic": "framedata/img/re-uchargek.gif",
        "damage": "120+70",
        "startup": "6",
        "hit": "5",
        "recovery": "41",
        "block_adv": "-21",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2k",
        "desc": "Cold Blue Kick (EX)",
        "pic": "framedata/img/re-qcbk.gif",
        "damage": "90+70",
        "startup": "18",
        "hit": "9",
        "recovery": "10",
        "block_adv": "-2/+5 low",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Light of Justice",
        "pic": "framedata/img/re-sa1.gif",
        "damage": "320",
        "startup": "1",
        "hit": "1x7",
        "recovery": "24",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "sa2",
        "desc": "Supreme Rising Rage Flash",
        "pic": "framedata/img/re-sa2.gif",
        "damage": "390",
        "startup": "1-49",
        "hit": "1x6/2x3/5",
        "recovery": "53",
        "block_adv": "-80",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Blue Nocturne",
        "pic": "framedata/img/re-sa3.gif",
        "damage": "465",
        "startup": "1",
        "hit": "21",
        "recovery": "39",
        "block_adv": "-21",
        "hit_adv": "knd"
    }
]