ryu_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/e/e7/%28ryut%29.gif",
        "damage": "N/A",
        "startup": "66",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/1/13/%28ryulp%29.gif",
        "damage": "30",
        "startup": "4",
        "hit": "3",
        "recovery": "4",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/6/69/%28ryump%29.gif",
        "damage": "100",
        "startup": "5",
        "hit": "4",
        "recovery": "9",
        "block_adv": "+4",
        "hit_adv": "+5"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/a/ae/%28ryuhp%29.gif",
        "damage": "130",
        "startup": "11",
        "hit": "3",
        "recovery": "18",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "http://wiki.shoryuken.com/images/6/6e/%28ryucloselp%29.gif",
        "damage": "30",
        "startup": "3",
        "hit": "3",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "http://wiki.shoryuken.com/images/2/27/%28ryuclosemp%29.gif",
        "damage": "100",
        "startup": "5",
        "hit": "4",
        "recovery": "10",
        "block_adv": "+14",
        "hit_adv": "+5"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "http://wiki.shoryuken.com/images/e/ea/%28ryuclosehp%29.gif",
        "damage": "130",
        "startup": "4",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/9/99/%28ryulk%29.gif",
        "damage": "40",
        "startup": "4",
        "hit": "4",
        "recovery": "7",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "http://wiki.shoryuken.com/images/8/8a/%28ryumk%29.gif",
        "damage": "90",
        "startup": "6",
        "hit": "4",
        "recovery": "15",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28ryuhk%29.gif",
        "damage": "140",
        "startup": "8",
        "hit": "5",
        "recovery": "18",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "http://wiki.shoryuken.com/images/e/e8/%28ryuclosemk%29.gif",
        "damage": "110",
        "startup": "4",
        "hit": "5",
        "recovery": "11",
        "block_adv": "+2",
        "hit_adv": "+4"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/1/17/%28ryujlp%29.gif",
        "damage": "50",
        "startup": "4",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/9/95/%28ryujmp%29.gif",
        "damage": "100",
        "startup": "4(5 neutral jump)",
        "hit": "2(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+4~+10",
        "hit_adv": "+4~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/a/aa/%28ryujhp%29.gif",
        "damage": "140",
        "startup": "6",
        "hit": "4(3 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+3~+13(+6~+13 neutral jump)",
        "hit_adv": "+3~+13(+6~+13 neutral jump)"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/3/32/%28ryujlk%29.gif",
        "damage": "50",
        "startup": "4",
        "hit": "19",
        "recovery": "N/A",
        "block_adv": "-6~+7",
        "hit_adv": "-6~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/0/0f/%28ryujmk%29.gif",
        "damage": "90",
        "startup": "5",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/7/70/%28ryujhk%29.gif",
        "damage": "120(130 neutral jump)",
        "startup": "6",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/1/1b/%28ryuoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "9",
        "recovery": "6",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Seoi Nage",
        "pic": "http://wiki.shoryuken.com/images/8/86/%28ryusgtr%29.gif",
        "damage": "110",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Tomoe Nage",
        "pic": "http://wiki.shoryuken.com/images/7/7c/%28ryutntr%29.gif",
        "damage": "110",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/0/08/%28ryuclp%29.gif",
        "damage": "15",
        "startup": "4",
        "hit": "3",
        "recovery": "5",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/9/9b/%28ryucmp%29.gif",
        "damage": "90",
        "startup": "5",
        "hit": "4",
        "recovery": "7",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/4/48/%28ryuchp%29.gif",
        "damage": "130",
        "startup": "5",
        "hit": "5",
        "recovery": "19",
        "block_adv": "-8",
        "hit_adv": "-6"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/0/0d/%28ryuclk%29.gif",
        "damage": "20",
        "startup": "5",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/f/ff/%28ryucmk%29.gif",
        "damage": "80",
        "startup": "7",
        "hit": "5",
        "recovery": "16",
        "block_adv": "-3",
        "hit_adv": "-2"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/4/4f/%28ryuchk%29.gif",
        "damage": "130",
        "startup": "7",
        "hit": "5",
        "recovery": "25",
        "block_adv": "-13",
        "hit_adv": "knd"
    },
    {
        "name": "f.mp",
        "desc": "Sakotsu Wari",
        "pic": "http://wiki.shoryuken.com/images/6/60/%28ryufmp%29.gif",
        "damage": "100",
        "startup": "14",
        "hit": "1,11",
        "recovery": "9",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "f.hp",
        "desc": "Kyuubi Kudaki",
        "pic": "http://wiki.shoryuken.com/images/d/d0/%28ryuhfp%29.gif",
        "damage": "70+80",
        "startup": "18",
        "hit": "2,4",
        "recovery": "13",
        "block_adv": "+2",
        "hit_adv": "+4"
    },
    {
        "name": "qcf.lp",
        "desc": "Hadouken",
        "pic": "http://wiki.shoryuken.com/images/0/0c/%28ryuhdk%29.gif",
        "damage": "60",
        "startup": "9",
        "hit": "1",
        "recovery": "36",
        "block_adv": "-9",
        "hit_adv": "-8"
    },
    {
        "name": "qcf.mp",
        "desc": "Hadouken",
        "pic": "http://wiki.shoryuken.com/images/0/0c/%28ryuhdk%29.gif",
        "damage": "60",
        "startup": "9",
        "hit": "1",
        "recovery": "36",
        "block_adv": "-9",
        "hit_adv": "-8"
    },
    {
        "name": "qcf.hp",
        "desc": "Hadouken",
        "pic": "http://wiki.shoryuken.com/images/0/0c/%28ryuhdk%29.gif",
        "damage": "60",
        "startup": "9",
        "hit": "1",
        "recovery": "36",
        "block_adv": "-9",
        "hit_adv": "-8"
    },
    {
        "name": "qcf.2p",
        "desc": "Hadouken (EX)",
        "pic": "http://wiki.shoryuken.com/images/1/17/%28ryuhdkex%29.gif",
        "damage": "60+60",
        "startup": "8",
        "hit": "1",
        "recovery": "36",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lk",
        "desc": "Tatsumaki Senpuu Kyaku (Short)",
        "pic": "http://wiki.shoryuken.com/images/f/f9/%28ryutsk%29.gif",
        "damage": "130",
        "startup": "10",
        "hit": "3",
        "recovery": "22",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.mk",
        "desc": "Tatsumaki Senpuu Kyaku (Forward)",
        "pic": "http://wiki.shoryuken.com/images/f/f9/%28ryutsk%29.gif",
        "damage": "150",
        "startup": "11/(17)/23/(29)/35",
        "hit": "2x5",
        "recovery": "30",
        "block_adv": "knd",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.hk",
        "desc": "Tatsumaki Senpuu Kyaku (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/f/f9/%28ryutsk%29.gif",
        "damage": "170",
        "startup": "11/(17)/23/(29)/35",
        "hit": "2x5",
        "recovery": "33",
        "block_adv": "knd",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2k",
        "desc": "Tatsumaki Senpuu Kyaku (EX)",
        "pic": "http://wiki.shoryuken.com/images/0/02/%28ryutskex%29.gif",
        "damage": "210",
        "startup": "10/(14)/18/(22)/26/(31)",
        "hit": "2x6",
        "recovery": "11",
        "block_adv": "knd",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcb.lk",
        "desc": "Air Tatsumaki Senpuu Kyaku (Short)",
        "pic": "http://wiki.shoryuken.com/images/8/83/%28ryuatsk%29.gif",
        "damage": "160",
        "startup": "7/(13)/19/(25)/31",
        "hit": "2",
        "recovery": "13",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcb.mk",
        "desc": "Air Tatsumaki Senpuu Kyaku (Forward)",
        "pic": "http://wiki.shoryuken.com/images/8/83/%28ryuatsk%29.gif",
        "damage": "160",
        "startup": "7/(13)/19/(25)/31",
        "hit": "2",
        "recovery": "13",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcb.hk",
        "desc": "Air Tatsumaki Senpuu Kyaku (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/8/83/%28ryuatsk%29.gif",
        "damage": "160",
        "startup": "7/(13)/19/(25)/31",
        "hit": "2",
        "recovery": "13",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "air.qcb.2k",
        "desc": "Air Tatsumaki Senpuu Kyaku (EX)",
        "pic": "http://wiki.shoryuken.com/images/3/3b/%28ryuatskex%29.gif",
        "damage": "185",
        "startup": "6/(9)/12/(15)/18/(21)",
        "hit": "1x6",
        "recovery": "13",
        "block_adv": "N/A",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lp",
        "desc": "Shoryuken (Jab)",
        "pic": "http://wiki.shoryuken.com/images/2/28/%28ryusrk%29.gif",
        "damage": "140",
        "startup": "3",
        "hit": "11",
        "recovery": "29",
        "block_adv": "-14~-24",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mp",
        "desc": "Shoryuken (Strong)",
        "pic": "http://wiki.shoryuken.com/images/2/28/%28ryusrk%29.gif",
        "damage": "155",
        "startup": "3",
        "hit": "14",
        "recovery": "34",
        "block_adv": "-20~-32",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Shoryuken (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/2/28/%28ryusrk%29.gif",
        "damage": "170",
        "startup": "3",
        "hit": "18",
        "recovery": "38",
        "block_adv": "-29~-38",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2p",
        "desc": "Shoryuken (EX)",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28ryusrkex%29.gif",
        "damage": "190",
        "startup": "2/4",
        "hit": "2/7",
        "recovery": "38",
        "block_adv": "-30-37",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.lk",
        "desc": "Joudan Sokutou Geri (Short)",
        "pic": "http://wiki.shoryuken.com/images/4/4b/%28ryujsg%29.gif",
        "damage": "120",
        "startup": "10",
        "hit": "3",
        "recovery": "28",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.mk",
        "desc": "Joudan Sokutou Geri (Forward)",
        "pic": "http://wiki.shoryuken.com/images/4/4b/%28ryujsg%29.gif",
        "damage": "140",
        "startup": "13",
        "hit": "3",
        "recovery": "27",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.hk",
        "desc": "Joudan Sokutou Geri (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/4/4b/%28ryujsg%29.gif",
        "damage": "160",
        "startup": "16",
        "hit": "3",
        "recovery": "26",
        "block_adv": "-10",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.2k",
        "desc": "Joudan Sokutou Geri (EX)",
        "pic": "http://wiki.shoryuken.com/images/1/1e/%28ryujsgex%29.gif",
        "damage": "120",
        "startup": "13",
        "hit": "4",
        "recovery": "27",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Shinkuu Hadouken",
        "pic": "http://wiki.shoryuken.com/images/a/aa/%28ryusa1%29.gif",
        "damage": "315",
        "startup": "3",
        "hit": "1",
        "recovery": "49",
        "block_adv": "-12",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Shin Shoryuken (close/far)",
        "pic": "http://wiki.shoryuken.com/images/8/89/%28ryusa2%29.gif",
        "damage": "570/210",
        "startup": "1-11/1-13",
        "hit": "1,2,2,10/2x7",
        "recovery": "40/35",
        "block_adv": "-25",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Denjin Hadouken",
        "pic": "http://wiki.shoryuken.com/images/6/66/%28ryusa3%29.gif",
        "damage": "60/120/165/225/270",
        "startup": "2-9/10-33/34-81/82-161/162-212",
        "hit": "2",
        "recovery": "(stun) 17/34/48/65/max",
        "block_adv": "N/A",
        "hit_adv": "stun"
    }
]