sean_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/a/a4/%28seant%29.gif",
        "damage": "1",
        "startup": "31",
        "hit": "N/A",
        "recovery": "19",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/7/73/%28seanlp%29.gif",
        "damage": "20",
        "startup": "3",
        "hit": "2",
        "recovery": "5",
        "block_adv": "+5",
        "hit_adv": "+5"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/3/3a/%28seanmp%29.gif",
        "damage": "80",
        "startup": "5",
        "hit": "4",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/f/f8/%28seanhp%29.gif",
        "damage": "120",
        "startup": "9",
        "hit": "4",
        "recovery": "23",
        "block_adv": "-7",
        "hit_adv": "-5~-4"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "http://wiki.shoryuken.com/images/8/86/%28seanclosemp%29.gif",
        "damage": "90",
        "startup": "4",
        "hit": "5",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "http://wiki.shoryuken.com/images/c/c6/%28seanclosehp%29.gif",
        "damage": "120",
        "startup": "5",
        "hit": "5",
        "recovery": "20",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/5/5e/%28seanlk%29.gif",
        "damage": "30",
        "startup": "4",
        "hit": "4",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "http://wiki.shoryuken.com/images/1/13/%28seanmk%29.gif",
        "damage": "90",
        "startup": "6",
        "hit": "4",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/2/2a/%28seanfhk%29.gif",
        "damage": "120",
        "startup": "7",
        "hit": "4",
        "recovery": "25",
        "block_adv": "-9",
        "hit_adv": "-7"
    },
    {
        "name": "close.hk",
        "desc": "Close Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/c/c1/%28seanclosehk%29.gif",
        "damage": "145",
        "startup": "5",
        "hit": "5",
        "recovery": "14",
        "block_adv": "+2",
        "hit_adv": "+4"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/9/95/%28seanjlp%29.gif",
        "damage": "50(40 neutral jump)",
        "startup": "4(5 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/6/6a/%28seanjmp%29.gif",
        "damage": "90",
        "startup": "5(6 neutral jump)",
        "hit": "14",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28seajhp%29.gif",
        "damage": "130",
        "startup": "6(7 neutral jump)",
        "hit": "4(3 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-4~+10",
        "hit_adv": "-4~+10"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/2/25/%28seanjlk%29.gif",
        "damage": "50",
        "startup": "4(5 neutral jump)",
        "hit": "10(19 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-8~+7",
        "hit_adv": "-8~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/5/57/%28seanjmk%29.gif",
        "damage": "90",
        "startup": "5",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "-3~+10",
        "hit_adv": "-3~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/6/63/%28seanjhk%29.gif",
        "damage": "110(130 neutral jump)",
        "startup": "6(7 neutral jump)",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-1~+10",
        "hit_adv": "-1~+10"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/6/62/%28seanuoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "8",
        "recovery": "7",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Seoi Throw",
        "pic": "http://wiki.shoryuken.com/images/3/31/%28seanhg%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Seoi Throw",
        "pic": "http://wiki.shoryuken.com/images/3/31/%28seanhg%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Tomoe Throw",
        "pic": "http://wiki.shoryuken.com/images/d/de/%28seansn%29.gif",
        "damage": "140",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/1/16/%28seanclp%29.gif",
        "damage": "20",
        "startup": "4",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/f/f1/%28seancmp%29.gif",
        "damage": "80",
        "startup": "5",
        "hit": "4",
        "recovery": "10",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/f/fc/%28seanchp%29.gif",
        "damage": "120",
        "startup": "7",
        "hit": "5",
        "recovery": "22",
        "block_adv": "-9",
        "hit_adv": "-7"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/f/f9/%28seanclk%29.gif",
        "damage": "20",
        "startup": "5",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/3/35/%28seancmk%29.gif",
        "damage": "70",
        "startup": "7",
        "hit": "5",
        "recovery": "17",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/7/70/%28seanchk%29.gif",
        "damage": "120",
        "startup": "8",
        "hit": "5",
        "recovery": "30",
        "block_adv": "-16",
        "hit_adv": "knd"
    },
    {
        "name": "f.hk",
        "desc": "Rolling Sabat",
        "pic": "http://wiki.shoryuken.com/images/5/52/%28seanthk%29.gif",
        "damage": "90",
        "startup": "15",
        "hit": "5",
        "recovery": "18",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "f.hp",
        "desc": "Sean Pachiki",
        "pic": "http://wiki.shoryuken.com/images/a/af/%28seanthp%29.gif",
        "damage": "140",
        "startup": "21",
        "hit": "7",
        "recovery": "24",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "qcf.lp",
        "desc": "Zenten",
        "pic": "http://wiki.shoryuken.com/images/e/e0/%28seanzenten%29.gif",
        "damage": "N/A",
        "startup": "2",
        "hit": "17",
        "recovery": "7",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "qcf.mp",
        "desc": "Zenten",
        "pic": "http://wiki.shoryuken.com/images/e/e0/%28seanzenten%29.gif",
        "damage": "N/A",
        "startup": "2",
        "hit": "27",
        "recovery": "7",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "qcf.hp",
        "desc": "Zenten",
        "pic": "http://wiki.shoryuken.com/images/e/e0/%28seanzenten%29.gif",
        "damage": "N/A",
        "startup": "2",
        "hit": "41",
        "recovery": "7",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "qcf.lk",
        "desc": "Ryuubi Kyaku",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28seanwheel%29.gif",
        "damage": "120",
        "startup": "25",
        "hit": "8",
        "recovery": "15",
        "block_adv": "-5~+2",
        "hit_adv": "-5~+2"
    },
    {
        "name": "qcf.mk",
        "desc": "Ryuubi Kyaku",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28seanwheel%29.gif",
        "damage": "120",
        "startup": "25",
        "hit": "8",
        "recovery": "15",
        "block_adv": "-5~+2",
        "hit_adv": "-5~+2"
    },
    {
        "name": "qcf.hk",
        "desc": "Ryuubi Kyaku",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28seanwheel%29.gif",
        "damage": "120",
        "startup": "25",
        "hit": "8",
        "recovery": "15",
        "block_adv": "-5~+2",
        "hit_adv": "-5~+2"
    },
    {
        "name": "dp.lp",
        "desc": "Dragon Smash (Jab)",
        "pic": "http://wiki.shoryuken.com/images/8/85/%28seands%29.gif",
        "damage": "130",
        "startup": "5",
        "hit": "6",
        "recovery": "36",
        "block_adv": "-24",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mp",
        "desc": "Dragon Smash (Strong)",
        "pic": "http://wiki.shoryuken.com/images/8/85/%28seands%29.gif",
        "damage": "130",
        "startup": "7",
        "hit": "8",
        "recovery": "39",
        "block_adv": "-30",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Dragon Smash (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/8/85/%28seands%29.gif",
        "damage": "130",
        "startup": "9",
        "hit": "10",
        "recovery": "42",
        "block_adv": "-34",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lk",
        "desc": "Tornado (Short)",
        "pic": "http://wiki.shoryuken.com/images/8/81/%28seandtornadokick%29.gif",
        "damage": "50+50",
        "startup": "11",
        "hit": "2",
        "recovery": "21",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "qcb.mk",
        "desc": "Tornado (Forward)",
        "pic": "http://wiki.shoryuken.com/images/8/81/%28seandtornadokick%29.gif",
        "damage": "50x3",
        "startup": "14",
        "hit": "2",
        "recovery": "21",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "qcb.hk",
        "desc": "Tornado (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/8/81/%28seandtornadokick%29.gif",
        "damage": "50+40x3",
        "startup": "16",
        "hit": "3",
        "recovery": "21",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "hcf.lp",
        "desc": "Tackle (Jab)",
        "pic": "http://wiki.shoryuken.com/images/5/57/%28seantacklefull%29.gif",
        "damage": "180",
        "startup": "18",
        "hit": "2",
        "recovery": "28",
        "block_adv": "-14",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.mp",
        "desc": "Tackle (Strong)",
        "pic": "http://wiki.shoryuken.com/images/5/57/%28seantacklefull%29.gif",
        "damage": "180",
        "startup": "22",
        "hit": "2",
        "recovery": "28",
        "block_adv": "-14",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.hp",
        "desc": "Tackle (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/5/57/%28seantacklefull%29.giff",
        "damage": "180",
        "startup": "26",
        "hit": "2",
        "recovery": "28",
        "block_adv": "-14",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.2p",
        "desc": "Ryuubi Kyaku (EX)",
        "pic": "http://wiki.shoryuken.com/images/2/2b/%28seanhdkex%29.gif",
        "damage": "60+70+70",
        "startup": "25/27/29/31",
        "hit": "2/2/2/2",
        "recovery": "19",
        "block_adv": "-1~+2",
        "hit_adv": "-1~+2"
    },
    {
        "name": "dp.2p",
        "desc": "Dragon Smash (EX)",
        "pic": "http://wiki.shoryuken.com/images/f/fc/%28seansrkex%29.gif",
        "damage": "90+90",
        "startup": "8/9",
        "hit": "1/11",
        "recovery": "42",
        "block_adv": "-37",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2k",
        "desc": "Tornado (EX)",
        "pic": "http://wiki.shoryuken.com/images/6/6c/%28seantskex%29.gif",
        "damage": "60+(40x3)",
        "startup": "9/21/30/40",
        "hit": "2/3/4/2",
        "recovery": "17",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "hcf.2p",
        "desc": "Tackle (EX)",
        "pic": "http://wiki.shoryuken.com/images/9/95/%28seanatskex%29.gif",
        "damage": "260",
        "startup": "28",
        "hit": "2",
        "recovery": "28",
        "block_adv": "-14",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Hadou Burst",
        "pic": "http://wiki.shoryuken.com/images/c/c8/%28seansa1%29.gif",
        "damage": "220",
        "startup": "2",
        "hit": "1",
        "recovery": "61",
        "block_adv": "-29",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Shoryu Cannon",
        "pic": "http://wiki.shoryuken.com/images/5/51/%28seansa2%29.gif",
        "damage": "390(14 hits)",
        "startup": "1~54",
        "hit": "2/7/2x3/1x10",
        "recovery": "36",
        "block_adv": "-43",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Hyper Tornado",
        "pic": "http://wiki.shoryuken.com/images/6/61/%28seansa3%29.gif",
        "damage": "460",
        "startup": "2",
        "hit": "14",
        "recovery": "53",
        "block_adv": "-31",
        "hit_adv": "knd"
    }
]