sean_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "framedata/img/se-taunt.gif",
        "damage": "1",
        "startup": "31",
        "hit": "N/A",
        "recovery": "19",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "framedata/img/se-lp.gif",
        "damage": "20",
        "startup": "3",
        "hit": "2",
        "recovery": "5",
        "block_adv": "+5",
        "hit_adv": "+5"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "framedata/img/se-mp.gif",
        "damage": "80",
        "startup": "5",
        "hit": "4",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "framedata/img/se-hp.gif",
        "damage": "120",
        "startup": "9",
        "hit": "4",
        "recovery": "23",
        "block_adv": "-7",
        "hit_adv": "-5~-4"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "framedata/img/se-closemp.gif",
        "damage": "90",
        "startup": "4",
        "hit": "5",
        "recovery": "13",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "framedata/img/se-closehp.gif",
        "damage": "120",
        "startup": "5",
        "hit": "5",
        "recovery": "20",
        "block_adv": "-4",
        "hit_adv": "-2"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "framedata/img/se-lk.gif",
        "damage": "30",
        "startup": "4",
        "hit": "4",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "framedata/img/se-mk.gif",
        "damage": "90",
        "startup": "6",
        "hit": "4",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "framedata/img/se-hk.gif",
        "damage": "120",
        "startup": "7",
        "hit": "4",
        "recovery": "25",
        "block_adv": "-9",
        "hit_adv": "-7"
    },
    {
        "name": "close.hk",
        "desc": "Close Roundhouse",
        "pic": "framedata/img/se-closehk.gif",
        "damage": "145",
        "startup": "5",
        "hit": "5",
        "recovery": "14",
        "block_adv": "+2",
        "hit_adv": "+4"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "framedata/img/se-alp.gif",
        "damage": "50(40 neutral jump)",
        "startup": "4(5 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "framedata/img/se-amp.gif",
        "damage": "90",
        "startup": "5(6 neutral jump)",
        "hit": "14",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "framedata/img/se-ahp.gif",
        "damage": "130",
        "startup": "6(7 neutral jump)",
        "hit": "4(3 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-4~+10",
        "hit_adv": "-4~+10"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "framedata/img/se-alk.gif",
        "damage": "50",
        "startup": "4(5 neutral jump)",
        "hit": "10(19 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-8~+7",
        "hit_adv": "-8~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "framedata/img/se-amk.gif",
        "damage": "90",
        "startup": "5",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "-3~+10",
        "hit_adv": "-3~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "framedata/img/se-ahk.gif",
        "damage": "110(130 neutral jump)",
        "startup": "6(7 neutral jump)",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-1~+10",
        "hit_adv": "-1~+10"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "framedata/img/se-overhead.gif",
        "damage": "40",
        "startup": "15",
        "hit": "8",
        "recovery": "7",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Seoi Throw",
        "pic": "framedata/img/se-fthrow.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Seoi Throw",
        "pic": "framedata/img/se-fthrow.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Tomoe Throw",
        "pic": "framedata/img/se-bthrow.gif",
        "damage": "140",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "framedata/img/se-clp.gif",
        "damage": "20",
        "startup": "4",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "framedata/img/se-cmp.gif",
        "damage": "80",
        "startup": "5",
        "hit": "4",
        "recovery": "10",
        "block_adv": "+3",
        "hit_adv": "+4"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "framedata/img/se-chp.gif",
        "damage": "120",
        "startup": "7",
        "hit": "5",
        "recovery": "22",
        "block_adv": "-9",
        "hit_adv": "-7"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "framedata/img/se-clk.gif",
        "damage": "20",
        "startup": "5",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "framedata/img/se-cmk.gif",
        "damage": "70",
        "startup": "7",
        "hit": "5",
        "recovery": "17",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "framedata/img/se-chk.gif",
        "damage": "120",
        "startup": "8",
        "hit": "5",
        "recovery": "30",
        "block_adv": "-16",
        "hit_adv": "knd"
    },
    {
        "name": "f.hk",
        "desc": "Rolling Sabat",
        "pic": "framedata/img/se-fhk.gif",
        "damage": "90",
        "startup": "15",
        "hit": "5",
        "recovery": "18",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "f.hp",
        "desc": "Sean Pachiki",
        "pic": "framedata/img/se-fhp.gif",
        "damage": "140",
        "startup": "21",
        "hit": "7",
        "recovery": "24",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "qcf.lp",
        "desc": "Zenten",
        "pic": "framedata/img/se-taunt.gif",
        "damage": "N/A",
        "startup": "2",
        "hit": "17",
        "recovery": "7",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "qcf.mp",
        "desc": "Zenten",
        "pic": "framedata/img/se-taunt.gif",
        "damage": "N/A",
        "startup": "2",
        "hit": "27",
        "recovery": "7",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "qcf.hp",
        "desc": "Zenten",
        "pic": "framedata/img/se-taunt.gif",
        "damage": "N/A",
        "startup": "2",
        "hit": "41",
        "recovery": "7",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "qcf.lk",
        "desc": "Ryuubi Kyaku",
        "pic": "framedata/img/se-qcfk.gif",
        "damage": "120",
        "startup": "25",
        "hit": "8",
        "recovery": "15",
        "block_adv": "-5~+2",
        "hit_adv": "-5~+2"
    },
    {
        "name": "qcf.mk",
        "desc": "Ryuubi Kyaku",
        "pic": "framedata/img/se-qcfk.gif",
        "damage": "120",
        "startup": "25",
        "hit": "8",
        "recovery": "15",
        "block_adv": "-5~+2",
        "hit_adv": "-5~+2"
    },
    {
        "name": "qcf.hk",
        "desc": "Ryuubi Kyaku",
        "pic": "framedata/img/se-qcfk.gif",
        "damage": "120",
        "startup": "25",
        "hit": "8",
        "recovery": "15",
        "block_adv": "-5~+2",
        "hit_adv": "-5~+2"
    },
    {
        "name": "dp.lp",
        "desc": "Dragon Smash (Jab)",
        "pic": "framedata/img/se-dp.gif",
        "damage": "130",
        "startup": "5",
        "hit": "6",
        "recovery": "36",
        "block_adv": "-24",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mp",
        "desc": "Dragon Smash (Strong)",
        "pic": "framedata/img/se-dp.gif",
        "damage": "130",
        "startup": "7",
        "hit": "8",
        "recovery": "39",
        "block_adv": "-30",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Dragon Smash (Fierce)",
        "pic": "framedata/img/se-dp.gif",
        "damage": "130",
        "startup": "9",
        "hit": "10",
        "recovery": "42",
        "block_adv": "-34",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lk",
        "desc": "Tornado (Short)",
        "pic": "framedata/img/se-qcbk.gif",
        "damage": "50+50",
        "startup": "11",
        "hit": "2",
        "recovery": "21",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "qcb.mk",
        "desc": "Tornado (Forward)",
        "pic": "framedata/img/se-qcbk.gif",
        "damage": "50x3",
        "startup": "14",
        "hit": "2",
        "recovery": "21",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "qcb.hk",
        "desc": "Tornado (Roundhouse)",
        "pic": "framedata/img/se-qcbk.gif",
        "damage": "50+40x3",
        "startup": "16",
        "hit": "3",
        "recovery": "21",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "hcf.lp",
        "desc": "Tackle (Jab)",
        "pic": "framedata/img/se-hcfp.gif",
        "damage": "180",
        "startup": "18",
        "hit": "2",
        "recovery": "28",
        "block_adv": "-14",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.mp",
        "desc": "Tackle (Strong)",
        "pic": "framedata/img/se-hcfp.gif",
        "damage": "180",
        "startup": "22",
        "hit": "2",
        "recovery": "28",
        "block_adv": "-14",
        "hit_adv": "knd"
    },
    {
        "name": "hcf.hp",
        "desc": "Tackle (Fierce)",
        "pic": "framedata/img/se-hcfp.gif",
        "damage": "180",
        "startup": "26",
        "hit": "2",
        "recovery": "28",
        "block_adv": "-14",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.2k",
        "desc": "Ryuubi Kyaku (EX)",
        "pic": "framedata/img/se-qcfp.gif",
        "damage": "60+70+70",
        "startup": "25/27/29/31",
        "hit": "2/2/2/2",
        "recovery": "19",
        "block_adv": "-1~+2",
        "hit_adv": "-1~+2"
    },
    {
        "name": "dp.2p",
        "desc": "Dragon Smash (EX)",
        "pic": "framedata/img/se-dp.gif",
        "damage": "90+90",
        "startup": "8/9",
        "hit": "1/11",
        "recovery": "42",
        "block_adv": "-37",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2k",
        "desc": "Tornado (EX)",
        "pic": "framedata/img/se-qcbk.gif",
        "damage": "60+(40x3)",
        "startup": "9/21/30/40",
        "hit": "2/3/4/2",
        "recovery": "17",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "hcf.2p",
        "desc": "Tackle (EX)",
        "pic": "framedata/img/se-hcfp.gif",
        "damage": "260",
        "startup": "28",
        "hit": "2",
        "recovery": "28",
        "block_adv": "-14",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Hadou Burst",
        "pic": "framedata/img/se-sa1.gif",
        "damage": "220",
        "startup": "2",
        "hit": "1",
        "recovery": "61",
        "block_adv": "-29",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Shoryu Cannon",
        "pic": "framedata/img/se-sa2.gif",
        "damage": "390(14 hits)",
        "startup": "1~54",
        "hit": "2/7/2x3/1x10",
        "recovery": "36",
        "block_adv": "-43",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Hyper Tornado",
        "pic": "framedata/img/se-sa3.gif",
        "damage": "460",
        "startup": "2",
        "hit": "14",
        "recovery": "53",
        "block_adv": "-31",
        "hit_adv": "knd"
    }
]