twelve_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "framedata/img/tw-taunt.gif",
        "damage": "N/A",
        "startup": "79",
        "hit": "150",
        "recovery": "71",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "framedata/img/tw-lp.gif",
        "damage": "30",
        "startup": "3",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "framedata/img/tw-mp.gif",
        "damage": "70",
        "startup": "9",
        "hit": "4",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "framedata/img/tw-hp.gif",
        "damage": "110",
        "startup": "12",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "framedata/img/tw-closemp.gif",
        "damage": "65",
        "startup": "6",
        "hit": "4",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "+4"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "framedata/img/tw-lk.gif",
        "damage": "35",
        "startup": "3",
        "hit": "5",
        "recovery": "10",
        "block_adv": "-1",
        "hit_adv": "-1"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "framedata/img/tw-mk.gif",
        "damage": "70",
        "startup": "6",
        "hit": "6",
        "recovery": "13",
        "block_adv": "-6",
        "hit_adv": "-2"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "framedata/img/tw-hk.gif",
        "damage": "100",
        "startup": "17",
        "hit": "3",
        "recovery": "25",
        "block_adv": "-11",
        "hit_adv": "-1"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "framedata/img/tw-alp.gif",
        "damage": "50(60 neutral jump)",
        "startup": "4(5 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "framedata/img/tw-amp.gif",
        "damage": "100",
        "startup": "5(6 neutral jump)",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "framedata/img/tw-ahp.gif",
        "damage": "130",
        "startup": "6(7 neutral jump)",
        "hit": "4(3 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "framedata/img/tw-alk.gif",
        "damage": "50",
        "startup": "4(5 neutral jump)",
        "hit": "10(19 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "framedata/img/tw-amk.gif",
        "damage": "90",
        "startup": "5",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "framedata/img/tw-ahk.gif",
        "damage": "125(130 neutral jump)",
        "startup": "6(7 neutral jump)",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "framedata/img/tw-overhead.gif",
        "damage": "40",
        "startup": "15",
        "hit": "8",
        "recovery": "7",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "H.U.G",
        "pic": "framedata/img/tw-throw.gif",
        "damage": "100",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "F.L.G",
        "pic": "framedata/img/tw-fthrow.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "T.R.W",
        "pic": "framedata/img/tw-bthrow.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "framedata/img/tw-clp.gif",
        "damage": "30",
        "startup": "3",
        "hit": "2",
        "recovery": "5",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "framedata/img/tw-cmp.gif",
        "damage": "55",
        "startup": "5",
        "hit": "2",
        "recovery": "10",
        "block_adv": "-2",
        "hit_adv": "+4"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "framedata/img/tw-chp.gif",
        "damage": "100",
        "startup": "10",
        "hit": "7",
        "recovery": "13",
        "block_adv": "-8",
        "hit_adv": "-1"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "framedata/img/tw-clk.gif",
        "damage": "35",
        "startup": "3",
        "hit": "4",
        "recovery": "8",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "framedata/img/tw-cmk.gif",
        "damage": "60",
        "startup": "8",
        "hit": "2",
        "recovery": "14",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "framedata/img/tw-chk.gif",
        "damage": "90",
        "startup": "13",
        "hit": "2",
        "recovery": "25",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "b.mk",
        "desc": "B.M.K",
        "pic": "framedata/img/tw-bmk.gif",
        "damage": "80",
        "startup": "5",
        "hit": "5",
        "recovery": "14",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "air.f,f",
        "desc": "Kokuu",
        "pic": "framedata/img/tw-taunt.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "NA"
    },
    {
        "name": "air.b,b",
        "desc": "Kokuu",
        "pic": "framedata/img/tw-taunt.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "NA"
    },
    {
        "name": "qcf.lp",
        "desc": "N.D.L. (Jab)",
        "pic": "framedata/img/tw-qcfp.gif",
        "damage": "60",
        "startup": "13",
        "hit": "11",
        "recovery": "14",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "qcf.mp",
        "desc": "N.D.L. (Strong)",
        "pic": "framedata/img/tw-qcfp.gif",
        "damage": "60",
        "startup": "13",
        "hit": "13",
        "recovery": "16",
        "block_adv": "-9",
        "hit_adv": "-8"
    },
    {
        "name": "qcf.hp",
        "desc": "N.D.L. (Fierce)",
        "pic": "framedata/img/tw-qcfp.gif",
        "damage": "80",
        "startup": "14",
        "hit": "13",
        "recovery": "20",
        "block_adv": "-13",
        "hit_adv": "-12"
    },
    {
        "name": "qcb.lp",
        "desc": "A.X.E. (Jab)",
        "pic": "framedata/img/tw-qcbp.gif",
        "damage": "60",
        "startup": "6",
        "hit": "3",
        "recovery": "16",
        "block_adv": "-5",
        "hit_adv": "-1"
    },
    {
        "name": "qcb.mp",
        "desc": "A.X.E. (Strong)",
        "pic": "framedata/img/tw-qcbp.gif",
        "damage": "140",
        "startup": "10",
        "hit": "3",
        "recovery": "17",
        "block_adv": "-6",
        "hit_adv": "-1"
    },
    {
        "name": "qcb.hp",
        "desc": "A.X.E. (Fierce)",
        "pic": "framedata/img/tw-qcbp.gif",
        "damage": "200",
        "startup": "14",
        "hit": "3",
        "recovery": "18",
        "block_adv": "-7",
        "hit_adv": "-1"
    },
    {
        "name": "air.qcb.lp",
        "desc": "Air A.X.E. (Jab)",
        "pic": "framedata/img/tw-aqcbp.gif",
        "damage": "90",
        "startup": "9",
        "hit": "3",
        "recovery": "15",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.mp",
        "desc": "Air A.X.E. (Strong)",
        "pic": "framedata/img/tw-aqcbp.gif",
        "damage": "120",
        "startup": "11",
        "hit": "3",
        "recovery": "15",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.hp",
        "desc": "Air A.X.E. (Fierce)",
        "pic": "framedata/img/tw-aqcbp.gif",
        "damage": "180",
        "startup": "13",
        "hit": "3",
        "recovery": "15",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.lk",
        "desc": "D.R.A (Short)",
        "pic": "framedata/img/tw-aqcbk.gif",
        "damage": "110",
        "startup": "14",
        "hit": "until land",
        "recovery": "10~11/20whiff/12~13parry",
        "block_adv": "-11",
        "hit_adv": "0"
    },
    {
        "name": "air.qcb.mk",
        "desc": "D.R.A (Forward)",
        "pic": "framedata/img/tw-aqcbk.gif",
        "damage": "110",
        "startup": "14",
        "hit": "until land",
        "recovery": "10~11/20whiff/12~13parry",
        "block_adv": "-11",
        "hit_adv": "0"
    },
    {
        "name": "air.qcb.hk",
        "desc": "D.R.A (Roundhouse)",
        "pic": "framedata/img/tw-aqcbk.gif",
        "damage": "110",
        "startup": "14",
        "hit": "until land",
        "recovery": "10~11/20whiff/12~13parry",
        "block_adv": "-11",
        "hit_adv": "0"
    },
    {
        "name": "qcf.2p",
        "desc": "N.D.L. (EX)",
        "pic": "framedata/img/tw-qcfp.gif",
        "damage": "50+30",
        "startup": "12/18",
        "hit": "6/7",
        "recovery": "15",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2p",
        "desc": "A.X.E. (EX)",
        "pic": "framedata/img/tw-qcbp.gif",
        "damage": "60+(40x5)",
        "startup": "8",
        "hit": "3/3/5/3/3/4",
        "recovery": "15",
        "block_adv": "-4",
        "hit_adv": "-1"
    },
    {
        "name": "air.qcb.2p",
        "desc": "Air A.X.E. (EX)",
        "pic": "framedata/img/tw-aqcbp.gif",
        "damage": "60+(35)",
        "startup": "6",
        "hit": "3/3/4/3/3/4",
        "recovery": "15",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.2k",
        "desc": "D.R.A. (EX)",
        "pic": "framedata/img/tw-aqcbk.gif",
        "damage": "240",
        "startup": "6/8",
        "hit": "until land",
        "recovery": "20",
        "block_adv": "-8~0",
        "hit_adv": "-1~0/knd"
    },
    {
        "name": "sa1",
        "desc": "X.N.D.L.",
        "pic": "framedata/img/tw-sa1.gif",
        "damage": "370",
        "startup": "3",
        "hit": "34",
        "recovery": "33",
        "block_adv": "-31",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "X.F.L.A.T.",
        "pic": "framedata/img/tw-sa2.gif",
        "damage": "430",
        "startup": "2",
        "hit": "until land",
        "recovery": "49",
        "block_adv": "-26",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "X.C.O.P.Y.",
        "pic": "framedata/img/tw-sa3.gif",
        "damage": "N/A",
        "startup": "12",
        "hit": "1440",
        "recovery": "73",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    }
]