twelve_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/3/37/%28twelvet%29.gif",
        "damage": "N/A",
        "startup": "79",
        "hit": "150",
        "recovery": "71",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/2/20/%28twelvelp%29.gif",
        "damage": "30",
        "startup": "3",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/5/54/%28twelvemp%29.gif",
        "damage": "70",
        "startup": "9",
        "hit": "4",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/3/39/%28twelvehp%29.gif",
        "damage": "110",
        "startup": "12",
        "hit": "4",
        "recovery": "17",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "http://wiki.shoryuken.com/images/e/ea/%28twelveclosemp%29.gif",
        "damage": "65",
        "startup": "6",
        "hit": "4",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "+4"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28twelvelk%29.gif",
        "damage": "35",
        "startup": "3",
        "hit": "5",
        "recovery": "10",
        "block_adv": "-1",
        "hit_adv": "-1"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "http://wiki.shoryuken.com/images/8/8e/%28twelvemk%29.gif",
        "damage": "70",
        "startup": "6",
        "hit": "6",
        "recovery": "13",
        "block_adv": "-6",
        "hit_adv": "-2"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/1/1b/%28twelvehk%29.gif",
        "damage": "100",
        "startup": "17",
        "hit": "3",
        "recovery": "25",
        "block_adv": "-11",
        "hit_adv": "-1"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/d/dc/%28twelvejlp%29.gif",
        "damage": "50(60 neutral jump)",
        "startup": "4(5 neutral jump)",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/6/6b/%28twelvejmp%29.gif",
        "damage": "100",
        "startup": "5(6 neutral jump)",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28twelvejhp%29.gif",
        "damage": "130",
        "startup": "6(7 neutral jump)",
        "hit": "4(3 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/7/74/%28twelvejlk%29.gif",
        "damage": "50",
        "startup": "4(5 neutral jump)",
        "hit": "10(19 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/1/11/%28twelvejmk%29.gif",
        "damage": "90",
        "startup": "5",
        "hit": "6",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/4/4b/%28twelvejhk%29.gif",
        "damage": "125(130 neutral jump)",
        "startup": "6(7 neutral jump)",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/d/d8/%28twelveoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "8",
        "recovery": "7",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "H.U.G",
        "pic": "http://wiki.shoryuken.com/images/1/1c/%28twelventr%29.gif",
        "damage": "100",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "F.L.G",
        "pic": "http://wiki.shoryuken.com/images/2/23/%28twelveftr%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "T.R.W",
        "pic": "http://wiki.shoryuken.com/images/9/95/%28twelvebtr%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/c/ca/%28twelveclp%29.gif",
        "damage": "30",
        "startup": "3",
        "hit": "2",
        "recovery": "5",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/2/2e/%28twelvecmp%29.gif",
        "damage": "55",
        "startup": "5",
        "hit": "2",
        "recovery": "10",
        "block_adv": "-2",
        "hit_adv": "+4"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/6/6b/%28twelvechp%29.gif",
        "damage": "100",
        "startup": "10",
        "hit": "7",
        "recovery": "13",
        "block_adv": "-8",
        "hit_adv": "-1"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/c/cb/%28twelveclk%29.gif",
        "damage": "35",
        "startup": "3",
        "hit": "4",
        "recovery": "8",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/8/88/%28twelvecmk%29.gif",
        "damage": "60",
        "startup": "8",
        "hit": "2",
        "recovery": "14",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/9/9d/%28twelvechk%29.gif",
        "damage": "90",
        "startup": "13",
        "hit": "2",
        "recovery": "25",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "b.mk",
        "desc": "B.M.K",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28twelvebmk%29.gif",
        "damage": "80",
        "startup": "5",
        "hit": "5",
        "recovery": "14",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "air.f,f",
        "desc": "Kokuu",
        "pic": "http://wiki.shoryuken.com/images/3/3e/%28twelvejffbb%29.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "NA"
    },
    {
        "name": "air.b,b",
        "desc": "Kokuu",
        "pic": "http://wiki.shoryuken.com/images/3/3e/%28twelvejffbb%29.gif",
        "damage": "N/A",
        "startup": "N/A",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "NA"
    },
    {
        "name": "qcf.lp",
        "desc": "N.D.L. (Jab)",
        "pic": "http://wiki.shoryuken.com/images/5/56/%28twelvendl%29.gif",
        "damage": "60",
        "startup": "13",
        "hit": "11",
        "recovery": "14",
        "block_adv": "-5",
        "hit_adv": "-4"
    },
    {
        "name": "qcf.mp",
        "desc": "N.D.L. (Strong)",
        "pic": "http://wiki.shoryuken.com/images/5/56/%28twelvendl%29.gif",
        "damage": "60",
        "startup": "13",
        "hit": "13",
        "recovery": "16",
        "block_adv": "-9",
        "hit_adv": "-8"
    },
    {
        "name": "qcf.hp",
        "desc": "N.D.L. (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/5/56/%28twelvendl%29.gif",
        "damage": "80",
        "startup": "14",
        "hit": "13",
        "recovery": "20",
        "block_adv": "-13",
        "hit_adv": "-12"
    },
    {
        "name": "qcb.lp",
        "desc": "A.X.E. (Jab)",
        "pic": "http://wiki.shoryuken.com/images/1/1c/%28twelveaxe%29.gif",
        "damage": "60",
        "startup": "6",
        "hit": "3",
        "recovery": "16",
        "block_adv": "-5",
        "hit_adv": "-1"
    },
    {
        "name": "qcb.mp",
        "desc": "A.X.E. (Strong)",
        "pic": "http://wiki.shoryuken.com/images/1/1c/%28twelveaxe%29.gif",
        "damage": "140",
        "startup": "10",
        "hit": "3",
        "recovery": "17",
        "block_adv": "-6",
        "hit_adv": "-1"
    },
    {
        "name": "qcb.hp",
        "desc": "A.X.E. (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/1/1c/%28twelveaxe%29.gif",
        "damage": "200",
        "startup": "14",
        "hit": "3",
        "recovery": "18",
        "block_adv": "-7",
        "hit_adv": "-1"
    },
    {
        "name": "air.qcb.lp",
        "desc": "Air A.X.E. (Jab)",
        "pic": "http://wiki.shoryuken.com/images/6/68/%28twelveaaxe%29.gif",
        "damage": "90",
        "startup": "9",
        "hit": "3",
        "recovery": "15",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.mp",
        "desc": "Air A.X.E. (Strong)",
        "pic": "http://wiki.shoryuken.com/images/6/68/%28twelveaaxe%29.gif",
        "damage": "120",
        "startup": "11",
        "hit": "3",
        "recovery": "15",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.hp",
        "desc": "Air A.X.E. (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/6/68/%28twelveaaxe%29.gif",
        "damage": "180",
        "startup": "13",
        "hit": "3",
        "recovery": "15",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.lk",
        "desc": "D.R.A (Short)",
        "pic": "http://wiki.shoryuken.com/images/e/e9/%28twelvedra%29.gif",
        "damage": "110",
        "startup": "14",
        "hit": "until land",
        "recovery": "10~11/20whiff/12~13parry",
        "block_adv": "-11",
        "hit_adv": "0"
    },
    {
        "name": "air.qcb.mk",
        "desc": "D.R.A (Forward)",
        "pic": "http://wiki.shoryuken.com/images/e/e9/%28twelvedra%29.gif",
        "damage": "110",
        "startup": "14",
        "hit": "until land",
        "recovery": "10~11/20whiff/12~13parry",
        "block_adv": "-11",
        "hit_adv": "0"
    },
    {
        "name": "air.qcb.hk",
        "desc": "D.R.A (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/e/e9/%28twelvedra%29.gif",
        "damage": "110",
        "startup": "14",
        "hit": "until land",
        "recovery": "10~11/20whiff/12~13parry",
        "block_adv": "-11",
        "hit_adv": "0"
    },
    {
        "name": "qcf.2p",
        "desc": "N.D.L. (EX)",
        "pic": "http://wiki.shoryuken.com/images/4/4f/%28twelvendlex%29.gif",
        "damage": "50+30",
        "startup": "12/18",
        "hit": "6/7",
        "recovery": "15",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.2p",
        "desc": "A.X.E. (EX)",
        "pic": "http://wiki.shoryuken.com/images/5/59/%28twelveaxeex%29.gif",
        "damage": "60+(40x5)",
        "startup": "8",
        "hit": "3/3/5/3/3/4",
        "recovery": "15",
        "block_adv": "-4",
        "hit_adv": "-1"
    },
    {
        "name": "air.qcb.2p",
        "desc": "Air A.X.E. (EX)",
        "pic": "http://wiki.shoryuken.com/images/1/19/%28twelveaaxeex%29.gif",
        "damage": "60+(35)",
        "startup": "6",
        "hit": "3/3/4/3/3/4",
        "recovery": "15",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "air.qcb.2k",
        "desc": "D.R.A. (EX)",
        "pic": "http://wiki.shoryuken.com/images/d/d6/%28twelvedraex%29.gif",
        "damage": "240",
        "startup": "6/8",
        "hit": "until land",
        "recovery": "20",
        "block_adv": "-8~0",
        "hit_adv": "-1~0/knd"
    },
    {
        "name": "sa1",
        "desc": "X.N.D.L.",
        "pic": "http://wiki.shoryuken.com/images/4/46/%28twelvesa1%29.gif",
        "damage": "370",
        "startup": "3",
        "hit": "34",
        "recovery": "33",
        "block_adv": "-31",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "X.F.L.A.T.",
        "pic": "http://wiki.shoryuken.com/images/b/bf/%28twelvesa2%29.gif",
        "damage": "430",
        "startup": "2",
        "hit": "until land",
        "recovery": "49",
        "block_adv": "-26",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "X.C.O.P.Y.",
        "pic": "http://wiki.shoryuken.com/images/f/f3/%28twelvesa3%29.gif",
        "damage": "N/A",
        "startup": "12",
        "hit": "1440",
        "recovery": "73",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    }
]