urien_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/f/fe/%28urient%29.gif",
        "damage": "5",
        "startup": "21",
        "hit": "3",
        "recovery": "1",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/6/6f/Urienfarlp.gif",
        "damage": "15",
        "startup": "4",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/7/72/Urienfarmp.gif",
        "damage": "80",
        "startup": "5",
        "hit": "5",
        "recovery": "10",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/d/dc/Urienfarhp.gif",
        "damage": "130",
        "startup": "10",
        "hit": "4",
        "recovery": "15",
        "block_adv": "-3",
        "hit_adv": "-1"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/3/35/Urienfarlk.gif",
        "damage": "30",
        "startup": "5",
        "hit": "2",
        "recovery": "7",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Far Forward",
        "pic": "http://wiki.shoryuken.com/images/8/82/Urienfarmk.gif",
        "damage": "80",
        "startup": "8",
        "hit": "2",
        "recovery": "15",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "hk",
        "desc": "Far Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/f/f0/Urienfarhk.gif",
        "damage": "140",
        "startup": "17",
        "hit": "3",
        "recovery": "20",
        "block_adv": "-7",
        "hit_adv": "-5"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/4/49/Urienjumpinglp.gif",
        "damage": "50",
        "startup": "4",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-5~+7",
        "hit_adv": "-5~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/a/af/Urienjumpingmp.gif",
        "damage": "90",
        "startup": "6",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "+3~+10",
        "hit_adv": "+3~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/2/2c/Urienjumpinghp.gif",
        "damage": "130",
        "startup": "7",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "+3~+13",
        "hit_adv": "+3~+13"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/0/05/Urienjumpinglk.gif",
        "damage": "50",
        "startup": "4",
        "hit": "10",
        "recovery": "N/A",
        "block_adv": "-7~+7",
        "hit_adv": "-7~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/a/a0/Urienjumpingmk.gif",
        "damage": "90",
        "startup": "6",
        "hit": "4",
        "recovery": "N/A",
        "block_adv": "+2~+10",
        "hit_adv": "+2~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/3/36/Urienjumpinghk.gif",
        "damage": "130",
        "startup": "10",
        "hit": "3",
        "recovery": "N/A",
        "block_adv": "+2~+13",
        "hit_adv": "+2~+13"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/2/2d/%28urienoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Destroy Claw",
        "pic": "http://wiki.shoryuken.com/images/0/0c/%28uriennt%29.gif",
        "damage": "100",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Spartan Bomb",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28uriensbft%29.gif",
        "damage": "140",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Spartan Bomb",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28uriensbft%29.gif",
        "damage": "140",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/0/02/Uriencrouchinglp.gif",
        "damage": "15",
        "startup": "4",
        "hit": "2",
        "recovery": "7",
        "block_adv": "+3",
        "hit_adv": "+3"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/c/c6/Uriencrouchingmp.gif",
        "damage": "60",
        "startup": "11",
        "hit": "4",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/d/d1/Uriencrouchinghp.gif",
        "damage": "110",
        "startup": "9",
        "hit": "1",
        "recovery": "25",
        "block_adv": "-10",
        "hit_adv": "knd"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/6/6f/Uriencrouchinglk.gif",
        "damage": "15",
        "startup": "5",
        "hit": "1",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/9/9e/Uriencrouchingmk.gif",
        "damage": "70",
        "startup": "7",
        "hit": "3",
        "recovery": "11",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/d/d5/Uriencrouchinghk.gif",
        "damage": "100",
        "startup": "12",
        "hit": "3",
        "recovery": "21",
        "block_adv": "-13",
        "hit_adv": "knd"
    },
    {
        "name": "f.mp",
        "desc": "Quarrel Punch",
        "pic": "http://wiki.shoryuken.com/images/3/3b/%28urienfmp%29.gif",
        "damage": "80",
        "startup": "9",
        "hit": "2",
        "recovery": "14",
        "block_adv": "-3",
        "hit_adv": "-2"
    },
    {
        "name": "f.hp",
        "desc": "Terrible Smash",
        "pic": "http://wiki.shoryuken.com/images/d/d9/%28urienfhp%29.gif",
        "damage": "120",
        "startup": "14",
        "hit": "1",
        "recovery": "21",
        "block_adv": "-6",
        "hit_adv": "-4"
    },
    {
        "name": "f.mk",
        "desc": "Quarrel Kick",
        "pic": "http://wiki.shoryuken.com/images/1/1a/%28urienfhk%29.gif",
        "damage": "90",
        "startup": "16",
        "hit": "3",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "qcf.lp",
        "desc": "Metallic Sphere (Jab)",
        "pic": "http://wiki.shoryuken.com/images/9/9c/%28urienmspherel%29.gif",
        "damage": "70",
        "startup": "13-77",
        "hit": "1",
        "recovery": "39",
        "block_adv": "-8",
        "hit_adv": "-7"
    },
    {
        "name": "qcf.mp",
        "desc": "Metallic Sphere (Strong)",
        "pic": "http://wiki.shoryuken.com/images/b/b7/%28urienmspherem%29.gif",
        "damage": "70",
        "startup": "13-77",
        "hit": "1",
        "recovery": "35",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "qcf.hp",
        "desc": "Metallic Sphere (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/9/94/%28urienmsphereh%29.gif",
        "damage": "70",
        "startup": "13-77",
        "hit": "1",
        "recovery": "28",
        "block_adv": "-3",
        "hit_adv": "+4"
    },
    {
        "name": "chargef.lk",
        "desc": "Chariot Tackle (Short)",
        "pic": "http://wiki.shoryuken.com/images/d/d1/%28urientacklesh%29.gif",
        "damage": "120",
        "startup": "7",
        "hit": "10",
        "recovery": "18/26 guard/ 25 far",
        "block_adv": "-10",
        "hit_adv": "0"
    },
    {
        "name": "chargef.mk",
        "desc": "Chariot Tackle (Forward)",
        "pic": "http://wiki.shoryuken.com/images/d/d1/%28urientacklesh%29.gif",
        "damage": "135",
        "startup": "10",
        "hit": "12",
        "recovery": "19/27 guard/28 far",
        "block_adv": "-11",
        "hit_adv": "-1"
    },
    {
        "name": "chargef.hk",
        "desc": "Chariot Tackle (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/d/d1/%28urientacklesh%29.gif",
        "damage": "150",
        "startup": "13",
        "hit": "15",
        "recovery": "20/28 guard/ 22 far",
        "block_adv": "-12",
        "hit_adv": "-2"
    },
    {
        "name": "chargeu.lk",
        "desc": "Violence Knee Drop (Short)",
        "pic": "http://wiki.shoryuken.com/images/9/90/%28urienkneedrop%29.gif",
        "damage": "110",
        "startup": "24",
        "hit": "12",
        "recovery": "7",
        "block_adv": "+8/-20~-10",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.mk",
        "desc": "Violence Knee Drop (Forward)",
        "pic": "http://wiki.shoryuken.com/images/9/90/%28urienkneedrop%29.gif",
        "damage": "110",
        "startup": "24",
        "hit": "13",
        "recovery": "7",
        "block_adv": "+8/-20~-10",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.hk",
        "desc": "Violence Knee Drop (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/9/90/%28urienkneedrop%29.gif",
        "damage": "110",
        "startup": "24",
        "hit": "16",
        "recovery": "7",
        "block_adv": "+8/-20~-10",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.lp",
        "desc": "Dangerous Headbutt (Jab)",
        "pic": "http://wiki.shoryuken.com/images/f/ff/%28urienheadbutt%29.gif",
        "damage": "120",
        "startup": "7",
        "hit": "2",
        "recovery": "16",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.mp",
        "desc": "Dangerous Headbutt (Strong)",
        "pic": "http://wiki.shoryuken.com/images/f/ff/%28urienheadbutt%29.gif",
        "damage": "130",
        "startup": "9",
        "hit": "4",
        "recovery": "15",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.hp",
        "desc": "Dangerous Headbutt (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/f/ff/%28urienheadbutt%29.gif",
        "damage": "140",
        "startup": "12",
        "hit": "6",
        "recovery": "16",
        "block_adv": "-6",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.2p",
        "desc": "Metallic Sphere (EX)",
        "pic": "http://wiki.shoryuken.com/images/b/b0/%28urienmsphex%29.gif",
        "damage": "80+80",
        "startup": "13",
        "hit": "1",
        "recovery": "55",
        "block_adv": "-16",
        "hit_adv": "-15"
    },
    {
        "name": "chargef.2k",
        "desc": "Chariot Tackle (EX)",
        "pic": "http://wiki.shoryuken.com/images/4/4a/%28urientackleex%29.gif",
        "damage": "90+80",
        "startup": "6/30",
        "hit": "24/10",
        "recovery": "19/28 guard/ 39 far",
        "block_adv": "-9",
        "hit_adv": "+2"
    },
    {
        "name": "chargeu.2p",
        "desc": "Dangerous Headbutt (EX)",
        "pic": "http://wiki.shoryuken.com/images/c/c6/%28urienhbtex%29.gif",
        "damage": "80+80",
        "startup": "9/11",
        "hit": "2/2",
        "recovery": "12",
        "block_adv": "+2",
        "hit_adv": "knd"
    },
    {
        "name": "chargeu.2k",
        "desc": "Violence Knee Drop (EX)",
        "pic": "http://wiki.shoryuken.com/images/f/fd/%28urienvkdex%29.gif",
        "damage": "30+110",
        "startup": "26/32",
        "hit": "5/2",
        "recovery": "7",
        "block_adv": "+8/-20~-10",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Tyrant Slaughter",
        "pic": "http://wiki.shoryuken.com/images/a/a0/%28uriensa1%29.gif",
        "damage": "435",
        "startup": "1/20/40/56/68",
        "hit": "14/10/10/9/8",
        "recovery": "19",
        "block_adv": "-18",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Temporial Thunder",
        "pic": "http://wiki.shoryuken.com/images/c/c6/%28uriensa2%29.gif",
        "damage": "270/260/220",
        "startup": "1",
        "hit": "1",
        "recovery": "91",
        "block_adv": "-36",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Aegis Reflector",
        "pic": "http://wiki.shoryuken.com/images/7/71/%28uriensa3pp%29.gif",
        "damage": "30x6",
        "startup": "12/24/32/0",
        "hit": "224/212/204/238",
        "recovery": "12",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    }
]