yang_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "framedata/img/ya-taunt.gif",
        "damage": "5",
        "startup": "21",
        "hit": "10",
        "recovery": "27",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "framedata/img/ya-lp.gif",
        "damage": "20",
        "startup": "3",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "framedata/img/ya-mp.gif",
        "damage": "50",
        "startup": "5",
        "hit": "4",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "framedata/img/ya-hp.gif",
        "damage": "120",
        "startup": "9",
        "hit": "62",
        "recovery": "12",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "framedata/img/ya-closemp.gif",
        "damage": "55",
        "startup": "4",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+6",
        "hit_adv": "+7"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "framedata/img/ya-closehp.gif",
        "damage": "100",
        "startup": "5",
        "hit": "3",
        "recovery": "13",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "framedata/img/ya-lk.gif",
        "damage": "30",
        "startup": "3",
        "hit": "3",
        "recovery": "6",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "framedata/img/ya-mk.gif",
        "damage": "80",
        "startup": "9",
        "hit": "3",
        "recovery": "15",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "framedata/img/ya-hk.gif",
        "damage": "100",
        "startup": "14",
        "hit": "3",
        "recovery": "22",
        "block_adv": "-8",
        "hit_adv": "-6"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "framedata/img/ya-closemk.gif",
        "damage": "80",
        "startup": "7",
        "hit": "3",
        "recovery": "15",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "framedata/img/ya-alp.gif",
        "damage": "40",
        "startup": "2",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-4~+7",
        "hit_adv": "-4~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "framedata/img/ya-amp.gif",
        "damage": "80",
        "startup": "3",
        "hit": "6(7 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "+5~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "framedata/img/ya-ahp.gif",
        "damage": "100(120 neutral jump)",
        "startup": "5(8 neutral jump)",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "+4~+10",
        "hit_adv": "+4~+10"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "framedata/img/ya-alk.gif",
        "damage": "40",
        "startup": "3(4 neutral jump)",
        "hit": "12",
        "recovery": "+1~+7",
        "block_adv": "+1~+7",
        "hit_adv": "+6~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "framedata/img/ya-amk.gif",
        "damage": "70",
        "startup": "6",
        "hit": "7",
        "recovery": "N/A",
        "block_adv": "-3~+10",
        "hit_adv": "-3~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "framedata/img/ya-ahk.gif",
        "damage": "110",
        "startup": "5",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "0~+10(-1～+10	neutral jump)",
        "hit_adv": "0~+10(-1～+10 neutral jump)"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "framedata/img/ya-overhead.gif",
        "damage": "40",
        "startup": "15",
        "hit": "10",
        "recovery": "5",
        "block_adv": "-5~+7",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hiza Geri",
        "pic": "framedata/img/ya-throw.gif",
        "damage": "160",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Youhon Shiun",
        "pic": "framedata/img/ya-fthrow.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "b.lp+lk",
        "desc": "Monkey Flip",
        "pic": "framedata/img/ya-bthrow.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "framedata/img/ya-clp.gif",
        "damage": "20",
        "startup": "3",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "framedata/img/ya-cmp.gif",
        "damage": "70",
        "startup": "5",
        "hit": "2",
        "recovery": "11",
        "block_adv": "+2",
        "hit_adv": "+3"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "framedata/img/ya-chp.gif",
        "damage": "110",
        "startup": "8",
        "hit": "7",
        "recovery": "12",
        "block_adv": "0",
        "hit_adv": "+1"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "framedata/img/ya-clk.gif",
        "damage": "30",
        "startup": "4",
        "hit": "1",
        "recovery": "8",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "framedata/img/ya-cmk.gif",
        "damage": "50",
        "startup": "7",
        "hit": "2",
        "recovery": "13",
        "block_adv": "-1",
        "hit_adv": "0"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "framedata/img/ya-chk.gif",
        "damage": "90",
        "startup": "10",
        "hit": "3",
        "recovery": "20",
        "block_adv": "-7",
        "hit_adv": "knd"
    },
    {
        "name": "f.mk",
        "desc": "Senpuu Kyaku",
        "pic": "framedata/img/ya-fmk.gif",
        "damage": "80",
        "startup": "19",
        "hit": "6",
        "recovery": "18",
        "block_adv": "-1",
        "hit_adv": "0"
    },
    {
        "name": "f.hp",
        "desc": "Koushu",
        "pic": "framedata/img/ya-fhp.gif",
        "damage": "120",
        "startup": "9",
        "hit": "6",
        "recovery": "12",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "air.d.mk",
        "desc": "Raigeki Shuu",
        "pic": "framedata/img/ya-adfk.gif",
        "damage": "70",
        "startup": "6/6/8",
        "hit": "land",
        "recovery": "N/A",
        "block_adv": "+1",
        "hit_adv": "+2"
    },
    {
        "name": "qcf.lp",
        "desc": "Tourou-Zan (Jab)",
        "pic": "framedata/img/ya-qcfp.gif",
        "damage": "30+35+90",
        "startup": "8/6/7",
        "hit": "5/5/4",
        "recovery": "22/25/29",
        "block_adv": "-1/-4/-7",
        "hit_adv": "+1/-2/knd"
    },
    {
        "name": "qcf.mp",
        "desc": "Tourou-Zan (Strong)",
        "pic": "framedata/img/ya-qcfp.gif",
        "damage": "35+40+95",
        "startup": "8/7/7",
        "hit": "5/5/5",
        "recovery": "26/29/32",
        "block_adv": "-5/-8/-11",
        "hit_adv": "-3/-6/knd"
    },
    {
        "name": "qcf.hp",
        "desc": "Tourou-Zan (Fierce)",
        "pic": "framedata/img/ya-qcfp.gif",
        "damage": "40+45+100",
        "startup": "8/8/7",
        "hit": "5/5/6",
        "recovery": "30/33/35",
        "block_adv": "-9/-12/-15",
        "hit_adv": "-7/-10/knd"
    },
    {
        "name": "qcf.2p",
        "desc": "Tourou-Zan (EX)",
        "pic": "framedata/img/ya-qcfp.gif",
        "damage": "40+50x4",
        "startup": "7/7/5/5/4",
        "hit": "2/2/2/2/4",
        "recovery": "26/28/30/33/25",
        "block_adv": "-4/-6/-7/-11/-9",
        "hit_adv": "-2/-4/-6/-9/knd"
    },
    {
        "name": "dp.lk",
        "desc": "Kaibou (Short)",
        "pic": "framedata/img/ya-dpk.gif",
        "damage": "N/A",
        "startup": "8",
        "hit": "29",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "dp.mk",
        "desc": "Kaibou (Forward)",
        "pic": "framedata/img/ya-dpk.gif",
        "damage": "N/A",
        "startup": "10",
        "hit": "34",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "dp.hk",
        "desc": "Kaibou (Roundhouse)",
        "pic": "framedata/img/ya-dpk.gif",
        "damage": "N/A",
        "startup": "10",
        "hit": "43",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "qcf.lk",
        "desc": "Senkyuutai (Short)",
        "pic": "framedata/img/ya-qcfk.gif",
        "damage": "130",
        "startup": "8-12",
        "hit": "4/4",
        "recovery": "34",
        "block_adv": "-25",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.mk",
        "desc": "Senkyuutai (Forward)",
        "pic": "framedata/img/ya-qcfk.gif",
        "damage": "140",
        "startup": "4-16/8-20",
        "hit": "4/4",
        "recovery": "28",
        "block_adv": "-19",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.hk",
        "desc": "Senkyuutai (Roundhouse)",
        "pic": "framedata/img/ya-qcfk.gif",
        "damage": "150",
        "startup": "3-29/5-31/7-33",
        "hit": "4/4",
        "recovery": "25",
        "block_adv": "-16",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.2k",
        "desc": "Senkyuutai (EX)",
        "pic": "framedata/img/ya-qcfk.gif",
        "damage": "200",
        "startup": "3-29/5-31/7-33",
        "hit": "2/2/4",
        "recovery": "25",
        "block_adv": "-16",
        "hit_adv": "knd"
    },
    {
        "name": "sa1",
        "desc": "Raishin-Mahhaken",
        "pic": "framedata/img/ya-sa1.gif",
        "damage": "465",
        "startup": "7",
        "hit": "4",
        "recovery": "37/36",
        "block_adv": "+1",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Tenshin-Senkyutai",
        "pic": "framedata/img/ya-sa2.gif",
        "damage": "315",
        "startup": "3~67",
        "hit": "3+2+3+3+4+2",
        "recovery": "37/36",
        "block_adv": "-69",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Sei-ei Enbu",
        "pic": "framedata/img/ya-sa3.gif",
        "damage": "N/A",
        "startup": "16",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    }
]