yun_frames=[
    {
        "name": "hp+hk",
        "desc": "Taunt",
        "pic": "http://wiki.shoryuken.com/images/0/09/%28yunt%29.gif",
        "damage": "5",
        "startup": "28",
        "hit": "26",
        "recovery": "28",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "lp",
        "desc": "Far Jab",
        "pic": "http://wiki.shoryuken.com/images/2/2c/%28yunlp%29.gif",
        "damage": "15",
        "startup": "4",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+1",
        "hit_adv": "+1"
    },
    {
        "name": "mp",
        "desc": "Far Strong",
        "pic": "http://wiki.shoryuken.com/images/1/12/%28yunmp%29.gif",
        "damage": "50",
        "startup": "5",
        "hit": "4",
        "recovery": "12",
        "block_adv": "-3",
        "hit_adv": "-2"
    },
    {
        "name": "hp",
        "desc": "Far Fierce",
        "pic": "http://wiki.shoryuken.com/images/9/9f/%28yunhp%29.gif",
        "damage": "130",
        "startup": "9",
        "hit": "2",
        "recovery": "23",
        "block_adv": "-5",
        "hit_adv": "-3"
    },
    {
        "name": "close.lp",
        "desc": "Close Jab",
        "pic": "http://wiki.shoryuken.com/images/0/0a/%28yuncloselp%29.gif",
        "damage": "15",
        "startup": "3",
        "hit": "2",
        "recovery": "6",
        "block_adv": "+4",
        "hit_adv": "+4"
    },
    {
        "name": "close.mp",
        "desc": "Close Strong",
        "pic": "http://wiki.shoryuken.com/images/b/be/%28yunclosemp%29.gif",
        "damage": "60",
        "startup": "4",
        "hit": "3",
        "recovery": "7",
        "block_adv": "+6",
        "hit_adv": "+7"
    },
    {
        "name": "close.hp",
        "desc": "Close Fierce",
        "pic": "http://wiki.shoryuken.com/images/8/84/%28yunclosehp%29.gif",
        "damage": "110",
        "startup": "6",
        "hit": "3",
        "recovery": "13",
        "block_adv": "-2",
        "hit_adv": "-1"
    },
    {
        "name": "lk",
        "desc": "Short",
        "pic": "http://wiki.shoryuken.com/images/8/8e/%28yunlk%29.gif",
        "damage": "35",
        "startup": "3",
        "hit": "3",
        "recovery": "6",
        "block_adv": "+2",
        "hit_adv": "+2"
    },
    {
        "name": "mk",
        "desc": "Forward",
        "pic": "http://wiki.shoryuken.com/images/d/d0/%28yunmk%29.gif",
        "damage": "80",
        "startup": "9",
        "hit": "3",
        "recovery": "15",
        "block_adv": "-4",
        "hit_adv": "-3"
    },
    {
        "name": "hk",
        "desc": "Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28yunhk%29.gif",
        "damage": "100",
        "startup": "14",
        "hit": "4",
        "recovery": "22",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "close.mk",
        "desc": "Close Forward",
        "pic": "http://wiki.shoryuken.com/images/2/25/%28yunclosemk%29.gif",
        "damage": "30",
        "startup": "5",
        "hit": "9",
        "recovery": "1",
        "block_adv": "-15",
        "hit_adv": "knd"
    },
    {
        "name": "air.lp",
        "desc": "Jump Jab",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28yunjlp%29.gif",
        "damage": "40(60 neutral jump)",
        "startup": "2",
        "hit": "until land",
        "recovery": "N/A",
        "block_adv": "-4~+7",
        "hit_adv": "-4~+7"
    },
    {
        "name": "air.mp",
        "desc": "Jump Strong",
        "pic": "http://wiki.shoryuken.com/images/8/88/%28yunjmp%29.gif",
        "damage": "80",
        "startup": "3",
        "hit": "6(7 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-2~+10",
        "hit_adv": "-2~+10"
    },
    {
        "name": "air.hp",
        "desc": "Jump Fierce",
        "pic": "http://wiki.shoryuken.com/images/1/14/%28yunjhp%29.gif",
        "damage": "100(120 neutral jump)",
        "startup": "5(8 neutral jump)",
        "hit": "4(5 neutral jump)",
        "recovery": "N/A",
        "block_adv": "-4~+10",
        "hit_adv": "-4~+10"
    },
    {
        "name": "air.lk",
        "desc": "Jump Short",
        "pic": "http://wiki.shoryuken.com/images/b/b1/%28yunjlk%29.gif",
        "damage": "40",
        "startup": "3(4 neutral jump)",
        "hit": "12",
        "recovery": "N/A",
        "block_adv": "+1~+7",
        "hit_adv": "+1~+7"
    },
    {
        "name": "air.mk",
        "desc": "Jump Forward",
        "pic": "http://wiki.shoryuken.com/images/5/5f/%28yunjmk%29.gif",
        "damage": "70",
        "startup": "6",
        "hit": "7",
        "recovery": "N/A",
        "block_adv": "-3~+10",
        "hit_adv": "-3~+10"
    },
    {
        "name": "air.hk",
        "desc": "Jump Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/7/7f/%28yunjhk%29.gif",
        "damage": "110",
        "startup": "5",
        "hit": "5",
        "recovery": "N/A",
        "block_adv": "-1~+10",
        "hit_adv": "-1~+10"
    },
    {
        "name": "mp+mk",
        "desc": "Universal Overhead",
        "pic": "http://wiki.shoryuken.com/images/4/44/%28yunoh%29.gif",
        "damage": "40",
        "startup": "15",
        "hit": "9",
        "recovery": "6",
        "block_adv": "-5~+2",
        "hit_adv": "0~+8"
    },
    {
        "name": "lp+lk",
        "desc": "Hiza Geri",
        "pic": "http://wiki.shoryuken.com/images/3/3d/%28yunhg%29.gif",
        "damage": "160",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "f.lp+lk",
        "desc": "Monkey Flip",
        "pic": "http://wiki.shoryuken.com/images/7/75/%28yunmfth%29.gif",
        "damage": "120",
        "startup": "2",
        "hit": "1",
        "recovery": "21",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    },
    {
        "name": "c.lp",
        "desc": "Crouch Jab",
        "pic": "http://wiki.shoryuken.com/images/0/07/%28yunclp%29.gif",
        "damage": "20",
        "startup": "2",
        "hit": "2",
        "recovery": "1",
        "block_adv": "+13",
        "hit_adv": "+14"
    },
    {
        "name": "c.mp",
        "desc": "Crouch Strong",
        "pic": "http://wiki.shoryuken.com/images/1/1c/%28yuncmp%29.gif",
        "damage": "40",
        "startup": "3",
        "hit": "2",
        "recovery": "1",
        "block_adv": "+12",
        "hit_adv": "+13"
    },
    {
        "name": "c.hp",
        "desc": "Crouch Fierce",
        "pic": "http://wiki.shoryuken.com/images/9/9e/%28yunchp%29.gif",
        "damage": "90",
        "startup": "3-10",
        "hit": "1-2",
        "recovery": "1",
        "block_adv": "+12",
        "hit_adv": "+13"
    },
    {
        "name": "c.lk",
        "desc": "Crouch Short",
        "pic": "http://wiki.shoryuken.com/images/7/7b/%28yunclk%29.gif",
        "damage": "20",
        "startup": "2",
        "hit": "2",
        "recovery": "1",
        "block_adv": "+13",
        "hit_adv": "+13"
    },
    {
        "name": "c.mk",
        "desc": "Crouch Forward",
        "pic": "http://wiki.shoryuken.com/images/a/ac/%28yuncmk%29.gif",
        "damage": "30",
        "startup": "3",
        "hit": "2",
        "recovery": "4",
        "block_adv": "+7",
        "hit_adv": "+8"
    },
    {
        "name": "c.hk",
        "desc": "Crouch Roundhouse",
        "pic": "http://wiki.shoryuken.com/images/b/b5/%28yunchk%29.gif",
        "damage": "50",
        "startup": "8",
        "hit": "2",
        "recovery": "9",
        "block_adv": "+5",
        "hit_adv": "knd"
    },
    {
        "name": "f.mk",
        "desc": "Senpuu Kyaku",
        "pic": "http://wiki.shoryuken.com/images/f/f3/%28yunfmk%29.gif",
        "damage": "80",
        "startup": "19",
        "hit": "6",
        "recovery": "18",
        "block_adv": "-1",
        "hit_adv": "0"
    },
    {
        "name": "f.hp",
        "desc": "Dakai",
        "pic": "http://wiki.shoryuken.com/images/a/a6/%28yunfhp%29.gif",
        "damage": "140",
        "startup": "17",
        "hit": "5",
        "recovery": "19",
        "block_adv": "-7",
        "hit_adv": "knd"
    },
    {
        "name": "air.d.mk",
        "desc": "Raigeki Shuu",
        "pic": "http://wiki.shoryuken.com/images/c/c6/%28yunjdk%29.gif",
        "damage": "70",
        "startup": "6/6/8",
        "hit": "land",
        "recovery": "N/A",
        "block_adv": "-3~+10",
        "hit_adv": "-3~+10"
    },
    {
        "name": "qcf.lp",
        "desc": "Zesshou Hohou (Jab)",
        "pic": "http://wiki.shoryuken.com/images/d/d9/%28yunlunge%29.gif",
        "damage": "100",
        "startup": "7",
        "hit": "5",
        "recovery": "22",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.mp",
        "desc": "Zesshou Hohou (Strong)",
        "pic": "http://wiki.shoryuken.com/images/d/d9/%28yunlunge%29.gif",
        "damage": "110",
        "startup": "10",
        "hit": "11",
        "recovery": "16",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.hp",
        "desc": "Zesshou Hohou (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/d/d9/%28yunlunge%29.gif",
        "damage": "120",
        "startup": "13",
        "hit": "15",
        "recovery": "12",
        "block_adv": "-11",
        "hit_adv": "knd"
    },
    {
        "name": "qcf.2p",
        "desc": "Zesshou Hohou (EX)",
        "pic": "http://wiki.shoryuken.com/images/2/22/%28yunlungeex%29.gif",
        "damage": "160",
        "startup": "13-22",
        "hit": "19-6",
        "recovery": "12",
        "block_adv": "-2",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lp",
        "desc": "Tetsu Zankou (Jab)",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28yunshoulder%29.gif",
        "damage": "100",
        "startup": "7",
        "hit": "6",
        "recovery": "13",
        "block_adv": "-1",
        "hit_adv": "+1"
    },
    {
        "name": "dp.mp",
        "desc": "Tetsu Zankou (Strong)",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28yunshoulder%29.gif",
        "damage": "125",
        "startup": "8",
        "hit": "6",
        "recovery": "15",
        "block_adv": "-3",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hp",
        "desc": "Tetsu Zankou (Fierce)",
        "pic": "http://wiki.shoryuken.com/images/1/1d/%28yunshoulder%29.gif",
        "damage": "140",
        "startup": "10",
        "hit": "6",
        "recovery": "17",
        "block_adv": "-5",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2p",
        "desc": "Tetsu Zankou (EX)",
        "pic": "http://wiki.shoryuken.com/images/5/51/%28yunshoulderex%29.gif",
        "damage": "160",
        "startup": "10-17",
        "hit": "7-6",
        "recovery": "19",
        "block_adv": "-7",
        "hit_adv": "knd"
    },
    {
        "name": "dp.lk",
        "desc": "Nishou Kyaku (Short)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28yunkicks%29.gif",
        "damage": "130",
        "startup": "4-13",
        "hit": "2-4",
        "recovery": "25",
        "block_adv": "-25",
        "hit_adv": "knd"
    },
    {
        "name": "dp.mk",
        "desc": "Nishou Kyaku (Forward)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28yunkicks%29.gif",
        "damage": "140",
        "startup": "6-15",
        "hit": "2-4",
        "recovery": "26",
        "block_adv": "-26",
        "hit_adv": "knd"
    },
    {
        "name": "dp.hk",
        "desc": "Nishou Kyaku (Roundhouse)",
        "pic": "http://wiki.shoryuken.com/images/5/55/%28yunkicks%29.gif",
        "damage": "150",
        "startup": "8-17",
        "hit": "2-4",
        "recovery": "28",
        "block_adv": "-28",
        "hit_adv": "knd"
    },
    {
        "name": "dp.2k",
        "desc": "Nishou Kyaku (EX)",
        "pic": "http://wiki.shoryuken.com/images/2/23/%28yunkicksex%29.gif",
        "damage": "170",
        "startup": "4-12",
        "hit": "2-4",
        "recovery": "29",
        "block_adv": "-28",
        "hit_adv": "knd"
    },
    {
        "name": "qcb.lp",
        "desc": "Kobukushi",
        "pic": "http://wiki.shoryuken.com/images/4/44/%28yunpalm%29.gif",
        "damage": "180",
        "startup": "24",
        "hit": "10",
        "recovery": "4",
        "block_adv": "0",
        "hit_adv": "knd"
    },
    {
        "name": "hcb.lk",
        "desc": "Zenpou-Tenshin",
        "pic": "http://wiki.shoryuken.com/images/6/61/%28yuncg%29.gif",
        "damage": "N/A",
        "startup": "5",
        "hit": "2",
        "recovery": "26",
        "block_adv": "N/A",
        "hit_adv": "+16"
    },
    {
        "name": "sa1",
        "desc": "You Hou",
        "pic": "http://wiki.shoryuken.com/images/7/78/%28yunsa1%29.gif",
        "damage": "410",
        "startup": "1+10+45",
        "hit": "9+2+2",
        "recovery": "36",
        "block_adv": "-27",
        "hit_adv": "knd"
    },
    {
        "name": "sa2",
        "desc": "Sourai Rengeki",
        "pic": "http://wiki.shoryuken.com/images/0/08/%28yunsa2%29.gif",
        "damage": "320",
        "startup": "4+20+34+47+66+78",
        "hit": "3+2+3+3+4+2",
        "recovery": "33",
        "block_adv": "-27",
        "hit_adv": "knd"
    },
    {
        "name": "sa3",
        "desc": "Genei Jin",
        "pic": "http://wiki.shoryuken.com/images/f/f3/%28yunsa3%29.gif",
        "damage": "N/A",
        "startup": "10",
        "hit": "N/A",
        "recovery": "N/A",
        "block_adv": "N/A",
        "hit_adv": "N/A"
    }
]